/* Stage 3 V1 retest corrections — base data/helpers. Dashboard intentionally unchanged. */
window.K3=window.K3||{};
K3.TODAY='2026-10-05';
K3.dt=s=>s?new Date(s).toLocaleString('en-GB',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).replace(',',''):'—';
K3.css=`.record-tabs{display:flex;gap:5px;flex-wrap:wrap;border-bottom:1px solid var(--b);margin:13px 0}.record-tabs .tab{white-space:nowrap}.sectionbox{background:#fff;border:1px solid var(--b);border-radius:10px;padding:12px;margin-top:10px}.chips{display:flex;gap:5px;flex-wrap:wrap;margin:6px 0}.chip{display:inline-block;padding:3px 7px;border-radius:999px;background:#f1edf5;color:#4e2d67;font-size:11px;font-weight:700}.chip.bad{background:#fdeceb;color:var(--r)}.chip.good{background:#eaf6ef;color:var(--g)}.planhead{display:flex;justify-content:space-between;gap:6px;align-items:flex-start}.planbuttons{display:flex;gap:4px;flex-wrap:wrap;margin:7px 0}.job .job-actions{display:flex;gap:4px;margin-top:6px}.job.warnjob{border-left-color:#b42318;background:#fff8f7}.current-est{border:2px solid var(--p)!important;box-shadow:0 0 0 2px #5b2b8211}.approval-history{background:#fafafa;border-radius:8px;padding:8px;margin-top:8px}.pricing-box{background:#f6f1f9;border:1px solid #d8c4e6;border-radius:10px;padding:10px;margin:10px 0}.srtbox{background:#f8f8fa;border:1px solid var(--b);border-radius:8px;padding:8px;margin-top:6px}.historyline{padding:7px 0;border-bottom:1px solid var(--b)}.historyline:last-child{border-bottom:0}.danger{color:var(--r);border-color:#e9b9b5}.accountbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.tiny{font-size:11px}.unsuitable{background:#fdf0ef;border:1px solid #efc4bf;color:#912018;padding:6px;border-radius:7px;margin:5px 0}.suitable{background:#edf8f2;border:1px solid #c1e3d0;color:#145c39;padding:6px;border-radius:7px;margin:5px 0}`;
let k3style=document.createElement('style');k3style.textContent=K3.css;document.head.appendChild(k3style);
K3.corrections=[
['DCR-004','Vehicle Records','Vehicle record tabs were visual only; make each section selectable with realistic dummy history.','Defect','P1','Vehicle tabs now select and display Work Orders, mileage, maintenance, compliance, defects, VOR, documents and profitability test data.'],
['DCR-005','Customer Records','Expand Customer record sections while preserving Work Order filters.','Improvement','P1','Added selectable Contacts, Contracts, Sites, Vehicles, Work Orders, Commercial Rules, SLA, Billing and Notification Rules.'],
['DCR-006','Planning','Replace shift placeholder; add shift controls, job reordering, absence types and suitability warnings.','Defect','P1','Create/Edit/Delete/Extend Shift, same-day reorder, Holiday/Sickness/Training/Rest Day and suitability checks added.'],
['DCR-007','Technicians','Expand Technician record information.','Improvement','P1','Working pattern, shifts, absence, skills, qualifications/expiry, authorisations, tools, van and benchmark group added; cost remains restricted.'],
['DCR-008','Estimates','Add full estimate status actions and approval history.','Defect','P1','Viewed/Approve/Decline/Revise/Supersede/Cancel actions and approval evidence history added.'],
['DCR-009','Pricing','Remove universal £80/30% assumption and use effective Customer/Contract pricing rules.','Defect','P1','Effective pricing rule versions now feed Estimate and Billing; audited override supported.'],
['DCR-010','SRT','Add Repair Operation/SRT selector with source and standard time.','Improvement','P1','Repair Operation selector and standard/source/expected/actual labour display added.'],
['DCR-011','Billing','Recalculate final Billing from the same commercial rule source as Estimate.','Defect','P1','Billing recomputes labour, parts, third-party and travel using pricing snapshot/rule; authorised adjustments remain separate.'],
['DCR-012','Billing','Consolidated Billing must never mix customer invoice lines.','Defect','P1','Billing Run now filters strictly by selected Billing Account/Customer and shows per-WO vs monthly consolidated previews.'],
['DCR-013','Defect Register','Allow issues to be edited and progressed without losing history.','Defect','P1','Open/Edit action, controlled workflow statuses, Resolution/Retest editing and append-only change history added.'],
['DCR-014','Date/Time','Normal operations date/time should use DD/MM/YYYY HH:MM without seconds.','Improvement','P1','Normal Operations display now omits seconds; ISO audit timestamps retain full precision internally.']];
K3.pricingRuleFor=function(w){let date=(w&&w.created?String(w.created).slice(0,10):K3.TODAY),ct=w?.ct||w;return (S.pricingRules||[]).filter(r=>r.contract===ct&&r.from<=date&&(!r.to||r.to>=date)).sort((a,b)=>String(b.from).localeCompare(String(a.from)))[0]||{id:'PR-DEFAULT',version:'default',labour:0,partsMarkup:0,thirdMarkup:0,mileage:0,vat:20,label:'No configured rule'}};
window.pricingRuleFor=K3.pricingRuleFor;
K3.estimateTotals=function(v){let labour=(+v.hrs||0)*(+v.rate||0),parts=(+v.parts||0)*(1+(+v.markup||0)/100),third=(+v.thirdCost||0)*(1+(+v.thirdMarkup||0)/100),travel=(+v.miles||0)*(+v.mileageRate||0),net=labour+parts+third+travel+(+v.other||0),vat=net*(+v.vat||20)/100;return{labour,parts,third,travel,net,vat,gross:net+vat}};window.estimateTotals=K3.estimateTotals;
K3.currentVersion=e=>e?.versions?.slice().sort((a,b)=>b.v-a.v).find(v=>!['Superseded','Cancelled'].includes(v.status))||e?.versions?.slice().sort((a,b)=>b.v-a.v)[0];
K3.currentEstimate=w=>(w.ests||[]).flatMap(e=>e.versions.map(v=>({e,v}))).filter(x=>!['Superseded','Cancelled'].includes(x.v.status)).sort((a,b)=>b.v.v-a.v.v)[0]||null;
K3.billRule=w=>K3.currentEstimate(w)?.v?.pricingSnapshot||K3.pricingRuleFor(w);
K3.billableHours=function(w){let mins=0;w.att.forEach(a=>(a.lab||[]).forEach(l=>{if(l[3]&&['Working','Repair','Service','Diagnosis'].includes(l[1]))mins+=+l[2]||0}));return (mins||w.tasks.reduce((s,t)=>s+(+t.actual||0)*60,0))/60};
window.recalcBilling=function(w){let r=K3.billRule(w),hours=K3.billableHours(w),partCost=w.parts.reduce((s,p)=>s+(+p[3]||0)*(+p[4]||0),0),thirdCost=+w.thirdPartyCost||0,miles=w.att.reduce((s,a)=>s+(+a.miles||0),0);w.bill=w.bill||{po:w.po,adjustments:[]};w.bill.adjustments=w.bill.adjustments||[];let adj=w.bill.adjustments.reduce((s,a)=>s+(+a.amount||0),0);Object.assign(w.bill,{ruleId:r.id,pricingVersion:r.version,labourHours:hours,labour:hours*r.labour,partsCost:partCost,parts:partCost*(1+r.partsMarkup/100),thirdCost,third:thirdCost*(1+r.thirdMarkup/100),travelMiles:miles,travel:miles*r.mileage,other:adj,vat:r.vat||20,po:w.po});return w.bill};
K3.ensure=function(){
 S.pricingRules=S.pricingRules||[{id:'PR-CT1-V2',contract:'CT1',version:'v2',from:'2026-07-01',labour:80,partsMarkup:30,thirdMarkup:20,mileage:.85,vat:20,label:'Test Transport Pricing v2'},{id:'PR-CT2-V1',contract:'CT2',version:'v1',from:'2026-03-01',labour:85,partsMarkup:25,thirdMarkup:15,mileage:.90,vat:20,label:'Demo Logistics Pricing v1'}];
 S.srtOps=S.srtOps||[{id:'SRT-BRK-CAL',name:'Replace rear brake caliper',time:1.4,source:'Kooner test SRT library',task:'Repair'},{id:'SRT-SUS-DL',name:'Replace front drop link',time:.8,source:'Kooner test SRT library',task:'Repair'},{id:'SRT-LAMP',name:'Replace side marker lamp',time:.6,source:'Kooner test SRT library',task:'Repair'},{id:'SRT-SVC-ANN',name:'Annual service',time:1.5,source:'Manufacturer / test service schedule',task:'Service'},{id:'SRT-DIAG',name:'General diagnostic inspection',time:.5,source:'Kooner test diagnostic allowance',task:'Diagnosis'},{id:'SRT-TYRE',name:'Tyre puncture repair',time:.5,source:'Kooner test SRT library',task:'Repair'}];
 S.shifts=S.shifts||[{id:'SH1',tech:'T1',date:K3.TODAY,start:'07:00',end:'17:00',base:'West Midlands',status:'Active'},{id:'SH2',tech:'T2',date:K3.TODAY,start:'08:00',end:'16:30',base:'Bristol',status:'Training'},{id:'SH3',tech:'T3',date:K3.TODAY,start:'07:30',end:'17:30',base:'Birmingham',status:'Active'},{id:'SH4',tech:'T4',date:K3.TODAY,start:'08:00',end:'17:00',base:'Birmingham',status:'Rest Day'}];
 let tx={T1:{workingPattern:'Mon–Fri 07:00–17:00',absence:'None',tools:'Diagnostics laptop, brake tools, multimeter',auth:'Breakdown diagnosis; repair within customer authority',expiry:'Driving licence 12/08/2029; EV awareness 30/06/2027'},T2:{workingPattern:'Mon–Fri 08:00–16:30',absence:'Training — 05/10/2026',tools:'Service kit, brake tools, tail-lift diagnostics',auth:'Service and mechanical repair',expiry:'Driving licence 04/03/2030'},T3:{workingPattern:'Mon–Fri 07:30–17:30',absence:'None',tools:'Workshop lift, diagnostics, heavy repair tooling',auth:'Workshop repairs',expiry:'Driving licence 21/11/2028'},T4:{workingPattern:'Mon–Fri 08:00–17:00',absence:'Rest Day — 05/10/2026',tools:'Workshop equipment, diagnostics',auth:'Supervisor approval; workshop release',expiry:'Driving licence 15/01/2029'}};S.techs.forEach(t=>Object.assign(t,tx[t.id]||{}, {qualifications:t.qualifications||t.quals}));
 let vx={V1:{mileageHistory:[['01/08/2026',25110,'Technician App'],['03/09/2026',27120,'Customer update'],['03/10/2026',28140,'Attendance']],compliance:[['MOT','Valid','18/04/2027'],['PMI','Due Soon','15/10/2026'],['Brake check','Due','05/10/2026']],defectsHistory:[['03/10/2026','Rear brake caliper seized','Open / VOR'],['15/08/2026','Marker lamp intermittent','Closed']],vorHistory:[['03/10/2026 09:32','Brake defect','Active','WO-10041']],docs:[['MOT certificate','PDF test record','18/04/2026'],['PMI sheet','PDF test record','15/08/2026']],cost:{revenue:450,cost:286.2}},V2:{mileageHistory:[['20/07/2026',38100,'Service'],['10/09/2026',42540,'Telematics test'],['03/10/2026',44110,'Attendance']],compliance:[['MOT','Valid','10/05/2027'],['Service','Overdue','20/09/2026']],defectsHistory:[['03/10/2026','N/S/F drop link worn','Awaiting Approval']],vorHistory:[],docs:[['Service history','Test document','20/09/2025']],cost:{revenue:675,cost:390.4}},V3:{mileageHistory:[['01/02/2026',50000,'Service'],['25/08/2026',58440,'Attendance'],['05/10/2026',61200,'Planning']],compliance:[['MOT','Valid','02/02/2027'],['Annual service','Planned','05/10/2026']],defectsHistory:[['25/08/2026','Tyre puncture','Closed']],vorHistory:[],docs:[['Service schedule','Test PDF','01/02/2026']],cost:{revenue:920,cost:501.6}},V4:{mileageHistory:[['04/08/2026',30110,'Customer update'],['02/10/2026',33290,'Attendance']],compliance:[['MOT','Valid','04/04/2027'],['Service','Due','04/10/2026']],defectsHistory:[['02/10/2026','Side marker lamp failed','Closed']],vorHistory:[],docs:[['Repair evidence','Test image set','02/10/2026']],cost:{revenue:182.91,cost:91.75}}};S.vehicles.forEach(v=>Object.assign(v,vx[v.id]||{}));
 S.wos.forEach(w=>{w.tasks.forEach(t=>{if(!t.op){let op=S.srtOps.find(o=>o.name.toLowerCase().includes((t.desc||'').toLowerCase().split(' ').slice(-2).join(' ')))||S.srtOps.find(o=>o.task===t.type);if(op){t.op=op.id;t.srt=op.time}}});w.att.forEach((a,i)=>{if(a.seq==null)a.seq=i+1});(w.ests||[]).forEach(e=>e.versions.forEach(v=>{let r=K3.pricingRuleFor(w);v.pricingVersion=v.pricingVersion||r.version;v.pricingRuleId=v.pricingRuleId||r.id;if(v.thirdMarkup==null)v.thirdMarkup=r.thirdMarkup;if(v.mileageRate==null)v.mileageRate=r.mileage;v.approvalHistory=v.approvalHistory||[]}))});
 let p=S.defects.find(x=>x.id==='DCR-003');if(p&&p.status!=='Ready to Test'){p.history=p.history||[];p.history.push({at:new Date().toISOString(),by:'System Build',from:p.status,to:'Ready to Test',note:'Shift controls and planning corrections implemented.'});p.status='Ready to Test';p.resolution='Shift management placeholder replaced with usable prototype controls; ready for retest.';p.retest='Pending Stage 3 retest'}
 K3.corrections.forEach(([id,area,desc,type,priority,resolution])=>{if(!S.defects.some(x=>x.id===id))S.defects.push({id,date:'05/10/2026',area,desc,type,priority,status:'Ready to Test',resolution,retest:'Pending Stage 3 retest',history:[{at:new Date().toISOString(),by:'System Build',from:'New',to:'Ready to Test',note:resolution}]})});S.defects.forEach(x=>x.history=x.history||[{at:new Date().toISOString(),by:'System Build',from:'',to:x.status,note:x.resolution||'Existing register item'}]);save()
};
K3.stripSeconds=function(root=document){let walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode())n.nodeValue=n.nodeValue.replace(/(\d{2}\/\d{2}\/\d{4}),?\s+(\d{2}:\d{2}):\d{2}/g,'$1 $2')};
K3.ensure();K3.stripSeconds();new MutationObserver(()=>K3.stripSeconds()).observe(document.body,{subtree:true,childList:true,characterData:true});