/* Stage 5 Operations/Desktop bridge: Customer Portal launch and actions requiring attention. */
(function(){
 function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function refreshState(){try{S=K5.ensure(JSON.parse(localStorage.getItem('koonerv1')||'null')||S)}catch(e){}}
 function openActions(){refreshState();let rows=(S.portalActions||[]).filter(x=>x.status!=='Resolved').slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));show(`<h3>Customer Portal Actions Requiring Attention</h3><div class=notice>These are actions on existing Kooner records or Portal Requests — not a separate ticketing system.</div>${rows.map(x=>`<div class=att><div class=row><div><b>${esc(x.type)}</b> • ${esc(x.id)}<br><small>${esc(x.userName)} • ${K3.dt?K3.dt(x.createdAt):x.createdAt} • ${esc(x.priority)}</small></div>${badge(x.status||'New')}</div><div>${esc(x.summary)}</div>${x.reason?`<div class=muted>Reason: ${esc(x.reason)}</div>`:''}<div class=toolbar><button class="btn sm" onclick="portalActionDetail('${x.id}')">Open</button><button class="btn sm" onclick="portalActionSet('${x.id}','In Review')">In Review</button><button class="btn sm p" onclick="portalActionSet('${x.id}','Resolved')">Resolve</button></div></div>`).join('')||'<div class="notice good">No open Customer Portal actions.</div>'}<div class=actions><button class=btn onclick=hide()>Close</button></div>`)}
 window.openPortalActions=openActions;
 window.portalActionSet=function(id,status){refreshState();let x=(S.portalActions||[]).find(a=>a.id===id);if(!x)return;x.history=x.history||[];x.history.push({at:new Date().toISOString(),by:'Operations Test User',from:x.status,to:status});x.status=status;if(x.refType==='Work Order'){let w=W(x.refId);if(w.id){w.audit=w.audit||[];w.audit.push([new Date().toISOString(),'Operations Test User','Customer Portal action '+status,`${x.type} • ${x.id}`])}}save();updatePortalCount();openActions()};
 window.portalActionDetail=function(id){refreshState();let x=(S.portalActions||[]).find(a=>a.id===id);if(!x)return;let extra='';if(x.refType==='Portal Request'){let r=(S.portalRequests||[]).find(q=>q.id===x.refId);if(r)extra=`<div class=pricing-box><b>${esc(r.id)} • ${esc(r.registration)}</b><br>${esc(r.requestType)} • ${esc(r.vehicleStatus)}<br>${esc(r.fault)}<br><small>Site: ${esc(SI(r.site).name)} • Caller: ${esc(r.caller)} • Driver: ${esc(r.driver||'—')} • PO: ${esc(r.po||'—')}</small></div><div class=notice>${r.emergency?'<b>Emergency/VOR supporting submission — telephone-first warning shown to customer.</b><br>':''}Request status: ${esc(r.status)}. No technician was auto-dispatched.</div>${r.status==='Awaiting Operations Triage'?`<button class="btn p" onclick="convertPortalRequest('${r.id}','${x.id}')">Create Pending-Triage Work Order</button>`:''}`;}
 if(x.refType==='Work Order'){let w=W(x.refId);if(w.id)extra=`<div class=notice><b>${w.id} • ${V(w.v).reg}</b><br>${esc(w.fault)}<br><button class="btn p" onclick="hide();openWO('${w.id}')">Open Work Order</button></div>`}
 if(x.refType==='Vehicle'){let v=V(x.refId);if(v.id)extra=`<div class=notice><b>${v.reg}</b> • ${v.make} ${v.model}<br>Trusted mileage: ${(+v.miles||0).toLocaleString()} mi</div>`}
 if(x.refType==='Data Change Request'){let r=(S.portalDataChangeRequests||[]).find(q=>q.id===x.refId);if(r)extra=`<div class=notice><b>${esc(r.recordType)} ${esc(r.recordId)}</b><br>${esc(r.currentValue)} → ${esc(r.requestedValue)}<br>Reason: ${esc(r.reason)}</div>`}
 show(`<h3>${esc(x.type)} — ${esc(x.id)}</h3><div class=kv><b>Customer</b><span>${esc(C(x.customer).name)}</span></div><div class=kv><b>Customer user</b><span>${esc(x.userName)}</span></div><div class=kv><b>Received</b><span>${K3.dt?K3.dt(x.createdAt):x.createdAt}</span></div><div class=kv><b>Status</b><span>${esc(x.status)}</span></div><div class=kv><b>Reason</b><span>${esc(x.reason||'—')}</span></div>${extra}<div class=actions><button class=btn onclick=hide()>Close</button><button class=btn onclick="portalActionSet('${x.id}','In Review')">Mark In Review</button><button class="btn p" onclick="portalActionSet('${x.id}','Resolved')">Resolve</button></div>`)};
 window.convertPortalRequest=function(rid,actionId){refreshState();let r=(S.portalRequests||[]).find(x=>x.id===rid);if(!r||r.status!=='Awaiting Operations Triage')return alert('Request is no longer awaiting triage.');let max=Math.max(10000,...(S.wos||[]).map(w=>+(String(w.id).replace(/\D/g,''))||0)),id='WO-'+(max+1),contract=C(r.customer).contract||S.contracts.find(c=>c.c===r.customer)?.id,wo={id,v:r.vehicle,c:r.customer,ct:contract,s:r.site,loc:r.location||SI(r.site).name,caller:r.caller,driver:r.driver,sitec:r.siteContact,update:r.updateContact,auth:r.authoriser,fault:r.fault,cat:r.requestType,pri:r.emergency?'Urgent':'Normal',safe:r.vehicleStatus,vor:/VOR|Unsafe|Roadside/i.test(r.vehicleStatus),po:r.po||'',access:SI(r.site).access,status:'Pending Triage',fin:'Not Started',owner:'Operations',next:'Triage Customer Portal request',due:new Date(Date.now()+4*3600000).toISOString(),created:new Date().toISOString(),archive:false,att:[],tasks:[{id:'TK-'+Date.now(),desc:r.fault,type:r.requestType==='Planned Maintenance'?'Service':'Inspection',status:'Not Started',srt:0,actual:0,out:'',required:true}],ests:[],parts:[],evidence:[],communications:[{id:'COM-'+Date.now(),at:r.submittedAt,sender:r.submittedByName,audience:'Kooner Operations',source:'Customer Portal',message:r.notes||r.fault,visibility:'Customer Visible'}],audit:[[new Date().toISOString(),'Operations Test User','Work Order created from Customer Portal request',`${r.id} • Pending Triage • no auto-dispatch`]]};S.wos.push(wo);r.status='Converted to Work Order';r.workOrder=id;let a=(S.portalActions||[]).find(x=>x.id===actionId);if(a){a.status='Resolved';a.history=a.history||[];a.history.push({at:new Date().toISOString(),by:'Operations Test User',from:'New',to:'Resolved',note:`Converted to ${id}`})}save();updatePortalCount();hide();openWO(id)};
 function updatePortalCount(){let b=document.getElementById('portalActionBtn');if(!b)return;refreshState();let n=(S.portalActions||[]).filter(x=>x.status!=='Resolved').length;b.textContent=`Portal Actions${n?' ('+n+')':''}`}
 let top=document.querySelector('.top');if(top&&!document.getElementById('customerPortalLink')){let a=document.createElement('a');a.id='customerPortalLink';a.href='customer.html';a.target='_blank';a.className='btn';a.textContent='Customer Portal';a.style.textDecoration='none';a.style.whiteSpace='nowrap';let ref=document.getElementById('techMobileLink')||[...top.querySelectorAll('button')].find(x=>x.textContent.includes('New Work Order'));top.insertBefore(a,ref||null);let q=document.createElement('button');q.id='portalActionBtn';q.className='btn';q.onclick=openActions;top.insertBefore(q,[...top.querySelectorAll('button')].find(x=>x.textContent.includes('New Work Order'))||null);updatePortalCount()}
 window.addEventListener('storage',e=>{if(e.key==='koonerv1'){updatePortalCount()}});
 if(new URLSearchParams(location.search).get('customerInit')==='1')setTimeout(()=>location.replace('customer.html'),150);
})();
