/* Stage 4 Technician Mobile core UI — same browser state as Operations/Desktop. */
var S=JSON.parse(localStorage.getItem('koonerv1')||'null');
var K4=window.K4||{};window.K4=K4;
const M=id=>document.getElementById(id), by=(a,id)=>(a||[]).find(x=>x.id===id)||{}, C=id=>by(S.customers,id), V=id=>by(S.vehicles,id), SI=id=>by(S.sites,id), T=id=>by(S.techs,id), W=id=>by(S.wos,id), CT=id=>by(S.contracts,id);
const money=n=>'£'+Number(n||0).toFixed(2);
const fmtDate=s=>s?new Date(s).toLocaleDateString('en-GB'):'—';
const fmtDT=s=>s?new Date(s).toLocaleString('en-GB',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).replace(',',''):'—';
const stat=s=>{let c=['Completed','Operationally Complete','Approved','Synced','Available'].includes(s)?'good':['Dispatched','Accepted','En Route','On Site','In Progress','Awaiting Parts','Awaiting Approval','Planned','Pending Sync'].includes(s)?'warn':['Rejected','VOR','Failed','Conflict','Stopped for Safety'].includes(s)?'bad':'info';return `<span class="st ${c}">${s||'—'}</span>`};
function persist(){localStorage.setItem('koonerv1',JSON.stringify(S))}
function selectedTech(){return T(S.mobileSettings?.selectedTech||'T1')}
function selectedTechId(){return selectedTech().id||'T1'}
function showSheet(html){M('mobileSheet').innerHTML=html;M('mobileModal').classList.add('show')}
function hideSheet(){M('mobileModal').classList.remove('show')}
function audit(w,action,detail){w.audit=w.audit||[];let at=(window.K4&&K4.iso)?K4.iso():new Date().toISOString();w.audit.push([at,selectedTech().name||'Technician Test User',action,detail||'']);queueSync(action,{wo:w.id,detail:detail||''},at);persist()}
function queueSync(type,payload,at){S.mobileSyncQueue=S.mobileSyncQueue||[];let online=S.mobileDevice?.online!==false,id='DEV-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);S.mobileSyncQueue.push({id,device:S.mobileDevice?.id||'KOONER-MOBILE-TEST-01',tech:selectedTechId(),type,payload,eventTime:at||new Date().toISOString(),deviceCaptureTime:new Date().toISOString(),serverSyncTime:online?new Date().toISOString():null,status:online?'Synced':'Pending Sync'});persist()}
function mobileGo(view){window.mobileView=view;document.querySelectorAll('.bottom button').forEach(b=>b.classList.remove('on'));let b=M('nav-'+view);if(b)b.classList.add('on');if(view==='home')renderHome();else if(view==='jobs')renderJobs();else if(view==='sync')renderSync();else renderMore()}
function attendanceJobs(tid){let rows=[];S.wos.forEach(w=>(w.att||[]).forEach(a=>{if((a.tech||[]).includes(tid))rows.push({w,a})}));return rows}
function shiftToday(tid){let day=(window.K4&&K4.today)?K4.today():new Date().toISOString().slice(0,10);return (S.shifts||[]).find(s=>s.tech===tid&&s.date===day)||null}
function jobSort(a,b){return String(a.a.plan||'').localeCompare(String(b.a.plan||''))}
function isDoneStatus(s){return ['Completed','Cancelled','Rejected'].includes(s)}
function activeJobs(tid){return attendanceJobs(tid).filter(x=>!isDoneStatus(x.a.status)).sort(jobSort)}
function completedJobs(tid){return attendanceJobs(tid).filter(x=>x.a.status==='Completed').sort((a,b)=>String(b.a.dep||b.a.plan).localeCompare(String(a.a.dep||a.a.plan)))}
function cardJob(w,a){let v=V(w.v),s=SI(w.s),warning=w.access||s.access||'',urgent=w.pri==='Urgent'||w.vor;return `<div class="card job ${urgent?'urgent':''}" onclick="openMobileJob('${w.id}','${a.id}')"><div class=row><div><div class=reg>${v.reg}</div><b>${w.cat} • ${a.type}</b></div><div class=right>${w.vor?stat('VOR'):''}<br>${stat(a.status)}</div></div><div class=chips><span class=chip>${C(w.c).name}</span><span class=chip>${s.name}</span><span class=chip>${w.pri}</span></div><div class=kv><b>Planned</b><span>${fmtDT(a.plan)}</span></div><div class=kv><b>Fault / request</b><span>${w.fault}</span></div>${warning?`<div class=alertline>Access: ${warning}</div>`:''}</div>`}
function renderHome(){let t=selectedTech(),sh=shiftToday(t.id),jobs=activeJobs(t.id),cur=jobs.find(x=>['Accepted','En Route','On Site','In Progress','Paused'].includes(x.a.status)),next=jobs.find(x=>!cur||x.a.id!==cur.a.id),pending=(S.mobileSyncQueue||[]).filter(x=>x.tech===t.id&&x.status==='Pending Sync').length;M('mobileContent').innerHTML=`<div class="card hero"><div class=row><div><h2>My Day</h2><div class=sub>${t.name} • ${t.role}</div></div>${stat(t.mobileDuty==='Off Duty'?'Off Duty':t.status)}</div><div class=kv><b>Shift</b><span>${sh?sh.start+'–'+sh.end+' • '+sh.status:'No shift scheduled today'}</span></div><div class=kv><b>Assigned van</b><span>${t.van||'—'}</span></div><div class=kv><b>Sync</b><span>${pending?pending+' awaiting sync':'All synced'}</span></div></div>${formalAvailabilityNotice(t,sh)}${cur?`<div class=section-title><h3>Current job</h3></div>${cardJob(cur.w,cur.a)}`:''}${next?`<div class=section-title><h3>Next job</h3></div>${cardJob(next.w,next.a)}`:'<div class="notice good">No further active jobs assigned.</div>'}<div class=section-title><h3>Today's Attendances</h3><span class=muted>${jobs.length} active • ${completedJobs(t.id).length} completed</span></div>${jobs.map(x=>cardJob(x.w,x.a)).join('')||'<div class=card>No active work assigned.</div>'}`}
function formalAvailabilityNotice(t,sh){if(sh&&['Holiday','Sickness','Training','Rest Day'].includes(sh.status))return `<div class=notice bad><b>Operations availability:</b> ${sh.status}. Planning remains authoritative for formal availability.</div>`;return ''}
function renderJobs(){let t=selectedTech(),rows=attendanceJobs(t.id).sort(jobSort);M('mobileContent').innerHTML=`<h2>My Jobs</h2><div class=sub>Only Attendances assigned to ${t.name} are shown.</div>${rows.map(x=>cardJob(x.w,x.a)).join('')||'<div class=card>No assigned jobs.</div>'}`}
function openMobileJob(wid,aid){window.mobileView='job';window.mobileJob={wid,aid};document.querySelectorAll('.bottom button').forEach(b=>b.classList.remove('on'));renderJob(wid,aid)}
function currentJob(){let j=window.mobileJob||{};let w=W(j.wid),a=(w.att||[]).find(x=>x.id===j.aid)||{};return{w,a}}
function renderJob(wid,aid){let w=W(wid),a=(w.att||[]).find(x=>x.id===aid);if(!w.id||!a)return mobileGo('jobs');let v=V(w.v),s=SI(w.s),t=selectedTech(),co=(a.tech||[]).map(T).filter(x=>x.id);let totalMine=(a.timeEntries||[]).filter(x=>x.tech===t.id&&x.end).reduce((n,x)=>n+(x.durationMinutes||0),0);let openTasks=(w.tasks||[]).filter(x=>!['Completed','Cancelled','Resolved by Override'].includes(x.status));M('mobileContent').innerHTML=`<button class="btn small" onclick="mobileGo('jobs')">← Back to My Jobs</button><div class="card hero"><div class=row><div><div class=reg>${v.reg}</div><b>${w.id} • ${a.type}</b></div><div>${w.vor?stat('VOR'):''}<br>${stat(a.status)}</div></div><div class=sub>${C(w.c).name} • ${s.name}</div><div>${w.fault}</div></div>${jobPrimaryActions(w,a)}<div class=section-title><h3>Vehicle & arrival</h3></div><div class=card><div class=kv><b>Registration</b><span><b>${v.reg}</b></span></div><div class=kv><b>Vehicle</b><span>${v.make} ${v.model}</span></div><div class=kv><b>Unit</b><span>${v.unit||'—'}</span></div><div class=kv><b>VIN</b><span>${v.vin||'Secondary / not normally required'}</span></div><div class=kv><b>Location</b><span>${w.loc||s.addr}</span></div>${a.vehicleConfirmation?`<div class="notice ${a.vehicleConfirmation.match?'good':'bad'}">Vehicle confirmation: ${a.vehicleConfirmation.text}</div>`:''}<button class=btn onclick="vehicleConfirmModal('${w.id}','${a.id}')">Confirm Registration / Mismatch</button></div><div class=section-title><h3>Site & access</h3></div>${siteCard(w)}<div class=section-title><h3>Safety</h3></div>${safetyCard(w,a)}<div class=section-title><h3>Tasks</h3><span class=muted>${openTasks.length} unresolved</span></div>${(w.tasks||[]).map(task=>taskCard(w,a,task)).join('')||'<div class=card>No Tasks.</div>'}<div class=section-title><h3>Labour / Time</h3><span class=muted>${totalMine} min recorded by you</span></div>${labourCard(w,a)}<div class=section-title><h3>Evidence</h3><span class=muted>${(w.evidence||[]).filter(e=>e.attendance===a.id).length} items</span></div>${evidenceCard(w,a)}<div class=section-title><h3>Diagnosis / Parts / Follow-on</h3></div><div class=card><div class=twobtn><button class=btn onclick="diagnosisModal('${w.id}','${a.id}')">Diagnosis</button><button class=btn onclick="partModal('${w.id}','${a.id}')">Parts</button></div><div class=twobtn><button class=btn onclick="estimateMobileModal('${w.id}','${a.id}')">Estimate</button><button class=btn onclick="followOnModal('${w.id}','${a.id}')">Follow-on</button></div><button class=btn onclick="exceptionModal('${w.id}','${a.id}')">Report Exception / Escalation</button></div><div class=section-title><h3>Completion</h3></div><div class=card><div class=kv><b>Other technicians</b><span>${co.map(x=>x.name).join(', ')||'—'}</span></div><div class=kv><b>Outstanding Tasks</b><span>${openTasks.length}</span></div><button class="btn p" onclick="completionModal('${w.id}','${a.id}')">Attendance Completion Summary</button></div>`}
function jobPrimaryActions(w,a){let h='';if(a.status==='Dispatched'||a.status==='Planned')h=`<div class=twobtn><button class="btn good" onclick="acceptJob('${w.id}','${a.id}')">Accept</button><button class="btn bad" onclick="rejectJobModal('${w.id}','${a.id}')">Reject</button></div>`;else if(a.status==='Accepted')h=`<button class="btn p" onclick="setJourneyStatus('${w.id}','${a.id}','En Route')">Start Travel / En Route</button>`;else if(a.status==='En Route')h=`<button class="btn p" onclick="setJourneyStatus('${w.id}','${a.id}','On Site')">Arrived On Site</button>`;else if(a.status==='On Site')h=`<button class="btn p" onclick="startWork('${w.id}','${a.id}')">Start Work</button>`;else if(a.status==='In Progress')h=`<div class="notice good"><b>Work in progress.</b> Record Tasks, time, evidence and outcomes below.</div>`;else if(a.status==='Completed')h=`<div class="notice good"><b>Attendance completed.</b> ${w.status==='Operationally Complete'?'Work Order passed the completion gate.':'Master Work Order remains '+w.status+'.'}</div>`;return h}
function siteCard(w){let s=SI(w.s);return `<div class=card><div class=kv><b>Site</b><span>${s.name}</span></div><div class=kv><b>Address</b><span>${s.addr} • ${s.pc}</span></div><div class=kv><b>Access</b><span>${s.access||w.access||'—'}</span></div><div class=kv><b>Keys / security</b><span>${s.keys||'—'}</span></div><div class=kv><b>Parking</b><span>${s.park||'—'}</span></div><div class=kv><b>PPE</b><span>${s.ppe||'—'}</span></div><div class=kv><b>RAMS</b><span>${s.rams||'—'}</span></div><div class=kv><b>Welfare</b><span>${s.welfare||'—'}</span></div><div class=kv><b>Parts</b><span>${s.parts||'—'}</span></div><div class=kv><b>Site contact</b><span>${w.sitec||'—'}</span></div></div>`}
function safetyCard(w,a){if(a.safety)return `<div class="card"><div class="notice ${a.safety.safe?'good':'bad'}"><b>${a.safety.safe?'Safe to Proceed':'Unsafe to Proceed'}</b><br>${a.safety.reason||'Checks completed'}</div><button class=btn onclick="safetyModal('${w.id}','${a.id}')">Review Safety Check</button></div>`;return `<div class=card><div class=notice>Complete the workflow-driven pre-work safety check before starting work.</div><button class="btn p" onclick="safetyModal('${w.id}','${a.id}')">Start Safety Check</button></div>`}
function taskCard(w,a,t){let op=(S.srtOps||[]).find(o=>o.id===t.op),mine=(a.timeEntries||[]).filter(x=>x.tech===selectedTechId()&&x.task===t.id&&x.end).reduce((n,x)=>n+(x.durationMinutes||0),0)/60;return `<div class=task><div class=row><div><b>${t.desc}</b><br><span class=muted>${t.type}</span></div>${stat(t.status)}</div>${op?`<div class=kv><b>Repair Operation</b><span>${op.name}</span></div><div class=kv><b>Standard Time</b><span>${op.time}h • ${op.source}</span></div>`:`<div class=kv><b>SRT / Expected</b><span>${t.srt||0}h</span></div>`}<div class=kv><b>Actual by you</b><span>${mine.toFixed(2)}h</span></div><div class=twobtn><button class=btn onclick="taskModal('${w.id}','${a.id}','${t.id}')">Open Task</button>${!['Completed','Cancelled','Resolved by Override'].includes(t.status)?`<button class="btn good" onclick="completeMobileTask('${w.id}','${a.id}','${t.id}')">Complete</button>`:'<button class=btn disabled disabled>Complete</button>'}</div></div>`}
function labourCard(w,a){let active=S.mobileActiveTimers?.[selectedTechId()],mine=(a.timeEntries||[]).filter(x=>x.tech===selectedTechId());return `<div class=card>${active&&active.attendance===a.id?`<div class=notice good><b>Timer running:</b> ${active.activity}<br><span class=timer>${fmtDT(active.start)}</span></div><button class="btn bad" onclick="stopTimer('${w.id}','${a.id}')">Stop Timer</button>`:`<button class="btn p" onclick="timeModal('${w.id}','${a.id}')">Start Activity Timer</button>`}${mine.slice().reverse().map(x=>`<div class=sync><div><b>${x.activity}</b>${x.task?` • ${by(w.tasks,x.task).desc}`:''}<br><small>${fmtDT(x.start)} → ${x.end?fmtDT(x.end):'Running'} • ${x.durationMinutes||0} min</small></div>${stat(x.syncStatus||'Synced')}</div>`).join('')||'<div class=muted>No time entries by you yet.</div>'}</div>`}
function evidenceCard(w,a){let rows=(w.evidence||[]).filter(e=>e.attendance===a.id);return `<div class=card>${rows.map(e=>`<div class=sync><div><b>${e.type}</b><br><small>${e.description||e.fileName||'Evidence'} • ${fmtDT(e.capturedAt)} • ${e.fileName||'metadata only'}</small></div>${stat(e.syncStatus)}</div>`).join('')||'<div class=muted>No evidence captured for this Attendance.</div>'}<button class=btn onclick="evidenceModal('${w.id}','${a.id}')">+ Add Evidence / Photo</button></div>`}
function renderSync(){let t=selectedTech(),rows=(S.mobileSyncQueue||[]).filter(x=>x.tech===t.id).slice().reverse();M('mobileContent').innerHTML=`<h2>Sync Centre</h2><div class=sub>Stage 4 simulates the approved offline-first event queue.</div><div class="card"><div class=row><div><b>Device</b><br><small>${S.mobileDevice?.id||'Test device'}</small></div>${stat(S.mobileDevice?.online===false?'Offline':'Online')}</div><div class=twobtn><button class=btn onclick="toggleOnline()">Go ${S.mobileDevice?.online===false?'Online':'Offline'}</button><button class="btn p" onclick="syncAll()">Sync Pending</button></div></div>${rows.map(x=>`<div class=card><div class=row><div><b>${x.type}</b><br><small>${x.id}</small></div>${stat(x.status)}</div><div class=kv><b>Event time</b><span>${fmtDT(x.eventTime)}</span></div><div class=kv><b>Device capture</b><span>${fmtDT(x.deviceCaptureTime)}</span></div><div class=kv><b>Server sync</b><span>${fmtDT(x.serverSyncTime)}</span></div>${x.status==='Pending Sync'?`<div class=twobtn><button class=btn onclick="simulateSyncState('${x.id}','Failed')">Simulate Failed</button><button class=btn onclick="simulateSyncState('${x.id}','Conflict')">Simulate Conflict</button></div>`:''}</div>`).join('')||'<div class=card>No mobile events yet.</div>'}`}
function renderMore(){let t=selectedTech(),sh=shiftToday(t.id);M('mobileContent').innerHTML=`<h2>Technician</h2><div class=card><div class=reg>${t.name}</div><div class=kv><b>Role</b><span>${t.role}</span></div><div class=kv><b>Benchmark Group</b><span>${t.group}</span></div><div class=kv><b>Assigned Van</b><span>${t.van||'—'}</span></div><div class=kv><b>Skills</b><span>${t.skills||'—'}</span></div><div class=kv><b>Qualifications</b><span>${t.qualifications||t.quals||'—'}</span></div><div class=kv><b>Formal Shift</b><span>${sh?sh.start+'–'+sh.end+' • '+sh.status:'No shift today'}</span></div><div class=notice>Internal technician hourly cost is restricted and is not shown in the Technician interface.</div><button class="btn ${t.mobileDuty==='Off Duty'?'good':'warn'}" onclick="toggleOffDuty()">${t.mobileDuty==='Off Duty'?'Mark On Duty':'Mark Off Duty'}</button></div><div class=card><h3>Prototype links</h3><a class="btn" style="display:block;text-align:center;text-decoration:none" href="index.html">Open Operations / Desktop</a><div class=notice>Formal Holiday, Sickness, Training, Rest Day and shift management remain controlled by Operations Planning.</div></div>`}
function toggleOnline(){S.mobileDevice=S.mobileDevice||{};S.mobileDevice.online=S.mobileDevice.online===false;persist();updateNetworkButton();if(window.mobileView==='sync')renderSync()}
function updateNetworkButton(){let b=M('netBtn'),online=S.mobileDevice?.online!==false;b.textContent=online?'Online':'Offline';b.classList.toggle('offline',!online)}
function toggleOffDuty(){let t=selectedTech();t.mobileDuty=t.mobileDuty==='Off Duty'?'On Duty':'Off Duty';persist();renderMore()}
function initMobile(){let sel=M('techSelect');sel.innerHTML=S.techs.map(t=>`<option value="${t.id}" ${S.mobileSettings?.selectedTech===t.id?'selected':''}>${t.name}</option>`).join('');sel.onchange=()=>{S.mobileSettings=S.mobileSettings||{};S.mobileSettings.selectedTech=sel.value;persist();mobileGo('home')};updateNetworkButton();mobileGo('home')}
window.addEventListener('storage',e=>{if(e.key==='koonerv1'&&e.newValue){S=JSON.parse(e.newValue);if(window.mobileView==='job'&&window.mobileJob)renderJob(window.mobileJob.wid,window.mobileJob.aid);else mobileGo(window.mobileView||'home')}});
