'use strict';
const crypto=require('crypto');
const {query,tx,bumpStateVersion}=require('./db');
const {isInternal,canAccessCustomer,canAccessSite}=require('./auth');

const transitions={
 workOrder:{'Draft':['Pending Triage','Cancelled'],'Pending Triage':['Planned','Dispatched','On Hold','Cancelled'],'Planned':['Dispatched','On Hold','Cancelled'],'Dispatched':['In Progress','On Hold','Cancelled'],'In Progress':['Awaiting Approval','Awaiting Parts','On Hold','Operationally Complete'],'Awaiting Approval':['In Progress','Awaiting Parts','On Hold','Cancelled'],'Awaiting Parts':['In Progress','Planned','On Hold','Cancelled'],'On Hold':['Pending Triage','Planned','Dispatched','In Progress','Awaiting Approval','Awaiting Parts','Cancelled'],'Operationally Complete':[],'Cancelled':[]},
 attendance:{'Planned':['Dispatched','Cancelled'],'Dispatched':['Accepted','Rejected','Cancelled'],'Accepted':['En Route','On Site','Rejected','Cancelled'],'En Route':['On Site','Rejected'],'On Site':['In Progress','Stopped for Safety'],'In Progress':['Paused','Completed','Stopped for Safety'],'Paused':['In Progress','Completed'],'Stopped for Safety':['In Progress','Completed','Cancelled'],'Completed':[],'Rejected':[],'Cancelled':[]},
 estimate:{'Draft':['Sent','Cancelled'],'Sent':['Viewed','Approved','Declined','Superseded','Cancelled'],'Viewed':['Approved','Declined','Superseded','Cancelled'],'Approved':['Superseded'],'Declined':['Superseded'],'Superseded':[],'Cancelled':[]},
 billing:{'Not Started':['Billing Review','Financially Closed / No Charge'],'Billing Review':['Validated','Financially Closed / No Charge'],'Validated':['Billing Review','Ready to Invoice'],'Ready to Invoice':['Billing Review','Invoiced'],'Invoiced':[],'Financially Closed / No Charge':[]},
 portalRequest:{'Awaiting Operations Triage':['In Review','Converted to Work Order','Rejected / Closed'],'In Review':['Awaiting Operations Triage','Converted to Work Order','Rejected / Closed'],'Emergency / VOR Reviewed':['Awaiting Operations Triage','In Review','Converted to Work Order','Rejected / Closed'],'Converted to Work Order':[],'Rejected / Closed':[]}
};
function assertTransition(kind,from,to){if(from===to)return;if(!(transitions[kind]?.[from]||[]).includes(to))throw Object.assign(new Error(`Invalid ${kind} transition: ${from} → ${to}`),{status:422,code:'BUSINESS_RULE'})}
function requestId(req){return req.id||crypto.randomUUID()}
async function audit(client,req,entityType,entityId,entityRef,action,prev,next,reason){await client.query(`INSERT INTO audit_events(entity_type,entity_id,entity_ref,action,user_id,user_role,source,previous_value,new_value,reason,correlation_id,ip_address,device_metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10,$11,$12,$13::jsonb)`,[entityType,entityId,entityRef,action,req.user?.id||null,req.user?.roles?.[0]||null,req.get('x-kooner-interface')||'API',prev?JSON.stringify(prev):null,next?JSON.stringify(next):null,reason||null,requestId(req),req.ip,JSON.stringify({userAgent:req.get('user-agent')||null})])}
async function idempotent(req,res,action,fn){const key=req.get('idempotency-key');if(!key)return fn();const prev=await query('SELECT response_status,response_body FROM idempotency_keys WHERE key=$1 AND expires_at>now()',[key]);if(prev.rowCount)return res.status(prev.rows[0].response_status).json(prev.rows[0].response_body);const result=await fn(true);if(result&&result.__handled)return result;return result}
async function storeIdempotency(client,key,userId,action,status,body){if(!key)return;await client.query(`INSERT INTO idempotency_keys(key,user_id,action,response_status,response_body,expires_at) VALUES($1,$2,$3,$4,$5::jsonb,now()+interval '24 hours') ON CONFLICT(key) DO NOTHING`,[key,userId,action,status,JSON.stringify(body)])}
async function entityScope(table,legacyRef){const specs={customers:['customers','id','id'],sites:['sites','customer_id','id'],vehicles:['vehicles','customer_id','current_site_id'],work_orders:['work_orders','customer_id','site_id'],invoices:['invoices','customer_id','explicit_site_id'],documents:['documents','customer_id','site_id'],portal_requests:['portal_requests','customer_id','site_id']};const s=specs[table];if(!s)return null;const r=await query(`SELECT id,${s[1]} customer_id,${s[2]} site_id FROM ${s[0]} WHERE legacy_ref=$1`,[legacyRef]);return r.rows[0]||null}
async function requireEntityScope(user,table,legacyRef,{siteRequired=false}={}){const r=await entityScope(table,legacyRef);if(!r)throw Object.assign(new Error('Record not found'),{status:404,code:'NOT_FOUND'});if(isInternal(user))return r;if(!canAccessCustomer(user,r.customer_id))throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'});if(r.site_id&&!canAccessSite(user,r.customer_id,r.site_id))throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'});if(siteRequired&&!r.site_id)throw Object.assign(new Error('Site scope cannot be established'),{status:403,code:'ACCESS_DENIED'});return r}
async function invoiceScope(user,legacyRef){const r=await query('SELECT * FROM invoices WHERE legacy_ref=$1',[legacyRef]);if(!r.rowCount)throw Object.assign(new Error('Invoice not found'),{status:404,code:'NOT_FOUND'});const inv=r.rows[0];if(isInternal(user))return inv;if(!canAccessCustomer(user,inv.customer_id)||!user.permissions.includes('portal.finance'))throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'});const lines=await query(`SELECT DISTINCT COALESCE(il.site_id,w.site_id) site_id FROM invoice_lines il LEFT JOIN work_orders w ON w.id=il.work_order_id WHERE il.invoice_id=$1`,[inv.id]);const siteIds=new Set(lines.rows.map(x=>x.site_id).filter(Boolean).map(String));if(inv.explicit_site_id)siteIds.add(String(inv.explicit_site_id));const allSites=user.permissions.includes('portal.finance.all_sites');if(!siteIds.size&&!allSites)throw Object.assign(new Error('Invoice Site scope cannot be established'),{status:403,code:'ACCESS_DENIED'});if(!allSites){for(const siteId of siteIds)if(!canAccessSite(user,inv.customer_id,siteId))throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'});if(/consolidated|monthly|weekly/i.test(inv.invoice_type))throw Object.assign(new Error('Customer-wide Finance authority required'),{status:403,code:'ACCESS_DENIED'})}return inv}
async function documentScope(user,legacyRef){const r=await query(`SELECT d.*,c.legacy_ref customer_ref,s.legacy_ref site_ref,w.site_id wo_site,v.current_site_id vehicle_site FROM documents d LEFT JOIN customers c ON c.id=d.customer_id LEFT JOIN sites s ON s.id=d.site_id LEFT JOIN work_orders w ON w.id=d.work_order_id LEFT JOIN vehicles v ON v.id=d.vehicle_id WHERE d.legacy_ref=$1`,[legacyRef]);if(!r.rowCount)throw Object.assign(new Error('Document not found'),{status:404,code:'NOT_FOUND'});const d=r.rows[0];if(isInternal(user))return d;if(!d.customer_id||!canAccessCustomer(user,d.customer_id))throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'});if(d.visibility==='Internal Kooner Only')throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'});let site=d.site_id||d.wo_site||d.vehicle_site;if(site&&!canAccessSite(user,d.customer_id,site))throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'});if(d.visibility==='Customer Finance Only'&&!user.permissions.includes('portal.finance'))throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'});if(d.visibility==='Specific Site/User Role'){const data=d.data||{},allowedSites=data.allowedSites||[],allowedRoles=data.allowedRoles||[],allowedUsers=data.allowedUsers||[];if(!allowedSites.length&&!allowedRoles.length&&!allowedUsers.length)throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'});if(allowedSites.length){const rs=await query('SELECT legacy_ref,id FROM sites WHERE legacy_ref=ANY($1::text[])',[allowedSites]);if(!rs.rows.some(s=>canAccessSite(user,d.customer_id,s.id)))throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'})}if(allowedRoles.length&&!allowedRoles.some(x=>user.roles.includes(String(x).toLowerCase().replace(/ /g,'_'))))throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'});if(allowedUsers.length&&!allowedUsers.includes(user.legacy_ref)&&!allowedUsers.includes(user.id))throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'})}if(d.invoice_id){const ir=await query('SELECT legacy_ref FROM invoices WHERE id=$1',[d.invoice_id]);if(ir.rowCount)await invoiceScope(user,ir.rows[0].legacy_ref)}return d}
async function emitEvent(client,eventType,entityType,entityId,entityRef,payload={}){await client.query('INSERT INTO notification_events(event_type,entity_type,entity_id,entity_ref,payload) VALUES($1,$2,$3,$4,$5::jsonb)',[eventType,entityType,entityId,entityRef,JSON.stringify(payload)])}
module.exports={transitions,assertTransition,audit,idempotent,storeIdempotency,requireEntityScope,invoiceScope,documentScope,emitEvent,bumpStateVersion,tx,query};
