'use strict';
const path=require('path');
const crypto=require('crypto');
const express=require('express');
const helmet=require('helmet');
const cookieParser=require('cookie-parser');
const rateLimit=require('express-rate-limit').rateLimit;
const {query,tx,ping,getStateVersion,bumpStateVersion,isProduction}=require('./db');
const {verifyPassword,randomToken,sha256,newTotpSecret,encryptSecret,decryptSecret,verifyTotp}=require('./security');
const {authMiddleware,requireAuth,requirePermission,requireAnyPermission,csrfRequired,isInternal,canAccessCustomer,canAccessSite}=require('./auth');
const {buildLegacyState,upsertLegacyState}=require('./state');
const B=require('./business');

const app=express();
app.set('trust proxy',1);
app.use((req,res,next)=>{req.id=crypto.randomUUID();res.setHeader('X-Request-ID',req.id);const started=Date.now();res.on('finish',()=>console.log(JSON.stringify({level:'info',event:'http_request',requestId:req.id,method:req.method,path:req.originalUrl,status:res.statusCode,durationMs:Date.now()-started,userId:req.user?.id||null})));next()});
app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false}));
app.use(express.json({limit:'2mb'}));
app.use(express.urlencoded({extended:false,limit:'256kb'}));
app.use(cookieParser());
app.use(authMiddleware);

const loginLimiter=rateLimit({windowMs:15*60*1000,limit:12,standardHeaders:true,legacyHeaders:false,message:{error:'RATE_LIMIT',message:'Too many login attempts. Please wait before retrying.'}});
const writeLimiter=rateLimit({windowMs:60*1000,limit:120,standardHeaders:true,legacyHeaders:false});
const cookieOpts={httpOnly:true,secure:isProduction,sameSite:'lax',path:'/',maxAge:8*60*60*1000};
function error(res,status,code,message,req,extra={}){return res.status(status).json({error:code,message,requestId:req.id,...extra})}
function requireVersion(body){const v=Number(body?.version);if(!Number.isFinite(v))throw Object.assign(new Error('Record version is required'),{status:422,code:'VALIDATION'});return v}
function page(req){return{limit:Math.min(Math.max(Number(req.query.limit)||50,1),200),offset:Math.max(Number(req.query.offset)||0,0)}}
function customerScopeSql(user,customerCol='customer_id',siteCol='site_id',start=1){if(isInternal(user))return{sql:'',params:[]};const siteIds=(user.scopes||[]).filter(x=>x.site_id).map(x=>x.site_id);return{sql:` AND ${customerCol}=$${start} AND ${siteCol}=ANY($${start+1}::uuid[])`,params:[user.customer_id,siteIds]}}

app.get('/api/v1/health/live',(req,res)=>res.json({status:'ok',service:'Kooner API',stage:6,time:new Date().toISOString()}));
app.get('/api/v1/health/ready',async(req,res,next)=>{try{const db=await ping();const m=await query('SELECT version FROM schema_migrations ORDER BY version DESC LIMIT 1');res.status(db?200:503).json({status:db?'ready':'not_ready',database:db?'reachable':'unavailable',migration:m.rows[0]?.version||null})}catch(e){next(e)}});
app.get('/api/v1/system/public',(req,res)=>res.json({name:'Kooner Fleet Management System',stage:6,environment:process.env.APP_ENV||'test',mode:'Database/API Backed',externalIntegrations:'Not Connected'}));

app.post('/api/v1/auth/login',loginLimiter,async(req,res,next)=>{try{
 const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),mfaCode=String(req.body.mfaCode||'');
 const r=await query('SELECT * FROM users WHERE lower(email)=lower($1)',[email]);if(!r.rowCount)return error(res,401,'INVALID_LOGIN','Invalid email or password',req);
 const u=r.rows[0];if(!u.active)return error(res,403,'ACCOUNT_INACTIVE','Account is inactive',req);if(u.locked_until&&new Date(u.locked_until)>new Date())return error(res,429,'ACCOUNT_LOCKED','Account temporarily locked after failed logins',req);
 const ok=await verifyPassword(password,u.password_hash);if(!ok){await query(`UPDATE users SET failed_login_count=failed_login_count+1,locked_until=CASE WHEN failed_login_count+1>=5 THEN now()+interval '15 minutes' ELSE locked_until END WHERE id=$1`,[u.id]);return error(res,401,'INVALID_LOGIN','Invalid email or password',req)}
 if(u.mfa_required){if(!u.mfa_secret_encrypted)return error(res,403,'MFA_CONFIGURATION','MFA is required but not configured',req);if(!mfaCode)return res.status(202).json({mfaRequired:true,message:'Authenticator code required'});if(!verifyTotp(decryptSecret(u.mfa_secret_encrypted),mfaCode))return error(res,401,'INVALID_MFA','Invalid authenticator code',req)}
 const raw=randomToken(32),csrf=randomToken(24),hash=sha256(raw);await tx(async c=>{await c.query(`INSERT INTO sessions(user_id,token_hash,csrf_token,expires_at,ip_address,user_agent) VALUES($1,$2,$3,now()+interval '8 hours',$4,$5)`,[u.id,hash,csrf,req.ip,req.get('user-agent')||null]);await c.query('UPDATE users SET failed_login_count=0,locked_until=NULL,last_login_at=now(),updated_at=now() WHERE id=$1',[u.id]);await B.audit(c,req,'User',u.id,u.legacy_ref,'Login',null,{email:u.email},null)});res.cookie('kooner_session',raw,cookieOpts);res.json({ok:true,csrfToken:csrf,user:{id:u.id,name:u.display_name,type:u.user_type}})
}catch(e){next(e)}});
app.post('/api/v1/auth/logout',requireAuth,csrfRequired,async(req,res,next)=>{try{await query('UPDATE sessions SET revoked_at=now() WHERE id=$1',[req.user.session_id]);res.clearCookie('kooner_session',{path:'/'});res.json({ok:true})}catch(e){next(e)}});
app.get('/api/v1/auth/me',requireAuth,(req,res)=>res.json({user:{id:req.user.id,ref:req.user.legacy_ref,email:req.user.email,name:req.user.display_name,type:req.user.user_type,roles:req.user.roles,permissions:req.user.permissions},csrfToken:req.user.csrf_token,expiresAt:req.user.expires_at}));
app.post('/api/v1/auth/mfa/enrol',requireAuth,csrfRequired,async(req,res,next)=>{try{if((process.env.APP_ENV||'test')==='production')return error(res,403,'DEFERRED','Production MFA enrolment/recovery ceremony is not enabled in Stage 6',req);const secret=newTotpSecret();await query('UPDATE users SET mfa_secret_encrypted=$1,mfa_required=false,updated_at=now() WHERE id=$2',[encryptSecret(secret),req.user.id]);res.json({secret,issuer:'Kooner FMS',account:req.user.email,note:'TEST/DEVELOPMENT enrolment only. Confirm with /auth/mfa/confirm.'})}catch(e){next(e)}});
app.post('/api/v1/auth/mfa/confirm',requireAuth,csrfRequired,async(req,res,next)=>{try{const r=await query('SELECT mfa_secret_encrypted FROM users WHERE id=$1',[req.user.id]);if(!r.rows[0]?.mfa_secret_encrypted)return error(res,422,'MFA_NOT_ENROLLED','Start MFA enrolment first',req);if(!verifyTotp(decryptSecret(r.rows[0].mfa_secret_encrypted),req.body.code))return error(res,422,'INVALID_MFA','Authenticator code does not match',req);await query('UPDATE users SET mfa_required=true,updated_at=now() WHERE id=$1',[req.user.id]);res.json({ok:true,mfaRequired:true})}catch(e){next(e)}});

app.get('/api/v1/bootstrap',requireAuth,requirePermission('compat.read'),async(req,res,next)=>{try{res.json(await buildLegacyState(req.user))}catch(e){next(e)}});
app.get('/api/v1/changes',requireAuth,async(req,res,next)=>{try{const version=await getStateVersion();res.json({version,changed:version>Number(req.query.since||0),serverTime:new Date().toISOString()})}catch(e){next(e)}});
app.put('/api/v1/compat/state',writeLimiter,requireAuth,requirePermission('compat.write'),csrfRequired,async(req,res,next)=>{try{const out=await upsertLegacyState(req.body.state||{},req.user,{baseVersion:req.body.baseVersion,source:req.get('x-kooner-interface')||'Compatibility UI',requestId:req.id,ip:req.ip});res.json({ok:true,stateVersion:out.version})}catch(e){next(e)}});

app.get('/api/v1/customers',requireAuth,async(req,res,next)=>{try{const {limit,offset}=page(req);let sql='SELECT legacy_ref,name,account_code,status,version FROM customers WHERE archived_at IS NULL',params=[];if(!isInternal(req.user)){sql+=' AND id=$1';params.push(req.user.customer_id)}params.push(limit,offset);const r=await query(sql+` ORDER BY name LIMIT $${params.length-1} OFFSET $${params.length}`,params);res.json({items:r.rows,limit,offset})}catch(e){next(e)}});
app.get('/api/v1/sites',requireAuth,async(req,res,next)=>{try{const {limit,offset}=page(req);let params=[],sql='SELECT s.legacy_ref,s.name,s.address,s.postcode,c.legacy_ref customer_ref,s.status,s.version FROM sites s JOIN customers c ON c.id=s.customer_id WHERE s.archived_at IS NULL';if(!isInternal(req.user)){const ids=req.user.scopes.filter(x=>x.site_id).map(x=>x.site_id);params=[ids];sql+=' AND s.id=ANY($1::uuid[])'}params.push(limit,offset);const r=await query(sql+` ORDER BY s.name LIMIT $${params.length-1} OFFSET $${params.length}`,params);res.json({items:r.rows,limit,offset})}catch(e){next(e)}});
app.get('/api/v1/vehicles',requireAuth,requireAnyPermission('vehicles.read','workorders.read'),async(req,res,next)=>{try{const {limit,offset}=page(req);let params=[],sql=`SELECT v.legacy_ref,v.registration,v.make,v.model,v.vehicle_type,v.current_mileage,v.status,v.vor,v.version,c.legacy_ref customer_ref,s.legacy_ref site_ref,s.name site_name FROM vehicles v JOIN customers c ON c.id=v.customer_id LEFT JOIN sites s ON s.id=v.current_site_id WHERE v.archived_at IS NULL`;if(req.query.q){params.push('%'+String(req.query.q).toUpperCase()+'%');sql+=` AND upper(v.registration) LIKE $${params.length}`}if(!isInternal(req.user)){params.push(req.user.customer_id);sql+=` AND v.customer_id=$${params.length}`;const ids=req.user.scopes.filter(x=>x.site_id).map(x=>x.site_id);params.push(ids);sql+=` AND v.current_site_id=ANY($${params.length}::uuid[])`}params.push(limit,offset);const r=await query(sql+` ORDER BY v.registration LIMIT $${params.length-1} OFFSET $${params.length}`,params);res.json({items:r.rows,limit,offset})}catch(e){next(e)}});
app.get('/api/v1/vehicles/:ref',requireAuth,requireAnyPermission('vehicles.read','workorders.read'),async(req,res,next)=>{try{const r=await query(`SELECT v.*,c.legacy_ref customer_ref,s.legacy_ref site_ref FROM vehicles v JOIN customers c ON c.id=v.customer_id LEFT JOIN sites s ON s.id=v.current_site_id WHERE v.legacy_ref=$1`,[req.params.ref]);if(!r.rowCount)return error(res,404,'NOT_FOUND','Vehicle not found',req);const v=r.rows[0];if(!isInternal(req.user)&&!canAccessSite(req.user,v.customer_id,v.current_site_id))return error(res,403,'ACCESS_DENIED','ACCESS DENIED / NOT AUTHORISED',req);const base={id:v.legacy_ref,registration:v.registration,customer:v.customer_ref,site:v.site_ref,make:v.make,model:v.model,type:v.vehicle_type,mileage:v.current_mileage,status:v.status,vor:v.vor,version:Number(v.version)};if(isInternal(req.user))Object.assign(base,{vin:v.vin,unitNumber:v.unit_number});res.json(base)}catch(e){next(e)}});

app.get('/api/v1/work-orders',requireAuth,requirePermission('workorders.read'),async(req,res,next)=>{try{const {limit,offset}=page(req);let params=[],sql=`SELECT w.legacy_ref,w.work_type,w.priority,w.fault_description,w.status,w.financial_status,w.current_owner,w.next_action,w.due_at,w.customer_reference,w.vor,w.version,c.legacy_ref customer_ref,s.legacy_ref site_ref,v.registration FROM work_orders w JOIN customers c ON c.id=w.customer_id JOIN sites s ON s.id=w.site_id JOIN vehicles v ON v.id=w.vehicle_id WHERE w.archived_at IS NULL`;if(req.query.status){params.push(req.query.status);sql+=` AND w.status=$${params.length}`}if(req.query.registration){params.push('%'+String(req.query.registration).toUpperCase()+'%');sql+=` AND upper(v.registration) LIKE $${params.length}`}if(!isInternal(req.user)){params.push(req.user.customer_id);sql+=` AND w.customer_id=$${params.length}`;const ids=req.user.scopes.filter(x=>x.site_id).map(x=>x.site_id);params.push(ids);sql+=` AND w.site_id=ANY($${params.length}::uuid[])`}else if(req.user.roles.includes('technician')){params.push(req.user.id);sql+=` AND EXISTS(SELECT 1 FROM attendances a JOIN attendance_resource_assignments ar ON ar.attendance_id=a.id JOIN technicians t ON t.id=ar.technician_id WHERE a.work_order_id=w.id AND t.user_id=$${params.length})`}params.push(limit,offset);const r=await query(sql+` ORDER BY w.updated_at DESC LIMIT $${params.length-1} OFFSET $${params.length}`,params);res.json({items:r.rows,limit,offset})}catch(e){next(e)}});
app.get('/api/v1/work-orders/:ref',requireAuth,requirePermission('workorders.read'),async(req,res,next)=>{try{const r=await query(`SELECT w.*,c.legacy_ref customer_ref,s.legacy_ref site_ref,v.legacy_ref vehicle_ref,v.registration FROM work_orders w JOIN customers c ON c.id=w.customer_id JOIN sites s ON s.id=w.site_id JOIN vehicles v ON v.id=w.vehicle_id WHERE w.legacy_ref=$1`,[req.params.ref]);if(!r.rowCount)return error(res,404,'NOT_FOUND','Work Order not found',req);const w=r.rows[0];if(!isInternal(req.user)&&!canAccessSite(req.user,w.customer_id,w.site_id))return error(res,403,'ACCESS_DENIED','ACCESS DENIED / NOT AUTHORISED',req);if(req.user.roles.includes('technician')){const a=await query(`SELECT 1 FROM attendances a JOIN attendance_resource_assignments ar ON ar.attendance_id=a.id JOIN technicians t ON t.id=ar.technician_id WHERE a.work_order_id=$1 AND t.user_id=$2`,[w.id,req.user.id]);if(!a.rowCount)return error(res,403,'ACCESS_DENIED','ACCESS DENIED / NOT AUTHORISED',req)}const at=await query('SELECT legacy_ref,attendance_type,status,planned_at,arrived_at,departed_at,outcome,version FROM attendances WHERE work_order_id=$1 ORDER BY planned_at',[w.id]);const tasks=await query('SELECT legacy_ref,description,task_type,status,required,srt_expected_hours,actual_hours,version FROM tasks WHERE work_order_id=$1 ORDER BY created_at',[w.id]);res.json({id:w.legacy_ref,customer:w.customer_ref,site:w.site_ref,vehicle:w.vehicle_ref,registration:w.registration,workType:w.work_type,priority:w.priority,fault:w.fault_description,status:w.status,financialStatus:isInternal(req.user)?w.financial_status:undefined,currentOwner:w.current_owner,nextAction:w.next_action,dueAt:w.due_at,customerReference:w.customer_reference,vor:w.vor,version:Number(w.version),attendances:at.rows,tasks:tasks.rows})}catch(e){next(e)}});
app.post('/api/v1/work-orders',writeLimiter,requireAuth,requirePermission('workorders.write'),csrfRequired,async(req,res,next)=>{try{const key=req.get('idempotency-key');if(key){const old=await query('SELECT response_status,response_body FROM idempotency_keys WHERE key=$1 AND expires_at>now()',[key]);if(old.rowCount)return res.status(old.rows[0].response_status).json(old.rows[0].response_body)}const b=req.body;const rel=await query(`SELECT c.id customer_id,s.id site_id,v.id vehicle_id,ct.id contract_id FROM customers c JOIN sites s ON s.customer_id=c.id JOIN vehicles v ON v.customer_id=c.id AND v.current_site_id=s.id LEFT JOIN contracts ct ON ct.customer_id=c.id AND ct.legacy_ref=$4 WHERE c.legacy_ref=$1 AND s.legacy_ref=$2 AND v.legacy_ref=$3`,[b.customer,b.site,b.vehicle,b.contract||null]);if(!rel.rowCount)return error(res,422,'VALIDATION','Customer/Site/Vehicle relationship is invalid',req);const refs=await query("SELECT COALESCE(max((substring(legacy_ref from '[0-9]+'))::int),10000)+1 n FROM work_orders");const ref='WO-'+refs.rows[0].n;const result=await tx(async c=>{const r=await c.query(`INSERT INTO work_orders(legacy_ref,customer_id,contract_id,site_id,vehicle_id,work_type,priority,fault_description,status,financial_status,current_owner,next_action,due_at,customer_reference,vor,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'Pending Triage','Not Started','Operations','Triage new Work Order',$9,$10,$11,$12::jsonb) RETURNING *`,[ref,rel.rows[0].customer_id,rel.rows[0].contract_id,rel.rows[0].site_id,rel.rows[0].vehicle_id,b.workType||'Other',b.priority||'Normal',b.fault||b.description||'No description',b.dueAt||null,b.customerReference||null,!!b.vor,JSON.stringify({source:req.get('x-kooner-interface')||'Operations/Desktop'})]);await B.audit(c,req,'WorkOrder',r.rows[0].id,ref,'Work Order created',null,{status:'Pending Triage'},null);await B.emitEvent(c,'Work Order created','WorkOrder',r.rows[0].id,ref,{});const version=await bumpStateVersion(c);const body={id:ref,status:'Pending Triage',version:Number(r.rows[0].version),stateVersion:version};await B.storeIdempotency(c,key,req.user.id,'work-order-create',201,body);return body});res.status(201).json(result)}catch(e){next(e)}});
app.patch('/api/v1/work-orders/:ref',writeLimiter,requireAuth,requirePermission('workorders.write'),csrfRequired,async(req,res,next)=>{try{const result=await tx(async c=>{const r=await c.query('SELECT * FROM work_orders WHERE legacy_ref=$1 FOR UPDATE',[req.params.ref]);if(!r.rowCount)throw Object.assign(new Error('Work Order not found'),{status:404,code:'NOT_FOUND'});const w=r.rows[0],version=requireVersion(req.body);if(Number(w.version)!==version)throw Object.assign(new Error('Conflict detected'),{status:409,code:'CONFLICT',serverVersion:Number(w.version)});if(req.body.status)B.assertTransition('workOrder',w.status,req.body.status);const nextStatus=req.body.status||w.status;await c.query(`UPDATE work_orders SET status=$2,current_owner=COALESCE($3,current_owner),next_action=COALESCE($4,next_action),due_at=COALESCE($5,due_at),customer_reference=COALESCE($6,customer_reference),fault_description=COALESCE($7,fault_description),version=version+1,updated_at=now() WHERE id=$1`,[w.id,nextStatus,req.body.currentOwner||null,req.body.nextAction||null,req.body.dueAt||null,req.body.customerReference||null,req.body.fault||null]);await B.audit(c,req,'WorkOrder',w.id,w.legacy_ref,'Work Order updated',{status:w.status,version:Number(w.version)},{status:nextStatus,version:Number(w.version)+1},req.body.reason);const sv=await bumpStateVersion(c);return{id:w.legacy_ref,status:nextStatus,version:Number(w.version)+1,stateVersion:sv}});res.json(result)}catch(e){next(e)}});

app.patch('/api/v1/attendances/:ref/status',writeLimiter,requireAuth,requireAnyPermission('workorders.write','technician.mobile'),csrfRequired,async(req,res,next)=>{try{const result=await tx(async c=>{const r=await c.query(`SELECT a.*,w.legacy_ref wo_ref,w.customer_id,w.site_id FROM attendances a JOIN work_orders w ON w.id=a.work_order_id WHERE a.legacy_ref=$1 FOR UPDATE`,[req.params.ref]);if(!r.rowCount)throw Object.assign(new Error('Attendance not found'),{status:404,code:'NOT_FOUND'});const a=r.rows[0],version=requireVersion(req.body);if(Number(a.version)!==version)throw Object.assign(new Error('Conflict detected'),{status:409,code:'CONFLICT',serverVersion:Number(a.version)});if(req.user.roles.includes('technician')){const assigned=await c.query(`SELECT 1 FROM attendance_resource_assignments ar JOIN technicians t ON t.id=ar.technician_id WHERE ar.attendance_id=$1 AND t.user_id=$2`,[a.id,req.user.id]);if(!assigned.rowCount)throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'})}B.assertTransition('attendance',a.status,req.body.status);let arrived=a.arrived_at,departed=a.departed_at;if(req.body.status==='On Site'&&!arrived)arrived=new Date();if(req.body.status==='Completed'&&!departed)departed=new Date();await c.query('UPDATE attendances SET status=$2,arrived_at=$3,departed_at=$4,version=version+1,updated_at=now() WHERE id=$1',[a.id,req.body.status,arrived,departed]);await B.audit(c,req,'Attendance',a.id,a.legacy_ref,'Attendance status changed',{status:a.status},{status:req.body.status},req.body.reason);await B.emitEvent(c,'Attendance status changed','Attendance',a.id,a.legacy_ref,{status:req.body.status,workOrder:a.wo_ref});const sv=await bumpStateVersion(c);return{id:a.legacy_ref,status:req.body.status,version:Number(a.version)+1,stateVersion:sv}});res.json(result)}catch(e){next(e)}});

app.post('/api/v1/estimates/:ref/approve',writeLimiter,requireAuth,requirePermission('estimates.approve'),csrfRequired,async(req,res,next)=>{try{const key=req.get('idempotency-key');if(key){const old=await query('SELECT response_status,response_body FROM idempotency_keys WHERE key=$1 AND expires_at>now()',[key]);if(old.rowCount)return res.status(old.rows[0].response_status).json(old.rows[0].response_body)}const result=await tx(async c=>{const r=await c.query(`SELECT e.id,e.legacy_ref,e.current_version_no,e.status,w.id work_order_id,w.legacy_ref wo_ref,w.customer_id,w.site_id,ev.id version_id,ev.version_no,ev.status version_status,ev.gross FROM estimates e JOIN work_orders w ON w.id=e.work_order_id JOIN estimate_versions ev ON ev.estimate_id=e.id AND ev.version_no=e.current_version_no WHERE e.legacy_ref=$1 FOR UPDATE`,[req.params.ref]);if(!r.rowCount)throw Object.assign(new Error('Estimate not found'),{status:404,code:'NOT_FOUND'});const e=r.rows[0];if(!isInternal(req.user)&&!canAccessSite(req.user,e.customer_id,e.site_id))throw Object.assign(new Error('ACCESS DENIED / NOT AUTHORISED'),{status:403,code:'ACCESS_DENIED'});if(Number(req.body.version)!==Number(e.version_no))throw Object.assign(new Error('Estimate version changed'),{status:409,code:'CONFLICT'});if(!['Sent','Viewed'].includes(e.version_status))throw Object.assign(new Error(`Estimate is already ${e.version_status}`),{status:422,code:'BUSINESS_RULE'});const decision=req.body.decision==='Declined'?'Declined':'Approved';await c.query('UPDATE estimate_versions SET status=$2 WHERE id=$1',[e.version_id,decision]);await c.query('UPDATE estimates SET status=$2,version=version+1,updated_at=now() WHERE id=$1',[e.id,decision]);await c.query(`INSERT INTO estimate_approval_history(estimate_version_id,decision,approver_user_id,approver_name,method,approved_amount,scope,evidence_reference,comments) VALUES($1,$2,$3,$4,'Customer Portal',$5,$6,$7,$8)`,[e.version_id,decision,req.user.id,req.user.display_name,e.gross,req.body.scope||null,req.body.reference||null,req.body.comments||null]);await c.query(`UPDATE work_orders SET status=CASE WHEN $2='Approved' THEN 'In Progress' ELSE 'Awaiting Approval' END,current_owner='Operations',next_action=CASE WHEN $2='Approved' THEN 'Continue approved work' ELSE 'Review declined Estimate' END,version=version+1,updated_at=now() WHERE id=$1`,[e.work_order_id,decision]);await B.audit(c,req,'Estimate',e.id,e.legacy_ref,`Estimate ${decision}`,{status:e.version_status,version:e.version_no},{status:decision,version:e.version_no},req.body.comments);await B.emitEvent(c,`Estimate ${decision}`,'Estimate',e.id,e.legacy_ref,{workOrder:e.wo_ref});const sv=await bumpStateVersion(c);const body={id:e.legacy_ref,version:e.version_no,status:decision,stateVersion:sv};await B.storeIdempotency(c,key,req.user.id,'estimate-response',200,body);return body});res.json(result)}catch(e){next(e)}});

app.post('/api/v1/pricing/calculate',requireAuth,requireAnyPermission('estimates.write','billing.write','estimates.read'),csrfRequired,async(req,res,next)=>{try{const {contractRef,effectiveDate,labourHours=0,partsCost=0,thirdPartyCost=0,miles=0,other=0}=req.body;const r=await query(`SELECT pr.legacy_ref,prv.* FROM pricing_rules pr JOIN contracts c ON c.id=pr.contract_id JOIN pricing_rule_versions prv ON prv.pricing_rule_id=pr.id WHERE c.legacy_ref=$1 AND prv.effective_from<=$2::date AND (prv.effective_to IS NULL OR prv.effective_to>=$2::date) ORDER BY prv.effective_from DESC LIMIT 1`,[contractRef,effectiveDate||new Date().toISOString().slice(0,10)]);if(!r.rowCount)return error(res,404,'NOT_FOUND','No applicable Pricing Rule Version',req);const p=r.rows[0],lab=Number(labourHours)*Number(p.labour_rate),parts=Number(partsCost)*(1+Number(p.parts_markup_percent)/100),third=Number(thirdPartyCost)*(1+Number(p.third_party_markup_percent)/100),travel=Number(miles)*Number(p.mileage_rate),net=lab+parts+third+travel+Number(other),vat=Math.round(net*Number(p.vat_percent))/100,gross=net+vat;res.json({pricingRule:p.legacy_ref,version:p.version_no,labour:Number(lab.toFixed(2)),parts:Number(parts.toFixed(2)),thirdParty:Number(third.toFixed(2)),travel:Number(travel.toFixed(2)),other:Number(other),net:Number(net.toFixed(2)),vat:Number(vat.toFixed(2)),gross:Number(gross.toFixed(2))})}catch(e){next(e)}});

app.post('/api/v1/maintenance/fixed/calculate',requireAuth,requireAnyPermission('billing.read','billing.write'),csrfRequired,async(req,res,next)=>{try{const period=String(req.body.period||'');if(!/^\d{4}-\d{2}$/.test(period))return error(res,422,'VALIDATION','Billing period must be YYYY-MM',req);const start=`${period}-01`,end=new Date(Number(period.slice(0,4)),Number(period.slice(5,7)),0).toISOString().slice(0,10);const rows=await query(`SELECT ca.legacy_ref assignment_ref,p.legacy_ref plan_ref,v.legacy_ref vehicle_ref,rv.version_no,rv.monthly_rate,GREATEST(ca.effective_from,$1::date) active_from,LEAST(COALESCE(ca.effective_to,$2::date),$2::date) active_to FROM coverage_assignments ca JOIN fixed_maintenance_plans p ON p.id=ca.plan_id LEFT JOIN vehicles v ON v.id=ca.vehicle_id JOIN LATERAL(SELECT * FROM effective_rate_versions r WHERE r.plan_id=p.id AND r.effective_from<=$2::date AND (r.effective_to IS NULL OR r.effective_to>=$1::date) ORDER BY r.effective_from DESC LIMIT 1) rv ON true WHERE ca.active=true AND ca.effective_from<=$2::date AND (ca.effective_to IS NULL OR ca.effective_to>=$1::date)`,[start,end]);const daysInMonth=Number(end.slice(8,10));let total=0;const lines=rows.rows.map(x=>{const from=new Date(x.active_from),to=new Date(x.active_to),activeDays=Math.max(0,Math.floor((to-from)/86400000)+1),amount=Math.round((Number(x.monthly_rate)*activeDays/daysInMonth)*100)/100;total+=amount;return{assignment:x.assignment_ref,plan:x.plan_ref,vehicle:x.vehicle_ref,rateVersion:x.version_no,monthlyRate:Number(x.monthly_rate),activeDays,daysInMonth,amount}});res.json({period,lines,total:Number(total.toFixed(2)),formula:'Plan → Coverage Assignment → Effective Rate Version → Billing Period'})}catch(e){next(e)}});

app.post('/api/v1/billing/work-orders/:ref/transition',writeLimiter,requireAuth,requirePermission('billing.write'),csrfRequired,async(req,res,next)=>{try{const result=await tx(async c=>{const r=await c.query('SELECT * FROM work_orders WHERE legacy_ref=$1 FOR UPDATE',[req.params.ref]);if(!r.rowCount)throw Object.assign(new Error('Work Order not found'),{status:404,code:'NOT_FOUND'});const w=r.rows[0];requireVersion(req.body);if(Number(w.version)!==Number(req.body.version))throw Object.assign(new Error('Conflict detected'),{status:409,code:'CONFLICT',serverVersion:Number(w.version)});B.assertTransition('billing',w.financial_status,req.body.status);if(req.body.status==='Validated'){const p=await c.query(`SELECT count(*)::int n FROM technician_labour_reviews WHERE work_order_id=$1 AND status NOT IN ('Approved','Not Chargeable')`,[w.id]);if(p.rows[0].n)throw Object.assign(new Error('Technician Labour Review remains unresolved'),{status:422,code:'BUSINESS_RULE'})}await c.query('UPDATE work_orders SET financial_status=$2,version=version+1,updated_at=now() WHERE id=$1',[w.id,req.body.status]);if(req.body.status==='Financially Closed / No Charge'){if(!req.body.reason)throw Object.assign(new Error('No Charge closure reason required'),{status:422,code:'VALIDATION'});await c.query('INSERT INTO no_charge_closures(work_order_id,reason,authorised_by) VALUES($1,$2,$3) ON CONFLICT(work_order_id) DO NOTHING',[w.id,req.body.reason,req.user.id])}await B.audit(c,req,'WorkOrder',w.id,w.legacy_ref,'Billing status changed',{financialStatus:w.financial_status},{financialStatus:req.body.status},req.body.reason);const sv=await bumpStateVersion(c);return{id:w.legacy_ref,financialStatus:req.body.status,version:Number(w.version)+1,stateVersion:sv}});res.json(result)}catch(e){next(e)}});

app.get('/api/v1/invoices/:ref',requireAuth,async(req,res,next)=>{try{const inv=await B.invoiceScope(req.user,req.params.ref);const lines=await query('SELECT line_type,description,amount,source_ref FROM invoice_lines WHERE invoice_id=$1',[inv.id]);res.json({id:inv.legacy_ref,type:inv.invoice_type,status:inv.status,issueDate:inv.issue_date,net:Number(inv.net),vat:Number(inv.vat),gross:Number(inv.gross),lines:lines.rows})}catch(e){next(e)}});
app.get('/api/v1/documents/:ref',requireAuth,requirePermission('documents.read'),async(req,res,next)=>{try{const d=await B.documentScope(req.user,req.params.ref);res.json({id:d.legacy_ref,filename:d.filename,mimeType:d.mime_type,size:d.size_bytes,visibility:d.visibility,storageStatus:d.storage_status,uploadedAt:d.uploaded_at})}catch(e){next(e)}});
app.get('/api/v1/documents/:ref/download',requireAuth,requirePermission('documents.read'),async(req,res,next)=>{try{const d=await B.documentScope(req.user,req.params.ref);if(!d.storage_key)return res.status(501).json({error:'STORAGE_PROVIDER_DEFERRED',message:'Document metadata and authorisation are active; production binary object storage is not connected in Stage 6.',requestId:req.id});return error(res,501,'STORAGE_PROVIDER_DEFERRED','Secure binary storage provider is not connected',req)}catch(e){next(e)}});

app.post('/api/v1/portal/requests',writeLimiter,requireAuth,requirePermission('portal.submit'),csrfRequired,async(req,res,next)=>{try{if(req.user.user_type!=='customer')return error(res,403,'ACCESS_DENIED','Customer Portal user required',req);const key=req.get('idempotency-key');if(key){const old=await query('SELECT response_status,response_body FROM idempotency_keys WHERE key=$1 AND expires_at>now()',[key]);if(old.rowCount)return res.status(old.rows[0].response_status).json(old.rows[0].response_body)}const b=req.body;const rel=await query(`SELECT v.id vehicle_id,v.customer_id,v.current_site_id,s.legacy_ref site_ref,v.registration FROM vehicles v JOIN sites s ON s.id=v.current_site_id WHERE v.legacy_ref=$1`,[b.vehicle]);if(!rel.rowCount||!canAccessSite(req.user,rel.rows[0].customer_id,rel.rows[0].current_site_id))return error(res,403,'ACCESS_DENIED','ACCESS DENIED / NOT AUTHORISED',req);const ref='PR-'+Date.now();const result=await tx(async c=>{const p=await c.query(`INSERT INTO portal_requests(legacy_ref,customer_id,site_id,vehicle_id,submitted_by,request_type,vehicle_status,description,status,emergency,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'Awaiting Operations Triage',$9,$10::jsonb) RETURNING id,version`,[ref,rel.rows[0].customer_id,rel.rows[0].current_site_id,rel.rows[0].vehicle_id,req.user.id,b.requestType||'Other',b.vehicleStatus||null,b.description||b.fault||'No description',!!b.emergency,JSON.stringify(b)]);await c.query(`INSERT INTO portal_actions(legacy_ref,customer_id,action_type,ref_type,ref_id,ref_legacy,summary,priority,status,data) VALUES($1,$2,$3,'Portal Request',$4,$5,$6,$7,'New',$8::jsonb)`,[`PA-${Date.now()}`,rel.rows[0].customer_id,b.emergency?'Emergency / VOR Portal Request':'New Customer Request',p.rows[0].id,ref,`${rel.rows[0].registration} • ${b.description||b.fault||''}`,b.emergency?'Urgent':'Normal',JSON.stringify({request:ref})]);await B.audit(c,req,'PortalRequest',p.rows[0].id,ref,'Customer Portal request submitted',null,{status:'Awaiting Operations Triage'},b.reason);await B.emitEvent(c,'Portal request submitted','PortalRequest',p.rows[0].id,ref,{emergency:!!b.emergency});const sv=await bumpStateVersion(c);const body={id:ref,status:'Awaiting Operations Triage',emergency:!!b.emergency,stateVersion:sv};await B.storeIdempotency(c,key,req.user.id,'portal-request',201,body);return body});res.status(201).json(result)}catch(e){next(e)}});
app.post('/api/v1/portal/requests/:ref/triage',writeLimiter,requireAuth,requirePermission('portal.actions'),csrfRequired,async(req,res,next)=>{try{const result=await tx(async c=>{const r=await c.query('SELECT * FROM portal_requests WHERE legacy_ref=$1 FOR UPDATE',[req.params.ref]);if(!r.rowCount)throw Object.assign(new Error('Portal Request not found'),{status:404,code:'NOT_FOUND'});const p=r.rows[0],decision=req.body.decision,reason=String(req.body.reason||'').trim();if(!reason)throw Object.assign(new Error('Reason/notes required'),{status:422,code:'VALIDATION'});let status=p.status;if(['Emergency reviewed – follow standard triage','Telephone contact completed – continue triage'].includes(decision)){status='Awaiting Operations Triage'}else if(decision==='Recovery/escalation arranged'){status='In Review'}else if(decision==='Customer advised – no attendance required'){status='Rejected / Closed'}else if(decision==='Mark In Review'){status='In Review'}else if(decision==='Reject / Close'){status='Rejected / Closed'}else throw Object.assign(new Error('Unsupported triage decision'),{status:422,code:'VALIDATION'});B.assertTransition('portalRequest',p.status,status);await c.query(`UPDATE portal_requests SET status=$2,data=jsonb_set(COALESCE(data,'{}'::jsonb),'{operationsOutcome}',$3::jsonb,true),version=version+1,updated_at=now() WHERE id=$1`,[p.id,status,JSON.stringify({decision,reason,by:req.user.display_name,at:new Date().toISOString()})]);if(status==='Rejected / Closed')await c.query("UPDATE portal_actions SET status='Resolved',resolved_at=now(),data=jsonb_set(COALESCE(data,'{}'::jsonb),'{resolution}',$2::jsonb,true) WHERE ref_id=$1 AND ref_type='Portal Request'",[p.id,JSON.stringify({decision,reason})]);else await c.query("UPDATE portal_actions SET status='In Review',resolved_at=NULL WHERE ref_id=$1 AND ref_type='Portal Request'",[p.id]);await B.audit(c,req,'PortalRequest',p.id,p.legacy_ref,'Portal Request triage outcome',{status:p.status},{status,decision},reason);const sv=await bumpStateVersion(c);return{id:p.legacy_ref,status,decision,stateVersion:sv}});res.json(result)}catch(e){next(e)}});

app.post('/api/v1/sync/events',writeLimiter,requireAuth,requirePermission('sync.write'),csrfRequired,async(req,res,next)=>{try{const b=req.body;if(!b.eventId||!b.deviceId||!b.eventType)return error(res,422,'VALIDATION','eventId, deviceId and eventType are required',req);const existing=await query('SELECT sync_status,resolution FROM sync_events WHERE event_id=$1',[b.eventId]);if(existing.rowCount)return res.json({eventId:b.eventId,status:existing.rows[0].sync_status,idempotentReplay:true,resolution:existing.rows[0].resolution});const result=await tx(async c=>{let wo=null,att=null,task=null;if(b.workOrder)wo=(await c.query('SELECT * FROM work_orders WHERE legacy_ref=$1',[b.workOrder])).rows[0];if(b.attendance)att=(await c.query('SELECT * FROM attendances WHERE legacy_ref=$1',[b.attendance])).rows[0];if(b.task)task=(await c.query('SELECT * FROM tasks WHERE legacy_ref=$1',[b.task])).rows[0];const serverVersion=att?Number(att.version):task?Number(task.version):wo?Number(wo.version):null;if(b.baseVersion!=null&&serverVersion!=null&&Number(b.baseVersion)!==serverVersion){const se=(await c.query(`INSERT INTO sync_events(event_id,user_id,device_id,work_order_id,attendance_id,task_id,event_type,event_timestamp,device_capture_timestamp,payload,base_version,sync_status,server_value,device_value) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,'Conflict',$12::jsonb,$13::jsonb) RETURNING id`,[b.eventId,req.user.id,b.deviceId,wo?.id||null,att?.id||null,task?.id||null,b.eventType,b.eventTime||new Date(),b.deviceCaptureTime||new Date(),JSON.stringify(b.payload||{}),b.baseVersion,JSON.stringify({version:serverVersion,status:att?.status||task?.status||wo?.status}),JSON.stringify(b.payload||{})])).rows[0];await c.query(`INSERT INTO conflicts(sync_event_id,entity_type,entity_id,server_version,device_version,server_value,device_value) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb)`,[se.id,att?'Attendance':task?'Task':'WorkOrder',att?.id||task?.id||wo?.id,serverVersion,b.baseVersion,JSON.stringify({version:serverVersion,status:att?.status||task?.status||wo?.status}),JSON.stringify(b.payload||{})]);return{eventId:b.eventId,status:'Conflict',serverVersion}}
   if(b.eventType==='attendance.status'&&att){B.assertTransition('attendance',att.status,b.payload.status);await c.query('UPDATE attendances SET status=$2,version=version+1,updated_at=now() WHERE id=$1',[att.id,b.payload.status])}else if(b.eventType==='time.entry'&&att&&wo){const tr=(await c.query('SELECT id FROM technicians WHERE user_id=$1',[req.user.id])).rows[0];if(!tr)throw Object.assign(new Error('Technician profile not linked'),{status:422,code:'BUSINESS_RULE'});await c.query(`INSERT INTO labour_time_entries(legacy_ref,technician_id,work_order_id,attendance_id,task_id,activity_type,started_at,ended_at,duration_minutes,chargeability_review_required,chargeability_reason,source,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'Technician Mobile',$12::jsonb) ON CONFLICT(legacy_ref) DO NOTHING`,[b.payload.id||b.eventId,tr.id,wo.id,att.id,task?.id||null,b.payload.activity||'Working',b.payload.start,b.payload.end||null,b.payload.durationMinutes||null,!!b.payload.chargeabilityReview,b.payload.chargeabilityReason||null,JSON.stringify(b.payload)])}else if(b.eventType==='task.complete'&&task){await c.query("UPDATE tasks SET status='Completed',version=version+1,updated_at=now() WHERE id=$1",[task.id])}else throw Object.assign(new Error('Unsupported or incomplete sync event payload'),{status:422,code:'VALIDATION'});
   await c.query(`INSERT INTO sync_events(event_id,user_id,device_id,work_order_id,attendance_id,task_id,event_type,event_timestamp,device_capture_timestamp,payload,base_version,sync_status,resolution) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,'Accepted',$12::jsonb)`,[b.eventId,req.user.id,b.deviceId,wo?.id||null,att?.id||null,task?.id||null,b.eventType,b.eventTime||new Date(),b.deviceCaptureTime||new Date(),JSON.stringify(b.payload||{}),b.baseVersion,JSON.stringify({serverSyncTime:new Date().toISOString()})]);await B.audit(c,req,'SyncEvent',null,b.eventId,'Offline event accepted',null,b.payload,null);const sv=await bumpStateVersion(c);return{eventId:b.eventId,status:'Accepted',stateVersion:sv}});res.json(result)}catch(e){next(e)}});
app.get('/api/v1/sync/conflicts',requireAuth,requireAnyPermission('sync.write','portal.actions'),async(req,res,next)=>{try{const r=await query(`SELECT c.id,se.event_id,se.device_id,se.event_type,se.event_timestamp,c.entity_type,c.server_value,c.device_value,c.status,c.resolution FROM conflicts c JOIN sync_events se ON se.id=c.sync_event_id WHERE c.status='Open' ORDER BY c.created_at DESC LIMIT 100`);res.json({items:r.rows})}catch(e){next(e)}});
app.post('/api/v1/sync/conflicts/:id/resolve',requireAuth,requirePermission('portal.actions'),csrfRequired,async(req,res,next)=>{try{const reason=String(req.body.reason||'').trim(),decision=req.body.decision;if(!reason||!['Keep Server','Retry Device Event','Apply Device Change After Review'].includes(decision))return error(res,422,'VALIDATION','Valid decision and reason are required',req);await tx(async c=>{const r=await c.query('SELECT * FROM conflicts WHERE id=$1 FOR UPDATE',[req.params.id]);if(!r.rowCount)throw Object.assign(new Error('Conflict not found'),{status:404,code:'NOT_FOUND'});await c.query(`UPDATE conflicts SET status='Resolved',resolution=$2,resolved_by=$3,resolved_at=now() WHERE id=$1`,[r.rows[0].id,JSON.stringify({decision,reason}),req.user.id]);await c.query(`UPDATE sync_events SET sync_status=$2,resolution=$3::jsonb WHERE id=$1`,[r.rows[0].sync_event_id,decision==='Keep Server'?'Discarded':'Operations Review',JSON.stringify({decision,reason})]);await B.audit(c,req,'Conflict',r.rows[0].id,null,'Sync conflict resolved',r.rows[0],{decision},reason)});res.json({ok:true,decision})}catch(e){next(e)}});

app.get('/api/v1/search',requireAuth,requirePermission('search'),async(req,res,next)=>{try{const q=String(req.query.q||'').trim();if(q.length<2)return res.json({items:[]});const like='%'+q+'%';const rows=[];const w=await query(`SELECT 'Work Order' type,w.legacy_ref ref,w.fault_description label,c.legacy_ref customer_ref,s.legacy_ref site_ref FROM work_orders w JOIN customers c ON c.id=w.customer_id JOIN sites s ON s.id=w.site_id WHERE w.legacy_ref ILIKE $1 OR w.customer_reference ILIKE $1 OR w.fault_description ILIKE $1 LIMIT 20`,[like]);const v=await query(`SELECT 'Vehicle' type,v.legacy_ref ref,v.registration||' • '||COALESCE(v.make,'')||' '||COALESCE(v.model,'') label,c.legacy_ref customer_ref,s.legacy_ref site_ref FROM vehicles v JOIN customers c ON c.id=v.customer_id LEFT JOIN sites s ON s.id=v.current_site_id WHERE v.registration ILIKE $1 LIMIT 20`,[like]);for(const x of [...w.rows,...v.rows]){if(isInternal(req.user))rows.push(x);else{const cr=(await query('SELECT id FROM customers WHERE legacy_ref=$1',[x.customer_ref])).rows[0];const sr=(await query('SELECT id FROM sites WHERE legacy_ref=$1',[x.site_ref])).rows[0];if(cr&&sr&&canAccessSite(req.user,cr.id,sr.id))rows.push(x)}}res.json({items:rows.slice(0,30)})}catch(e){next(e)}});

app.get('/api/v1/audit',requireAuth,requirePermission('audit.read'),async(req,res,next)=>{try{const {limit,offset}=page(req);const r=await query('SELECT id,entity_type,entity_ref,action,user_role,source,reason,correlation_id,created_at FROM audit_events ORDER BY created_at DESC LIMIT $1 OFFSET $2',[limit,offset]);res.json({items:r.rows,limit,offset})}catch(e){next(e)}});
app.get('/api/v1/dcr',requireAuth,requirePermission('dcr.read'),async(req,res,next)=>{try{const {limit,offset}=page(req);const r=await query('SELECT dcr_ref,area,description,item_type,priority,status,resolution,retest_result,deferred,updated_at FROM dcr_items ORDER BY dcr_ref LIMIT $1 OFFSET $2',[limit,offset]);res.json({items:r.rows,limit,offset})}catch(e){next(e)}});
app.get('/api/v1/integrations',requireAuth,async(req,res,next)=>{try{const r=await query('SELECT code,name,status,enabled FROM integration_providers ORDER BY name');res.json({items:r.rows})}catch(e){next(e)}});
app.get('/api/v1/export/work-orders.csv',requireAuth,requirePermission('import.export'),async(req,res,next)=>{try{let params=[],sql=`SELECT w.legacy_ref,c.name customer,s.name site,v.registration,w.work_type,w.status,w.financial_status,w.customer_reference,w.created_at FROM work_orders w JOIN customers c ON c.id=w.customer_id JOIN sites s ON s.id=w.site_id JOIN vehicles v ON v.id=w.vehicle_id WHERE 1=1`;if(!isInternal(req.user)){params.push(req.user.customer_id);sql+=` AND w.customer_id=$1`;const ids=req.user.scopes.filter(x=>x.site_id).map(x=>x.site_id);params.push(ids);sql+=` AND w.site_id=ANY($2::uuid[])`}const r=await query(sql+' ORDER BY w.created_at DESC',params);const esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv=['Work Order,Customer,Site,Registration,Work Type,Status,Financial Status,Customer Reference,Created',...r.rows.map(x=>[x.legacy_ref,x.customer,x.site,x.registration,x.work_type,x.status,x.financial_status,x.customer_reference,x.created_at].map(esc).join(','))].join('\n');res.type('text/csv').send(csv)}catch(e){next(e)}});
app.post('/api/v1/import/vehicle-batches',requireAuth,requirePermission('import.export'),csrfRequired,async(req,res,next)=>{try{const batch='IMP-'+Date.now(),rows=Array.isArray(req.body.rows)?req.body.rows:[];const id=await tx(async c=>{const b=(await c.query("INSERT INTO import_batches(batch_ref,import_type,status,created_by,mapping) VALUES($1,'Vehicle','Preview',$2,$3::jsonb) RETURNING id",[batch,req.user.id,JSON.stringify(req.body.mapping||{})])).rows[0].id;for(let i=0;i<rows.length;i++){const r=rows[i],errs=[];if(!r.registration)errs.push('Registration required');if(!r.customer)errs.push('Customer required');if(!r.site)errs.push('Site required');await c.query('INSERT INTO import_rows(batch_id,row_key,raw_data,mapped_data,validation_errors,status) VALUES($1,$2,$3::jsonb,$4::jsonb,$5::jsonb,$6)',[id,String(r.rowId||i+1),JSON.stringify(r),JSON.stringify(r),JSON.stringify(errs),errs.length?'Error':'Valid'])}return id});res.status(201).json({batchRef:batch,id,status:'Preview',rowCount:rows.length,note:'Invalid rows are not committed automatically.'})}catch(e){next(e)}});

app.get('/api/v1/admin/system',requireAuth,requirePermission('system.read'),async(req,res,next)=>{try{const m=await query('SELECT version,applied_at FROM schema_migrations ORDER BY version DESC LIMIT 1'),flags=await query('SELECT code,enabled,environment FROM feature_flags ORDER BY code'),ints=await query('SELECT code,status FROM integration_providers ORDER BY code'),sv=await getStateVersion();res.json({application:'Kooner Fleet Management System',build:process.env.RENDER_GIT_COMMIT||process.env.APP_VERSION||'development',environment:process.env.APP_ENV||'test',database:'PostgreSQL',migration:m.rows[0]||null,stateVersion:sv,serverTime:new Date().toISOString(),featureFlags:flags.rows,deferredIntegrations:ints.rows,storageProvider:process.env.OBJECT_STORAGE_PROVIDER||'Not Connected',backupStatus:process.env.BACKUP_STATUS||'Production backup/restore test not yet verified'})}catch(e){next(e)}});

app.use('/server',(req,res)=>res.status(404).end());app.get('/package.json',(req,res)=>res.status(404).end());
const root=path.resolve(__dirname,'..');app.use(express.static(root,{index:false,dotfiles:'deny',etag:true,maxAge:'5m'}));
app.get('/',(req,res)=>res.sendFile(path.join(root,'index.html')));

app.use((req,res)=>res.status(404).json({error:'NOT_FOUND',message:'Resource not found',requestId:req.id}));
app.use((err,req,res,next)=>{console.error(JSON.stringify({level:'error',event:'request_error',requestId:req.id,code:err.code||null,message:err.message,stack:process.env.APP_ENV==='development'?err.stack:undefined}));const status=err.status||500,code=err.code||'SERVER_ERROR',msg=status>=500?'Unexpected server error':err.message;res.status(status).json({error:code,message:msg,requestId:req.id,...(err.serverVersion?{serverVersion:err.serverVersion}:{})})});

module.exports=app;
