'use strict';
const fs=require('fs');
const path=require('path');
const {query,tx}=require('./db');
function assert(ok,msg){if(!ok)throw new Error(msg)}
function read(name){return fs.readFileSync(path.join(__dirname,'..',name),'utf8')}
function ref(){return `WO-DCR121-${Date.now()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`}
async function cleanup(f){if(!f)return;const entities=[f.wo,f.att];await query('DELETE FROM notification_events WHERE entity_ref=ANY($1::text[])',[entities]);await query('DELETE FROM audit_events WHERE entity_ref=ANY($1::text[])',[entities]);await query("DELETE FROM attendance_resource_assignments WHERE attendance_id IN (SELECT a.id FROM attendances a JOIN work_orders w ON w.id=a.work_order_id WHERE w.legacy_ref=$1)",[f.wo]);await query("DELETE FROM attendances WHERE work_order_id IN (SELECT id FROM work_orders WHERE legacy_ref=$1)",[f.wo]);await query('DELETE FROM work_orders WHERE legacy_ref=$1',[f.wo])}
async function fixture(base,tech){const wo=ref(),att=wo.replace('WO-','ATT-');await tx(async c=>{const w=await c.query(`INSERT INTO work_orders(legacy_ref,customer_id,contract_id,site_id,vehicle_id,work_type,priority,fault_description,status,financial_status,current_owner,next_action,data) VALUES($1,$2,$3,$4,$5,'Breakdown','Normal','DCR-121 authoritative journey persistence fixture','Planned','Not Started','Planning','Await Technician acceptance','{}'::jsonb) RETURNING id`,[wo,base.customer_id,base.contract_id,base.site_id,base.vehicle_id]);const a=await c.query(`INSERT INTO attendances(legacy_ref,work_order_id,attendance_type,status,planned_at,data) VALUES($1,$2,'Mobile Repair','Planned',now(),'{}'::jsonb) RETURNING id`,[att,w.rows[0].id]);await c.query('INSERT INTO attendance_resource_assignments(attendance_id,technician_id) VALUES($1,$2)',[a.rows[0].id,tech.id])});return{wo,att}}
async function primarySnapshot(){const w=(await query("SELECT status,financial_status,current_owner,next_action,version,updated_at,data FROM work_orders WHERE legacy_ref='WO-10046'")).rows[0];const a=(await query("SELECT legacy_ref,status,arrived_at,departed_at,outcome,version,updated_at,data FROM attendances WHERE work_order_id=(SELECT id FROM work_orders WHERE legacy_ref='WO-10046') ORDER BY legacy_ref")).rows;return{w,a}}
function same(a,b){return JSON.stringify(a)===JSON.stringify(b)}
async function promote(note){return tx(async c=>{const r=await c.query("SELECT id,status FROM dcr_items WHERE dcr_ref='DCR-121' FOR UPDATE");assert(r.rowCount===1,'DCR-121 missing');const d=r.rows[0],target='Ready to Test';await c.query(`UPDATE dcr_items SET status=$2,resolution=$3,retest_result=$4,deferred=false,updated_at=now() WHERE id=$1`,[d.id,target,'DCR-121 corrected the Technician guided journey to use explicit authenticated Stage 6 server actions. Browser state no longer advances before server confirmation. Successful actions remain on the same Work Order / Attendance screen and use server-returned authoritative state. Accept, En Route, On Site, Registration, Safety and Start Work persistence are covered by deployed regression; Finish / Resolve continues through the existing explicit Smart Close server route.','Automated deployed DCR-121 acceptance PASS. Jon manual retest is required on WO-10046 / AB26 CDE before DCR-120 or DCR-117 can resume.']);if(d.status!==target)await c.query('INSERT INTO dcr_history(dcr_id,from_status,to_status,note,changed_by) VALUES($1,$2,$3,$4,$5)',[d.id,d.status,target,note,'Stage 6 DCR-121 automated acceptance']);const d117=(await c.query("SELECT status FROM dcr_items WHERE dcr_ref='DCR-117'")).rows[0],d120=(await c.query("SELECT status FROM dcr_items WHERE dcr_ref='DCR-120'")).rows[0],d119=(await c.query("SELECT status FROM dcr_items WHERE dcr_ref='DCR-119'")).rows[0];assert(d117?.status==='Ready to Test – blocked by Technician journey correction','DCR-117 blocker state changed unexpectedly');assert(d120?.status==='Ready to Test – Manual Retest Failed / blocked by DCR-121','DCR-120 manual FAIL/block state changed unexpectedly');assert(d119?.status==='Agreed – Awaiting Build','DCR-119 must remain unbuilt');return{dcr121:target,dcr117:d117.status,dcr120:d120.status,dcr119:d119.status}})}
async function runDcr121(port,core,final,evidence,dcr117,dcr118,dcr120){
 if((process.env.APP_ENV||'test')!=='stage6-test')return{skipped:true};
 const password=process.env.TEST_USER_PASSWORD;if(!password)throw new Error('TEST_USER_PASSWORD required');
 const baseUrl=`http://127.0.0.1:${port}`,results=[];let f=null;
 const check=(name,ok,detail='')=>{assert(ok,`${name}: ${detail||'failed'}`);results.push({name,ok:true,detail})};
 async function call(pathname,{method='GET',session,body}={}){const headers={'x-kooner-interface':'Technician Mobile'};if(session?.cookie)headers.cookie=session.cookie;if(session?.csrf&&!['GET','HEAD'].includes(method))headers['x-csrf-token']=session.csrf;if(body!==undefined){headers['content-type']='application/json';body=JSON.stringify(body)}const r=await fetch(baseUrl+pathname,{method,headers,body}),text=await r.text();let data=text;try{data=text?JSON.parse(text):null}catch{}return{status:r.status,data,headers:r.headers}}
 async function login(){const r=await call('/api/v1/auth/login',{method:'POST',body:{email:'technician@kooner.test',password}});assert(r.status===200,`Technician login failed: ${r.status}`);return{cookie:(r.headers.get('set-cookie')||'').split(';')[0],csrf:r.data.csrfToken}}
 async function boot(session){return call('/api/v1/bootstrap',{session})}
 function attendanceFromBootstrap(b){const w=b.data?.legacyState?.wos?.find(x=>x.id===f.wo);return{w,a:w?.att?.find(x=>x.id===f.att)}}
 const primaryBefore=await primarySnapshot();assert(primaryBefore.w,'WO-10046 missing');
 try{
  check('Core Stage 6 regression remains passed',core?.failed===0&&core?.total>=24,`${core?.passed||0}/${core?.total||0}`);
  check('Full Stage 6 regression remains passed',final?.failed===0&&final?.total>=42,`${final?.passed||0}/${final?.total||0}`);
  check('DCR-116 evidence regression remains passed',evidence?.failed===0&&evidence?.passed>=12,`${evidence?.passed||0}/${evidence?.passed||0}`);
  check('DCR-117 automated regression remains passed',dcr117?.failed===0&&dcr117?.passed>=15,`${dcr117?.passed||0}/${dcr117?.total||0}`);
  check('DCR-118 automated regression remains passed',dcr118?.failed===0&&dcr118?.passed>=18,`${dcr118?.passed||0}/${dcr118?.total||0}`);
  check('DCR-120 automated regression remains passed',dcr120?.failed===0&&dcr120?.passed>=25,`${dcr120?.passed||0}/${dcr120?.total||0}`);
  const d121=(await query("SELECT status,resolution FROM dcr_items WHERE dcr_ref='DCR-121'")).rows[0];check('DCR-121 was recorded before correction',d121?.status==='Blocking UAT Defect – Build Required',d121?.status);
  const d117db=(await query("SELECT status FROM dcr_items WHERE dcr_ref='DCR-117'")).rows[0],d120db=(await query("SELECT status FROM dcr_items WHERE dcr_ref='DCR-120'")).rows[0],d119db=(await query("SELECT status FROM dcr_items WHERE dcr_ref='DCR-119'")).rows[0];check('DCR-117 remains blocked by Technician journey correction',d117db?.status==='Ready to Test – blocked by Technician journey correction',d117db?.status);check('DCR-120 manual FAIL remains blocked by DCR-121',d120db?.status==='Ready to Test – Manual Retest Failed / blocked by DCR-121',d120db?.status);check('DCR-119 remains unbuilt',d119db?.status==='Agreed – Awaiting Build',d119db?.status);

  const guided=read('stage6-guided-journey.js'),client=read('stage6-client.js'),server=read('server/stage6-technician-journey-router.js');
  check('Guided journey calls explicit Stage 6 journey API',guided.includes('/api/v1/technician-journey/')&&!guided.includes('return acceptJob('),'server journey route');
  check('UI waits for server confirmation before advancing',guided.includes('const out=await journeyApi(wid,aid,action,payload);')&&guided.includes('applyServerConfirmation(wid,aid,out)'),'await server then apply');
  check('Successful UI flow explicitly stays on same job',guided.includes("window.mobileView='job';window.mobileJob={wid,aid}")&&guided.includes('renderJob(wid,aid)')&&!guided.includes("mobileGo('home')"),'same Work Order / Attendance render');
  check('Failed save cannot use browser-first journey success',guided.includes('Action not saved')&&guided.includes('Your job has not been advanced')&&!guided.includes('location.reload()'),'failure stays controlled');
  check('Server-confirmed state is adopted without compatibility re-write',client.includes('function acceptServerState(')&&guided.includes('KoonerStage6.acceptServerState(S,out.stateVersion)'),'no duplicate compatibility snapshot');
  check('Server route persists journey timestamps and audit',server.includes('acceptedAt')&&server.includes('enRouteAt')&&server.includes('onSiteAt')&&server.includes('workStartedAt')&&server.includes('Technician Journey – Accept Job'),'authoritative journey fields');

  const base=(await query("SELECT customer_id,contract_id,site_id,vehicle_id FROM work_orders WHERE legacy_ref='WO-10046'")).rows[0],tech=(await query("SELECT t.id,u.id user_id FROM technicians t JOIN users u ON u.id=t.user_id WHERE lower(u.email)='technician@kooner.test'")).rows[0];assert(base&&tech,'DCR-121 fixture base unavailable');f=await fixture(base,tech);
  let session=await login();
  let r=await call(`/api/v1/technician-journey/${encodeURIComponent(f.wo)}/${encodeURIComponent(f.att)}/action`,{method:'POST',session,body:{action:'accept'}});
  check('Technician Accept receives server success',r.status===200&&r.data.attendanceStatus==='Accepted'&&r.data.nextAction?.code==='en_route',JSON.stringify(r.data));
  const firstVersion=r.data.attendanceVersion;
  let q=(await query("SELECT status,data,version FROM attendances WHERE legacy_ref=$1",[f.att])).rows[0];check('Accept persisted authoritative Attendance and accepted timestamp',q?.status==='Accepted'&&!!q.data?.journey?.acceptedAt&&String(q.data?.journey?.acceptedBy)===String(tech.user_id),JSON.stringify(q));
  q=(await query("SELECT count(*)::int n,min(user_id::text) user_id FROM audit_events WHERE entity_type='Attendance' AND entity_ref=$1 AND action='Technician Journey – Accept Job'",[f.att])).rows[0];check('Accept audit/history exists with Technician user',q?.n===1&&String(q.user_id)===String(tech.user_id),JSON.stringify(q));
  let b=await boot(session),ba=attendanceFromBootstrap(b);check('Fresh bootstrap shows Attendance Accepted',b.status===200&&ba.a?.status==='Accepted'&&!!ba.a?.journey?.acceptedAt,JSON.stringify(ba.a));
  let logout=await call('/api/v1/auth/logout',{method:'POST',session,body:{}});assert(logout.status===200,'DCR-121 Technician logout failed');session=await login();b=await boot(session);ba=attendanceFromBootstrap(b);check('Relogin still shows Accepted',b.status===200&&ba.a?.status==='Accepted'&&!!ba.a?.journey?.acceptedAt,JSON.stringify(ba.a));
  r=await call(`/api/v1/technician-close/${encodeURIComponent(f.wo)}/${encodeURIComponent(f.att)}/journey`,{session});check('Server next action after Accept is Start Travel / En Route',r.status===200&&r.data.nextAction?.code==='en_route'&&/Start Travel/.test(r.data.nextAction?.label||''),JSON.stringify(r.data));
  r=await call(`/api/v1/technician-journey/${encodeURIComponent(f.wo)}/${encodeURIComponent(f.att)}/action`,{method:'POST',session,body:{action:'accept'}});check('Repeat Accept is idempotent',r.status===200&&r.data.replayed===true&&r.data.attendanceStatus==='Accepted'&&Number(r.data.attendanceVersion)===Number(firstVersion),JSON.stringify(r.data));q=(await query("SELECT count(*)::int n FROM audit_events WHERE entity_type='Attendance' AND entity_ref=$1 AND action='Technician Journey – Accept Job'",[f.att])).rows[0];check('Repeat Accept does not duplicate audit',q.n===1,String(q.n));

  const beforeFail=(await query("SELECT status,data,version FROM attendances WHERE legacy_ref=$1",[f.att])).rows[0];r=await call(`/api/v1/technician-journey/${encodeURIComponent(f.wo)}/${encodeURIComponent(f.att)}/action`,{method:'POST',session,body:{action:'start_work'}});check('Out-of-sequence server save is rejected',r.status===422&&r.data.error==='OUT_OF_SEQUENCE',JSON.stringify(r.data));const afterFail=(await query("SELECT status,data,version FROM attendances WHERE legacy_ref=$1",[f.att])).rows[0];check('Rejected save does not advance authoritative Attendance',same(beforeFail,afterFail),JSON.stringify(afterFail));

  r=await call(`/api/v1/technician-journey/${encodeURIComponent(f.wo)}/${encodeURIComponent(f.att)}/action`,{method:'POST',session,body:{action:'en_route'}});check('En Route persists server-confirmed status/timestamp',r.status===200&&r.data.attendanceStatus==='En Route'&&!!r.data.journey?.enRouteAt&&r.data.nextAction?.code==='on_site',JSON.stringify(r.data));b=await boot(session);ba=attendanceFromBootstrap(b);check('Fresh bootstrap shows En Route',ba.a?.status==='En Route'&&!!ba.a?.journey?.enRouteAt,JSON.stringify(ba.a));
  r=await call(`/api/v1/technician-journey/${encodeURIComponent(f.wo)}/${encodeURIComponent(f.att)}/action`,{method:'POST',session,body:{action:'on_site'}});check('On Site persists server-confirmed status/timestamp',r.status===200&&r.data.attendanceStatus==='On Site'&&!!r.data.journey?.onSiteAt&&r.data.nextAction?.code==='registration',JSON.stringify(r.data));b=await boot(session);ba=attendanceFromBootstrap(b);check('Fresh bootstrap shows On Site and arrival time',ba.a?.status==='On Site'&&!!ba.a?.journey?.onSiteAt&&!!ba.a?.arr,JSON.stringify(ba.a));
  r=await call(`/api/v1/technician-journey/${encodeURIComponent(f.wo)}/${encodeURIComponent(f.att)}/action`,{method:'POST',session,body:{action:'registration',registration:'AB26 CDE'}});check('Registration confirmation persists before Safety',r.status===200&&r.data.vehicleConfirmation?.match===true&&r.data.nextAction?.code==='safety',JSON.stringify(r.data));
  r=await call(`/api/v1/technician-journey/${encodeURIComponent(f.wo)}/${encodeURIComponent(f.att)}/action`,{method:'POST',session,body:{action:'safety',safe:true,safeLoc:true,secured:true,ppe:true,traffic:true,height:true,ev:true,note:'DCR-121 controlled safe test'}});check('Safety confirmation persists before Start Work',r.status===200&&r.data.safety?.safe===true&&r.data.nextAction?.code==='start_work',JSON.stringify(r.data));
  r=await call(`/api/v1/technician-journey/${encodeURIComponent(f.wo)}/${encodeURIComponent(f.att)}/action`,{method:'POST',session,body:{action:'start_work'}});check('Start Work persists server-confirmed Working status/timestamp',r.status===200&&r.data.attendanceStatus==='In Progress'&&!!r.data.journey?.workStartedAt&&r.data.nextAction?.code==='finish_job',JSON.stringify(r.data));b=await boot(session);ba=attendanceFromBootstrap(b);check('Fresh bootstrap shows Working after Start Work',ba.a?.status==='In Progress'&&!!ba.a?.journey?.workStartedAt&&ba.a?.vehicleConfirmation?.match===true&&ba.a?.safety?.safe===true,JSON.stringify(ba.a));
  q=(await query("SELECT action,count(*)::int n FROM audit_events WHERE entity_type='Attendance' AND entity_ref=$1 AND action LIKE 'Technician Journey – %' GROUP BY action ORDER BY action",[f.att])).rows;const actions=new Map(q.map(x=>[x.action,x.n]));check('Journey audit covers Accept, Travel, On Site, Registration, Safety and Start Work',['Technician Journey – Accept Job','Technician Journey – Start Travel','Technician Journey – Arrived On Site','Technician Journey – Registration Confirmed','Technician Journey – Safety Check Passed','Technician Journey – Start Work'].every(x=>actions.get(x)===1),JSON.stringify(q));

  const primaryAfter=await primarySnapshot();check('WO-10046 / AB26 CDE was not changed by DCR-121 automated testing',same(primaryBefore,primaryAfter),JSON.stringify(primaryAfter));
  const note=`DCR-121 deployed acceptance PASS (${results.length} checks). Live-root-cause correction now uses explicit server-confirmed Technician journey actions, independent bootstrap/relogin persistence, idempotent repeat Accept, failed-save non-advancement, and persisted En Route / On Site / Start Work timestamps. WO-10046 / AB26 CDE was not altered.`;
  const statuses=await promote(note);const result={passed:results.length,failed:0,total:results.length,dcr:'DCR-121',dcrStatus:statuses.dcr121,dcr117Status:statuses.dcr117,dcr120Status:statuses.dcr120,dcr119Status:statuses.dcr119,primaryManualWorkOrder:'WO-10046',registration:'AB26 CDE',results,note};console.log(JSON.stringify({level:'info',event:'stage6_dcr121_acceptance_complete',...result}));return result
 }finally{await cleanup(f)}
}
module.exports={runDcr121};
