'use strict';
const {tx,pool}=require('./db');
const {hashPassword}=require('./security');

const stage6Dcr=[
['DCR-089','Platform','Shared Backend/API Foundation','Ready to Test'],['DCR-090','Database','PostgreSQL Database & Schema Migrations','Ready to Test'],['DCR-091','Database','Prototype Data Migration / Seed','Ready to Test'],['DCR-092','Platform','Remove localStorage as Authoritative System of Record','Ready to Test'],['DCR-093','Security','Backend Authentication & Session Management','Ready to Test'],['DCR-094','Security','MFA Foundation','Ready to Test'],['DCR-095','Security','Server-Side Roles / Permissions','Ready to Test'],['DCR-096','Security','Customer/Site Tenant Isolation','Ready to Test'],['DCR-097','Platform','Server-Side Audit','Ready to Test'],['DCR-098','Data Integrity','Optimistic Concurrency / Record Versioning','Ready to Test'],['DCR-099','Data Integrity','API Idempotency','Ready to Test'],['DCR-100','Technician Mobile','Technician Offline Sync Backend','Ready to Test'],['DCR-101','Documents','Secure Document / Media Architecture','Ready to Test'],['DCR-102','Commercial','Pricing Engine Backend Authority','Ready to Test'],['DCR-103','Billing','Billing Backend Authority','Ready to Test'],['DCR-104','Commercial','Fixed Maintenance Backend Authority','Ready to Test'],['DCR-105','Platform','Backend Search / Filtering / Pagination','Ready to Test'],['DCR-106','Platform','Environment / Secrets Configuration','Ready to Test'],['DCR-107','Platform','Logging / Health / Observability','Ready to Test'],['DCR-108','Platform','Backup / Recovery Foundation','Agreed / Deferred Production Dependency'],['DCR-109','Compliance','GDPR Retention / Archive Foundation','Ready to Test'],['DCR-110','Platform','Bulk Import / Export Foundation','Ready to Test'],['DCR-111','Platform','Notification Event / Background Job Foundation','Ready to Test'],['DCR-112','Integrations','Integration Hub Server Foundation','Ready to Test'],['DCR-113','Security','Automated Security / Permission Test Matrix','Ready to Test'],['DCR-114','Regression','Stage 1–5 Regression Testing','Ready to Test'],['DCR-115','Security','Production Security Testing Dependency','Agreed / Deferred Production Dependency']];

const permissionCodes=['admin.*','compat.read','compat.write','workorders.read','workorders.write','planning.write','vehicles.read','estimates.read','estimates.write','estimates.approve','billing.read','billing.write','documents.read','documents.write','sync.write','technician.mobile','customer.portal','portal.submit','portal.finance','portal.finance.all_sites','portal.users','portal.actions','search','audit.read','dcr.read','dcr.write','system.read','import.export'];
const rolePermissions={operations:['compat.read','compat.write','workorders.read','workorders.write','planning.write','vehicles.read','estimates.read','estimates.write','billing.read','documents.read','documents.write','portal.actions','search','audit.read','dcr.read','system.read','import.export'],dispatcher:['compat.read','compat.write','workorders.read','workorders.write','planning.write','vehicles.read','estimates.read','documents.read','search'],technician:['compat.read','compat.write','workorders.read','vehicles.read','documents.read','sync.write','technician.mobile'],billing:['compat.read','compat.write','workorders.read','vehicles.read','estimates.read','billing.read','billing.write','documents.read','search','audit.read'],administrator:['admin.*'],customer_administrator:['compat.read','compat.write','customer.portal','portal.submit','workorders.read','vehicles.read','estimates.read','estimates.approve','documents.read','portal.finance','portal.finance.all_sites','portal.users'],site_manager:['compat.read','compat.write','customer.portal','portal.submit','workorders.read','vehicles.read','estimates.read','documents.read'],customer_finance:['compat.read','customer.portal','workorders.read','vehicles.read','estimates.read','documents.read','portal.finance','portal.finance.all_sites'],read_only:['compat.read','customer.portal','workorders.read','vehicles.read','estimates.read','documents.read']};

async function seed(){
 const testPassword=process.env.TEST_USER_PASSWORD;if(!testPassword)throw new Error('TEST_USER_PASSWORD is required for Stage 6 test seed');
 const passwordHash=await hashPassword(testPassword);
 return tx(async c=>{
  for(const p of permissionCodes)await c.query('INSERT INTO permissions(code,description) VALUES($1,$2) ON CONFLICT(code) DO NOTHING',[p,p]);
  for(const role of Object.keys(rolePermissions)){const type=role.startsWith('customer_')||role==='site_manager'||role==='read_only'?'customer':'internal';await c.query('INSERT INTO roles(code,name,role_type) VALUES($1,$2,$3) ON CONFLICT(code) DO NOTHING',[role,role.replaceAll('_',' '),type]);for(const p of rolePermissions[role])await c.query('INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r,permissions p WHERE r.code=$1 AND p.code=$2 ON CONFLICT DO NOTHING',[role,p])}
  async function upsertCustomer(ref,name,account,data){return (await c.query('INSERT INTO customers(legacy_ref,name,account_code,data) VALUES($1,$2,$3,$4::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET name=EXCLUDED.name,data=EXCLUDED.data RETURNING id',[ref,name,account,JSON.stringify(data)])).rows[0].id}
  const c1=await upsertCustomer('C1','Test Transport Ltd','TEST-001',{id:'C1',name:'Test Transport Ltd',account:'TEST-001',sites:['S1','S2'],contract:'CT1',billing:'Monthly consolidated • 31st cut-off',sla:'4 hour breakdown attendance target',authority:'Approval required over £250',po:'PO required for chargeable non-contract work',notify:'Dispatch, ETA, Estimate, Completion, Invoice'});
  const c2=await upsertCustomer('C2','Demo Logistics UK Ltd','TEST-002',{id:'C2',name:'Demo Logistics UK Ltd',account:'TEST-002',sites:['S3'],contract:'CT2',billing:'Per Work Order',sla:'Next business day planned work',authority:'Approval required over £500'});
  async function upsertSite(ref,cid,name,addr,pc,data){return (await c.query('INSERT INTO sites(legacy_ref,customer_id,name,address,postcode,data) VALUES($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET data=EXCLUDED.data RETURNING id',[ref,cid,name,addr,pc,JSON.stringify(data)])).rows[0].id}
  const s1=await upsertSite('S1',c1,'Birmingham Depot','100 Test Road, Birmingham','B24 9QG',{id:'S1',c:'C1',name:'Birmingham Depot',pc:'B24 9QG',addr:'100 Test Road, Birmingham',hours:'06:00–22:00',access:'Call gatehouse on arrival',keys:'Key cabinet — authorised access',park:'Workshop apron',ppe:'Hi-vis, safety boots',rams:'Site induction required',welfare:'Rest room',parts:'Workshop stores'});
  const s2=await upsertSite('S2',c1,'Bristol Depot','20 Example Way, Bristol','BS11 9FG',{id:'S2',c:'C1',name:'Bristol Depot',pc:'BS11 9FG',addr:'20 Example Way, Bristol',hours:'05:30–21:00',access:'Security barrier — quote WO',keys:'Key safe',park:'Rear service area',ppe:'Hi-vis, safety boots',rams:'RAMS on request',welfare:'Canteen',parts:'Reception marked Fleet'});
  const s3=await upsertSite('S3',c2,'Coventry Hub','5 Demo Park, Coventry','CV2 2TA',{id:'S3',c:'C2',name:'Coventry Hub',pc:'CV2 2TA',addr:'5 Demo Park, Coventry',hours:'24h',access:'Transport office check-in',keys:'Transport office',park:'Bay 12–18',ppe:'Hi-vis'});
  async function upsertContract(ref,cid,name,type,from,to,data){return (await c.query('INSERT INTO contracts(legacy_ref,customer_id,name,contract_type,effective_from,effective_to,data) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET data=EXCLUDED.data RETURNING id',[ref,cid,name,type,from,to,JSON.stringify(data)])).rows[0].id}
  const ct1=await upsertContract('CT1',c1,'Test Transport Fleet Maintenance','Fixed Maintenance + Breakdown','2026-01-01','2026-12-31',{id:'CT1',c:'C1',name:'Test Transport Fleet Maintenance',type:'Fixed Maintenance + Breakdown',from:'2026-01-01',to:'2026-12-31',monthly:225,level:'Vehicle',rate:'v2 effective 01/07/2026',pricing:'Labour £80/hr • Parts +30% • Travel £0.85/mile • 3rd party +20%'});
  const ct2=await upsertContract('CT2',c2,'Demo Logistics Reactive','Reactive','2026-03-01','2027-02-28',{id:'CT2',c:'C2',name:'Demo Logistics Reactive',type:'Reactive',from:'2026-03-01',to:'2027-02-28',monthly:0,level:'N/A',rate:'v1',pricing:'Labour £85/hr • Parts +25% • Travel £0.90/mile'});
  const vehicleDefs=[['V1',c1,s1,'AB26 CDE','TESTVIN000000001','TT-101','Ford','Transit','3.5t Van',28140,'VOR',true,'Due Soon','2026-10-15',30000],['V2',c1,s2,'XY25 ABC','TESTVIN000000002','TT-205','Peugeot','Partner','Van',44110,'In Service',false,'Overdue','2026-09-20',44000],['V3',c1,s1,'PN24 XYZ','TESTVIN000000003','TT-303','Mercedes-Benz','Sprinter','3.5t Van',61200,'In Service',false,'Not Due','2027-02-01',70000],['V4',c2,s3,'DE25 MOO','TESTVIN000000004','DL-44','Iveco','Daily','Van',33290,'In Service',false,'Due','2026-10-04',33500]];
  const vehicleIds={};for(const v of vehicleDefs){const data={id:v[0],reg:v[3],c:v[1]===c1?'C1':'C2',s:v[2]===s1?'S1':v[2]===s2?'S2':'S3',vin:v[4],unit:v[5],make:v[6],model:v[7],type:v[8],miles:v[9],status:v[10],maint:v[12],nextD:v[13],nextM:v[14]};const r=await c.query('INSERT INTO vehicles(legacy_ref,customer_id,current_site_id,registration,vin,unit_number,make,model,vehicle_type,current_mileage,status,vor,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET current_site_id=EXCLUDED.current_site_id,data=EXCLUDED.data RETURNING id',[...v.slice(0,12),JSON.stringify(data)]);vehicleIds[v[0]]=r.rows[0].id;await c.query('INSERT INTO vehicle_site_assignments(vehicle_id,site_id,effective_from,current,reason) SELECT $1,$2,$3,true,$4 WHERE NOT EXISTS(SELECT 1 FROM vehicle_site_assignments WHERE vehicle_id=$1 AND current=true)',[r.rows[0].id,v[2],'2026-01-01','Stage 6 seed'])}
  async function addUser(email,name,type,role,customerId=null,siteIds=[],legacy=null){const u=(await c.query('INSERT INTO users(legacy_ref,email,display_name,password_hash,active,user_type,customer_id) VALUES($1,$2,$3,$4,true,$5,$6) ON CONFLICT(email) DO UPDATE SET active=true,display_name=EXCLUDED.display_name RETURNING id',[legacy,email,name,passwordHash,type,customerId])).rows[0].id;await c.query('INSERT INTO user_roles(user_id,role_id) SELECT $1,id FROM roles WHERE code=$2 ON CONFLICT DO NOTHING',[u,role]);for(const sid of siteIds)await c.query("INSERT INTO user_scopes(user_id,customer_id,site_id,scope_type) VALUES($1,$2,$3,'site') ON CONFLICT DO NOTHING",[u,customerId,sid]);return u}
  const ops=await addUser('operations@kooner.test','Operations Test User','internal','operations',null,[],'U-OPS');await addUser('dispatcher@kooner.test','Dispatcher Test User','internal','dispatcher',null,[],'U-DISPATCH');const techUser=await addUser('technician@kooner.test','Technician Test User','internal','technician',null,[],'U-TECH');await addUser('billing@kooner.test','Billing Test User','internal','billing',null,[],'U-BILL');await addUser('admin@kooner.test','Administrator Test User','internal','administrator',null,[],'U-ADMIN');await addUser('customer.admin@testtransport.test','Test Transport Customer Administrator','customer','customer_administrator',c1,[s1,s2],'CU1');await addUser('birmingham.manager@testtransport.test','Test Transport Birmingham Site Manager','customer','site_manager',c1,[s1],'CU2');await addUser('finance@testtransport.test','Test Transport Finance','customer','customer_finance',c1,[s1,s2],'CU4');await addUser('customer.admin@demologistics.test','Demo Logistics Customer Administrator','customer','customer_administrator',c2,[s3],'CU5');
  const techDefs=[['T1',techUser,'Field Technician A','Mobile Technician','West Midlands','Available','KV26 TST','Field Technician'],['T2',null,'Field Technician B','Mobile Technician','Bristol','Available','KV26 DEM','Field Technician'],['T3',null,'Workshop Technician','Workshop Technician','Birmingham','Assigned',null,'Workshop Technician'],['T4',null,'Workshop Manager','Workshop Manager','Birmingham','Available',null,'Workshop Manager']];const techIds={};for(const t of techDefs){const data={id:t[0],name:t[2],role:t[3],base:t[4],status:t[5],van:t[6]||'—',group:t[7]};const r=await c.query('INSERT INTO technicians(legacy_ref,user_id,display_name,role_name,base_region,status,assigned_van,benchmark_group,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET user_id=COALESCE(technicians.user_id,EXCLUDED.user_id),data=EXCLUDED.data RETURNING id',[...t,JSON.stringify(data)]);techIds[t[0]]=r.rows[0].id}
  await c.query("INSERT INTO technician_cost_rate_history(technician_id,effective_from,hourly_cost) SELECT $1,'2026-01-01',24.50 WHERE NOT EXISTS(SELECT 1 FROM technician_cost_rate_history WHERE technician_id=$1)",[techIds.T1]);
  async function pricing(ref,cid,ctid,name,version,effective,labour,parts,third,miles){const rid=(await c.query('INSERT INTO pricing_rules(legacy_ref,customer_id,contract_id,name,data) VALUES($1,$2,$3,$4,$5::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET data=EXCLUDED.data RETURNING id',[ref,cid,ctid,name,JSON.stringify({id:ref,version,effective,labour,partsMarkup:parts,thirdMarkup:third,mileage:miles,vat:20})])).rows[0].id;await c.query('INSERT INTO pricing_rule_versions(pricing_rule_id,version_no,effective_from,labour_rate,parts_markup_percent,third_party_markup_percent,mileage_rate,vat_percent,data) VALUES($1,$2,$3,$4,$5,$6,$7,20,$8::jsonb) ON CONFLICT(pricing_rule_id,version_no) DO NOTHING',[rid,version,effective,labour,parts,third,miles,JSON.stringify({source:'Approved Stage 3 rule'})]);return rid}
  await pricing('PR-CT1-V2',c1,ct1,'Test Transport Pricing',2,'2026-07-01',80,30,20,.85);await pricing('PR-CT2-V1',c2,ct2,'Demo Logistics Pricing',1,'2026-03-01',85,25,15,.90);
  const plan=(await c.query("INSERT INTO fixed_maintenance_plans(legacy_ref,customer_id,contract_id,name,coverage_level,pro_rata_rule,data) VALUES('FMP-C1-VEH',$1,$2,'Test Transport – Vehicle Maintenance Plan','Vehicle-specific','Daily pro-rata',$3::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET name=EXCLUDED.name RETURNING id",[c1,ct1,JSON.stringify({name:'Test Transport – Vehicle Maintenance Plan'})])).rows[0].id;await c.query("INSERT INTO effective_rate_versions(plan_id,version_no,effective_from,monthly_rate,data) VALUES($1,1,'2026-01-01',225,$2::jsonb) ON CONFLICT(plan_id,version_no) DO NOTHING",[plan,JSON.stringify({regression:'October 2026 example'})]);
  for(const [ref,vid] of [['CA-V1',vehicleIds.V1],['CA-V3',vehicleIds.V3]])await c.query("INSERT INTO coverage_assignments(legacy_ref,plan_id,vehicle_id,effective_from,active,data) VALUES($1,$2,$3,'2026-01-01',true,'{}') ON CONFLICT(legacy_ref) DO NOTHING",[ref,plan,vid]);
  const woDefs=[['WO-10041',c1,ct1,s1,vehicleIds.V1,'Breakdown','Urgent','Brake warning light and low braking performance','Awaiting Parts','Not Started','Parts','Source rear caliper','PO-TEST-4101',true],['WO-10042',c1,ct1,s2,vehicleIds.V2,'Repair','Normal','Noise from front suspension','Awaiting Approval','Not Started','Customer','Approve Estimate v1','PO-TEST-4102',false],['WO-10043',c1,ct1,s1,vehicleIds.V3,'Planned Maintenance','Planned','Annual service due','Dispatched','Not Started','Planning','Technician attend planned service','CONTRACT',false],['WO-10044',c2,ct2,s3,vehicleIds.V4,'Repair','Normal','Replace failed side marker lamp','Operationally Complete','Billing Review','Billing','Commercial review','PO-5551',false],['WO-10045',c2,ct2,s3,vehicleIds.V4,'Repair','Normal','Number plate lamp inoperative','Dispatched','Not Started','Technician','Attend and repair number plate lamp','PO-MOB-0045',false],['WO-10038',c1,ct1,s1,vehicleIds.V3,'Repair','Normal','Previous tyre repair','Operationally Complete','Invoiced','Finance','None','PO-OLD',false]];const woIds={};for(const w of woDefs){const r=await c.query('INSERT INTO work_orders(legacy_ref,customer_id,contract_id,site_id,vehicle_id,work_type,priority,fault_description,status,financial_status,current_owner,next_action,customer_reference,vor,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET status=work_orders.status RETURNING id',[...w,JSON.stringify({id:w[0],cat:w[5],pri:w[6],fault:w[7],status:w[8],fin:w[9],owner:w[10],next:w[11],po:w[12],vor:w[13]})]);woIds[w[0]]=r.rows[0].id}
  async function attendance(ref,wo,type,status,tech,plan){const a=(await c.query('INSERT INTO attendances(legacy_ref,work_order_id,attendance_type,status,planned_at,data) VALUES($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET status=attendances.status RETURNING id',[ref,woIds[wo],type,status,plan,JSON.stringify({id:ref,type,status,tech,plan})])).rows[0].id;for(const t of tech)await c.query('INSERT INTO attendance_resource_assignments(attendance_id,technician_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[a,techIds[t]]);return a}
  await attendance('MOB-A41','WO-10041','Diagnosis','Dispatched',['T1'],'2026-10-06T09:00:00Z');await attendance('A3','WO-10043','Planned Maintenance','Dispatched',['T3'],'2026-10-06T08:00:00Z');await attendance('MOB-A45','WO-10045','Repair','Dispatched',['T1'],'2026-10-06T13:00:00Z');
  async function task(ref,wo,desc,type,status,srt){await c.query('INSERT INTO tasks(legacy_ref,work_order_id,description,task_type,status,required,srt_expected_hours,actual_hours,data) VALUES($1,$2,$3,$4,$5,true,$6,0,$7::jsonb) ON CONFLICT(legacy_ref) DO NOTHING',[ref,woIds[wo],desc,type,status,srt,JSON.stringify({id:ref,desc,type,status,srt,actual:0,required:true})])}
  await task('MOB-TK41','WO-10041','Confirm brake fault and rear caliper condition','Diagnosis','Not Started',.5);await task('TK2','WO-10041','Replace rear brake caliper','Repair','Awaiting Parts',1.4);await task('TK4','WO-10042','Replace N/S/F drop link','Repair','Awaiting Approval',.8);await task('TK5','WO-10043','Carry out annual service','Service','Not Started',1.5);await task('MOB-TK45','WO-10045','Replace number plate lamp','Repair','Not Started',.4);
  const est=(await c.query("INSERT INTO estimates(legacy_ref,work_order_id,status,current_version_no) VALUES('EST-2041',$1,'Sent',1) ON CONFLICT(legacy_ref) DO UPDATE SET status=estimates.status RETURNING id",[woIds['WO-10042']])).rows[0].id;await c.query("INSERT INTO estimate_versions(estimate_id,version_no,status,net,vat,gross,scope,data) VALUES($1,1,'Sent',105.60,21.12,126.72,'Replace N/S/F drop link',$2::jsonb) ON CONFLICT(estimate_id,version_no) DO NOTHING",[est,JSON.stringify({v:1,status:'Sent',hrs:.8,rate:80,parts:32,markup:30,vat:20,scope:'Replace N/S/F drop link'})]);
  async function invoice(ref,cid,site,type,date,net,vat,gross,wo){const inv=(await c.query('INSERT INTO invoices(legacy_ref,customer_id,explicit_site_id,invoice_type,status,issue_date,net,vat,gross,locked_at,data) VALUES($1,$2,$3,$4,\'Issued\',$5,$6,$7,$8,now(),$9::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET status=\'Issued\' RETURNING id',[ref,cid,site,type,date,net,vat,gross,JSON.stringify({id:ref,customer:cid===c1?'C1':'C2',site:site===s1?'S1':site===s2?'S2':site===s3?'S3':null,type,status:'Issued',date,net,vat,gross})])).rows[0].id;if(wo)await c.query('INSERT INTO invoice_lines(invoice_id,line_type,description,amount,work_order_id,site_id,source_ref,data) VALUES($1,\'Work Order\',$2,$3,$4,$5,$6,$7::jsonb)',[inv,`Work Order ${wo}`,net,woIds[wo],site,wo,JSON.stringify({type:'Work Order',workOrder:wo,reference:wo,amount:net})]);return inv}
  await invoice('INV-9001',c1,s1,'One Work Order','2026-08-31',56.60,11.32,67.92,'WO-10038');const invCon=await invoice('INV-9101',c1,null,'Monthly Consolidated','2026-09-30',405,81,486,null);await c.query("INSERT INTO invoice_lines(invoice_id,line_type,description,amount,source_ref,data) VALUES($1,'Fixed Maintenance','Vehicle Maintenance Plan — test monthly charge',225,'FMP-C1-VEH',$2::jsonb)",[invCon,JSON.stringify({type:'Fixed Maintenance',reference:'FMP-C1-VEH',amount:225})]);await invoice('INV-9301',c1,s1,'One Work Order','2026-10-03',120,24,144,'WO-10041');
  const docs=[['DOC-TEST-CUST-S1','Customer visible test document','Customer Visible',{}],['DOC-TEST-FIN-S1','Finance only test document','Customer Finance Only',{}],['DOC-TEST-SPEC-S1','Birmingham Site Manager scoped document','Specific Site/User Role',{allowedSites:['S1'],allowedRoles:['Site Manager']}],['DOC-TEST-INT-S1','Internal only test document','Internal Kooner Only',{}]];for(const d of docs)await c.query('INSERT INTO documents(legacy_ref,customer_id,site_id,vehicle_id,work_order_id,filename,visibility,storage_status,data) VALUES($1,$2,$3,$4,$5,$6,$7,\'Metadata Only\',$8::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET visibility=EXCLUDED.visibility,data=EXCLUDED.data',[d[0],c1,s1,vehicleIds.V1,woIds['WO-10041'],d[1],d[2],JSON.stringify({id:d[0],customer:'C1',site:'S1',vehicle:'V1',workOrder:'WO-10041',name:d[1],visibility:d[2],...d[3]})]);
  for(const p of ['DVLA','DVSA','Telematics','Accounting','Parts Suppliers','Customer APIs','Fuel Data','Maps','M365/Email'])await c.query("INSERT INTO integration_providers(code,name,status,enabled) VALUES($1,$2,'Future Integration – Not Connected',false) ON CONFLICT(code) DO NOTHING",[p.toUpperCase().replace(/[^A-Z0-9]+/g,'_'),p]);
  for(const cat of ['customer_data','employee_user_data','audit','documents_media'])await c.query("INSERT INTO retention_policies(category,verified,status) VALUES($1,false,'Legal / Compliance Verification Required') ON CONFLICT(category) DO NOTHING",[cat]);
  for(let i=1;i<=88;i++){const ref='DCR-'+String(i).padStart(3,'0');await c.query("INSERT INTO dcr_items(dcr_ref,area,description,item_type,priority,status,resolution,retest_result,deferred) VALUES($1,'Legacy Stage 1–5',$2,'Migrated','P2','Agreed','Preserved from approved Stage 1–5 prototype','Migrated to Stage 6 backend',false) ON CONFLICT(dcr_ref) DO NOTHING",[ref,`Approved Stage 1–5 ${ref}`]);const d=(await c.query('SELECT id FROM dcr_items WHERE dcr_ref=$1',[ref])).rows[0];await c.query("INSERT INTO dcr_history(dcr_id,to_status,note,changed_by) SELECT $1,'Agreed','Migrated into Stage 6 shared backend storage','System Build' WHERE NOT EXISTS(SELECT 1 FROM dcr_history WHERE dcr_id=$1)",[d.id])}
  for(const [ref,area,desc,status] of stage6Dcr){const deferred=status.startsWith('Agreed / Deferred');const resolution=deferred?'Production dependency intentionally deferred and visibly retained.':'Implemented in Stage 6 foundation; pending user retest.';await c.query('INSERT INTO dcr_items(dcr_ref,area,description,item_type,priority,status,resolution,retest_result,deferred) VALUES($1,$2,$3,\'Stage 6\',\'P1\',$4,$5,$6,$7) ON CONFLICT(dcr_ref) DO UPDATE SET status=EXCLUDED.status,resolution=EXCLUDED.resolution,deferred=EXCLUDED.deferred',[ref,area,desc,status,resolution,deferred?'N/A until dependency complete':'Pending Stage 6 retest',deferred]);const d=(await c.query('SELECT id FROM dcr_items WHERE dcr_ref=$1',[ref])).rows[0];await c.query('INSERT INTO dcr_history(dcr_id,to_status,note,changed_by) SELECT $1,$2,$3,\'System Build\' WHERE NOT EXISTS(SELECT 1 FROM dcr_history WHERE dcr_id=$1)',[d.id,status,resolution])}
  await c.query("INSERT INTO feature_flags(code,enabled,environment,data) VALUES('stage6_api_mode',true,'test','{}'),('customer_portal',true,'test','{}'),('dvla_integration',false,'test','{\"status\":\"Future Integration – Not Connected\"}'),('dvsa_integration',false,'test','{\"status\":\"Future Integration – Not Connected\"}') ON CONFLICT(code) DO NOTHING");
  await c.query("INSERT INTO system_meta(key,value,updated_at) VALUES('seed_version','{\"version\":1,\"name\":\"stage6-regression-seed\"}',now()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()");
  await c.query("INSERT INTO audit_events(entity_type,action,user_id,user_role,source,reason,correlation_id) VALUES('System','Stage 6 seed verified',$1,'operations','System','Idempotent development/test seed complete',gen_random_uuid())",[ops]);
  return {seeded:true};
 })
}
if(require.main===module)seed().then(x=>{console.log(JSON.stringify({level:'info',event:'seed_complete',...x}));return pool.end()}).catch(e=>{console.error(e);process.exit(1)});
module.exports={seed,stage6Dcr};
