'use strict';
const express=require('express');
const cookieParser=require('cookie-parser');
const crypto=require('crypto');
const inner=require('./index');
const {query,tx,getStateVersion,bumpStateVersion}=require('./db');
const {authMiddleware,requireAuth,csrfRequired,isInternal,canAccessSite}=require('./auth');
const {buildLegacyState}=require('./state');
const B=require('./business');

const app=express();
app.set('trust proxy',1);
app.use((req,res,next)=>{req.id=req.id||crypto.randomUUID();next()});
app.use(express.json({limit:'2mb'}));
app.use(express.urlencoded({extended:false,limit:'256kb'}));
app.use(cookieParser());
app.use(authMiddleware);

function fail(status,code,message){throw Object.assign(new Error(message),{status,code})}
function has(user,p){return !!user&&(user.permissions||[]).some(x=>x==='admin.*'||x===p)}
function ref(v){return String(v||'').trim()}
function same(a,b){return JSON.stringify(a??null)===JSON.stringify(b??null)}
function cleanText(v,max=5000){return String(v??'').trim().slice(0,max)}
function safeDate(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.valueOf())?null:d.toISOString()}
function roleLabel(code){return({customer_administrator:'Customer Administrator',site_manager:'Site Manager',fleet_manager:'Fleet Manager',authoriser:'Authoriser',customer_finance:'Finance',read_only:'Read Only'})[code]||String(code||'Customer User').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function frontendPermissions(perms,roles){const p=new Set(perms||[]),out=[];if(p.has('vehicles.read'))out.push('vehicles');if(p.has('workorders.read'))out.push('workorders');if(p.has('portal.submit'))out.push('submit','mileage','po','datachange');if(p.has('estimates.read'))out.push('estimates');if(p.has('estimates.approve'))out.push('approve');if(p.has('portal.finance'))out.push('billing','invoices');if(p.has('documents.read'))out.push('documents');if(p.has('portal.users'))out.push('users');if(p.has('customer.portal'))out.push('notifications');return [...new Set(out)]}
async function siteRefsFor(user,client=query){const q=typeof client==='function'?client:(t,p)=>client.query(t,p);const r=await q(`SELECT s.id,s.legacy_ref FROM user_scopes us JOIN sites s ON s.id=us.site_id WHERE us.user_id=$1 AND us.scope_type='site'`,[user.id]);return r.rows}
async function customerRefFor(user,client=query){const q=typeof client==='function'?client:(t,p)=>client.query(t,p);const r=await q('SELECT legacy_ref FROM customers WHERE id=$1',[user.customer_id]);return r.rows[0]?.legacy_ref||null}
async function customerPortalUsers(user){
 if(user.user_type!=='customer')return[];
 const allowAdmin=has(user,'portal.users');
 const r=await query(`SELECT u.id,u.legacy_ref,u.email,u.display_name,u.active,u.customer_id,
  COALESCE(array_agg(DISTINCT ro.code) FILTER(WHERE ro.code IS NOT NULL),'{}') roles,
  COALESCE(array_agg(DISTINCT p.code) FILTER(WHERE p.code IS NOT NULL),'{}') permissions
  FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles ro ON ro.id=ur.role_id
  LEFT JOIN role_permissions rp ON rp.role_id=ro.id LEFT JOIN permissions p ON p.id=rp.permission_id
  WHERE u.customer_id=$1 ${allowAdmin?'':'AND u.id=$2'} GROUP BY u.id ORDER BY u.display_name`,allowAdmin?[user.customer_id]:[user.customer_id,user.id]);
 const cRef=await customerRefFor(user),items=[];
 for(const u of r.rows){const sr=await query(`SELECT s.legacy_ref FROM user_scopes us JOIN sites s ON s.id=us.site_id WHERE us.user_id=$1 AND us.scope_type='site' ORDER BY s.name`,[u.id]);const role=u.roles[0]||'read_only',readOnly=role==='read_only'||role==='customer_finance';items.push({id:u.legacy_ref||String(u.id),customer:cRef,name:u.display_name,email:u.email,phone:'',role:roleLabel(role),sites:sr.rows.map(x=>x.legacy_ref),permissions:frontendPermissions(u.permissions,u.roles),finance:u.permissions.includes('portal.finance'),readOnly,status:u.active?'Active':'Inactive',stage6Authenticated:u.id===user.id})}
 return items
}

async function enrichBootstrap(user,payload){
 const s=payload.legacyState||{};
 // Vehicle history is relational and append-only in Stage 6.
 for(const v of (s.vehicles||[])){
  const vr=await query('SELECT id FROM vehicles WHERE legacy_ref=$1',[v.id]);if(!vr.rowCount)continue;const vid=vr.rows[0].id;
  const sa=await query(`SELECT vsa.id,s.legacy_ref site_ref,vsa.effective_from,vsa.effective_to,vsa.current,vsa.reason,u.display_name changed_by FROM vehicle_site_assignments vsa JOIN sites s ON s.id=vsa.site_id LEFT JOIN users u ON u.id=vsa.changed_by WHERE vsa.vehicle_id=$1 ORDER BY vsa.effective_from`,[vid]);
  v.siteAssignments=sa.rows.map(x=>({id:String(x.id),site:x.site_ref,from:x.effective_from,to:x.effective_to,current:x.current,reason:x.reason,by:x.changed_by||'System'}));
  const mh=await query(`SELECT m.id,m.mileage,m.source,m.captured_at,m.review_required,m.reason,u.display_name entered_by,w.legacy_ref wo_ref,a.legacy_ref att_ref FROM mileage_history m LEFT JOIN users u ON u.id=m.entered_by LEFT JOIN work_orders w ON w.id=m.work_order_id LEFT JOIN attendances a ON a.id=m.attendance_id WHERE m.vehicle_id=$1 ORDER BY m.captured_at`,[vid]);
  v.mileageRecords=mh.rows.map(x=>({id:String(x.id),mileage:Number(x.mileage),at:x.captured_at,source:x.source,enteredBy:x.entered_by||x.source,workOrder:x.wo_ref,attendance:x.att_ref,reviewRequired:x.review_required,reviewReason:x.reason||''}));
 }
 // Fixed-maintenance and SRT remain shared server data, reconstructed for approved Stage 3/4 screens.
 const customerRefs=new Set((s.customers||[]).map(x=>x.id));
 s.fixedMaintenancePlans=[];
 const plans=await query(`SELECT p.id,p.legacy_ref,c.legacy_ref customer_ref,ct.legacy_ref contract_ref,p.name,p.coverage_level,p.pro_rata_rule,p.active,p.data FROM fixed_maintenance_plans p JOIN customers c ON c.id=p.customer_id LEFT JOIN contracts ct ON ct.id=p.contract_id ORDER BY p.name`);
 for(const p of plans.rows){if(customerRefs.size&&!customerRefs.has(p.customer_ref))continue;const rr=await query('SELECT id,version_no,effective_from,effective_to,monthly_rate,data FROM effective_rate_versions WHERE plan_id=$1 ORDER BY effective_from',[p.id]);const ca=await query(`SELECT ca.id,ca.legacy_ref,v.legacy_ref vehicle_ref,ca.group_ref,ca.fleet_ref,ca.effective_from,ca.effective_to,ca.active,ca.data FROM coverage_assignments ca LEFT JOIN vehicles v ON v.id=ca.vehicle_id WHERE ca.plan_id=$1 ORDER BY ca.effective_from`,[p.id]);s.fixedMaintenancePlans.push({id:p.legacy_ref,customer:p.customer_ref,contract:p.contract_ref,name:p.name,scope:p.coverage_level,status:p.active?'Active':'Inactive',proRata:p.pro_rata_rule,rateVersions:rr.rows.map(x=>({id:String(x.id),version:'v'+x.version_no,from:String(x.effective_from).slice(0,10),to:x.effective_to?String(x.effective_to).slice(0,10):null,monthly:Number(x.monthly_rate)})),coverageAssignments:ca.rows.filter(x=>x.active).map(x=>({id:x.legacy_ref||String(x.id),vehicle:x.vehicle_ref||undefined,group:x.group_ref||undefined,fleet:x.fleet_ref||undefined,from:String(x.effective_from).slice(0,10),to:x.effective_to?String(x.effective_to).slice(0,10):null,...(x.data||{})}))})}
 const ops=await query(`SELECT ro.code,ro.name,ro.source,sv.version_no,sv.standard_hours,sv.source srt_source FROM repair_operations ro LEFT JOIN LATERAL(SELECT * FROM srt_versions x WHERE x.repair_operation_id=ro.id AND x.effective_from<=current_date AND (x.effective_to IS NULL OR x.effective_to>=current_date) ORDER BY x.effective_from DESC LIMIT 1) sv ON true WHERE ro.active=true ORDER BY ro.code`);
 s.srtOps=ops.rows.map(x=>({id:x.code,name:x.name,time:x.standard_hours==null?0:Number(x.standard_hours),source:x.srt_source||x.source||'Kooner configured SRT',version:x.version_no||1}));
 // Evidence, labour commercial reviews and customer communications are reconstructed from relational records.
 for(const w of (s.wos||[])){
  const wr=await query('SELECT id FROM work_orders WHERE legacy_ref=$1',[w.id]);if(!wr.rowCount)continue;const wid=wr.rows[0].id;
  const ev=await query(`SELECT e.legacy_ref,e.evidence_type,e.filename,e.visibility,e.storage_status,e.captured_at,a.legacy_ref att_ref,t.legacy_ref task_ref,u.display_name FROM evidence_metadata e LEFT JOIN attendances a ON a.id=e.attendance_id LEFT JOIN tasks t ON t.id=e.task_id LEFT JOIN users u ON u.id=e.captured_by WHERE e.work_order_id=$1 ORDER BY e.captured_at`,[wid]);w.evidence=ev.rows.map(x=>({id:x.legacy_ref,type:x.evidence_type,name:x.filename||x.evidence_type,visibility:x.visibility,storageStatus:x.storage_status,at:x.captured_at,attendance:x.att_ref,task:x.task_ref,by:x.display_name||'System'}));
  const cm=await query(`SELECT cm.legacy_ref,cm.source,cm.visibility,cm.message,cm.created_at,u.display_name sender FROM customer_messages cm LEFT JOIN users u ON u.id=cm.sender_user_id WHERE cm.work_order_id=$1 ORDER BY cm.created_at`,[wid]);w.communications=cm.rows.map(x=>({id:x.legacy_ref||String(x.created_at),source:x.source,visibility:x.visibility,audience:x.visibility==='Customer Visible'?'Customer':'Internal',message:x.message,at:x.created_at,sender:x.sender||x.source}));
  if(isInternal(user)&&!user.roles.includes('technician')){const lr=await query(`SELECT lr.*,t.legacy_ref tech_ref,a.legacy_ref att_ref,ta.legacy_ref task_ref,u.display_name reviewer,pr.legacy_ref pricing_ref,prv.version_no pricing_version,prv.labour_rate FROM technician_labour_reviews lr LEFT JOIN technicians t ON t.id=lr.technician_id LEFT JOIN attendances a ON a.id=lr.attendance_id LEFT JOIN tasks ta ON ta.id=lr.task_id LEFT JOIN users u ON u.id=lr.reviewer_user_id LEFT JOIN pricing_rule_versions prv ON prv.id=lr.pricing_rule_version_id LEFT JOIN pricing_rules pr ON pr.id=prv.pricing_rule_id WHERE lr.work_order_id=$1`,[wid]);w.labourReviews=lr.rows.map(x=>({id:String(x.id),timeEntryId:x.time_entry_id?String(x.time_entry_id):null,technician:x.tech_ref,attendance:x.att_ref,task:x.task_ref,activity:x.data?.activity||'Working',actualMinutes:x.actual_minutes,expectedMinutes:x.expected_minutes,srtHours:(x.expected_minutes||0)/60,srtLabel:x.data?.srtLabel||'',pricingRuleId:x.pricing_ref,pricingVersion:x.pricing_version,customerRate:Number(x.labour_rate||0),chargeabilityReviewRequired:!!x.data?.chargeabilityReviewRequired,reviewReason:x.data?.reviewReason||'',proposedBillableMinutes:x.proposed_billable_minutes,approvedBillableMinutes:x.approved_billable_minutes,reviewer:x.reviewer||'',reviewedAt:x.reviewed_at,overrideReason:x.override_reason||'',status:x.status}))}
 }
 if(user.user_type==='customer'){
  const us=await customerPortalUsers(user);s.portalUsers=us;s.portalSettings={selectedUser:user.legacy_ref||String(user.id),stage6Locked:true};
  const dc=await query(`SELECT d.*,c.legacy_ref c_ref FROM customer_data_change_requests d JOIN customers c ON c.id=d.customer_id WHERE d.customer_id=$1 AND d.submitted_by=$2 ORDER BY d.created_at`,[user.customer_id,user.id]);s.portalDataChangeRequests=dc.rows.map(x=>({id:x.legacy_ref,customer:x.c_ref,user:user.legacy_ref,recordType:x.record_type,recordId:x.record_ref,currentValue:x.current_value,requestedValue:x.requested_value,reason:x.reason,status:x.status,createdAt:x.created_at,operationsDecision:x.decision_reason||''}));
  const ur=await query('SELECT * FROM portal_user_requests WHERE customer_id=$1 AND requested_by=$2 ORDER BY created_at',[user.customer_id,user.id]);s.portalUserRequests=ur.rows.map(x=>({id:x.legacy_ref,customer:(s.customers||[])[0]?.id,requestedBy:user.legacy_ref,name:x.requested_name,email:x.requested_email,role:x.requested_role,sites:[],status:x.status,createdAt:x.created_at}));
 }
 if(user.roles.includes('technician')){
  const se=await query(`SELECT event_id,device_id,event_type,event_timestamp,device_capture_timestamp,server_received_timestamp,sync_status,resolution FROM sync_events WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100`,[user.id]);s.mobileSyncQueue=se.rows.map(x=>({id:x.event_id,device:x.device_id,tech:(s.techs||[])[0]?.id,type:x.event_type,eventTime:x.event_timestamp,deviceCaptureTime:x.device_capture_timestamp,serverSyncTime:x.server_received_timestamp,status:x.sync_status,resolution:x.resolution||null,applied:x.sync_status==='Accepted'}));
 }
 payload.legacyState=s;payload.stage6={authority:'PostgreSQL',mode:'Database/API Backed',authenticatedUser:user.legacy_ref||String(user.id),interfacePermissions:user.permissions};return payload
}

async function addPortalAction(c,req,{legacyRef,customerId,type,refType,refLegacy,summary,reason,priority='Normal',siteRef}){
 const id=legacyRef||`CPA-SRV-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`;
 const data={site:siteRef||null,user:req.user.legacy_ref,userName:req.user.display_name,source:'Customer Portal'};
 await c.query(`INSERT INTO portal_actions(legacy_ref,customer_id,action_type,ref_type,ref_legacy,summary,reason,priority,status,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'New',$9::jsonb) ON CONFLICT(legacy_ref) DO NOTHING`,[id,customerId,type,refType||null,refLegacy||null,summary,reason||null,priority,JSON.stringify(data)]);return id
}
async function authorisedMaps(c,user){
 const cr=await c.query('SELECT id,legacy_ref FROM customers WHERE id=$1',[user.customer_id]);if(!cr.rowCount)fail(403,'ACCESS_DENIED','ACCESS DENIED / NOT AUTHORISED');const customer=cr.rows[0];
 const sr=await c.query(`SELECT s.id,s.legacy_ref FROM user_scopes us JOIN sites s ON s.id=us.site_id WHERE us.user_id=$1 AND us.scope_type='site'`,[user.id]);const siteByRef=new Map(sr.rows.map(x=>[x.legacy_ref,x.id]));
 const vr=await c.query(`SELECT v.id,v.legacy_ref,v.current_site_id,v.current_mileage FROM vehicles v WHERE v.customer_id=$1`,[user.customer_id]);const vehicleByRef=new Map(vr.rows.filter(v=>[...siteByRef.values()].some(x=>String(x)===String(v.current_site_id))).map(x=>[x.legacy_ref,x]));
 const wr=await c.query('SELECT id,legacy_ref,site_id,vehicle_id,customer_reference,status,financial_status,current_owner,next_action FROM work_orders WHERE customer_id=$1',[user.customer_id]);const workByRef=new Map(wr.rows.filter(w=>[...siteByRef.values()].some(x=>String(x)===String(w.site_id))).map(x=>[x.legacy_ref,x]));
 return{customer,siteByRef,vehicleByRef,workByRef}
}
async function customerCommit(req){return tx(async c=>{
 const expected=Number(req.body.baseVersion),current=await getStateVersion(c);if(Number.isFinite(expected)&&expected!==current)fail(409,'CONFLICT','Server data changed. Refresh before retrying.');
 const incoming=req.body.state||{},m=await authorisedMaps(c,req.user);let changed=false;
 const requireSubmit=()=>{if(!has(req.user,'portal.submit'))fail(403,'ACCESS_DENIED','ACCESS DENIED / NOT AUTHORISED')};
 // New customer Work Requests: customer/site/vehicle are resolved again from server scope and status is server-controlled.
 for(const r of (incoming.portalRequests||[])){
  const rid=ref(r.id);if(!rid)continue;const ex=await c.query('SELECT 1 FROM portal_requests WHERE legacy_ref=$1',[rid]);if(ex.rowCount)continue;requireSubmit();if(ref(r.customer||r.c)!==m.customer.legacy_ref)fail(403,'ACCESS_DENIED','ACCESS DENIED / NOT AUTHORISED');const sid=m.siteByRef.get(ref(r.site||r.s)),v=m.vehicleByRef.get(ref(r.vehicle||r.v));if(!sid||!v||String(v.current_site_id)!==String(sid))fail(403,'ACCESS_DENIED','ACCESS DENIED / NOT AUTHORISED');const emergency=['VOR / Not Driveable','Roadside Breakdown','Unsafe / Safety Issue'].includes(r.vehicleStatus)||!!r.emergency;const desc=cleanText(r.fault||r.description,8000);if(!desc)fail(422,'VALIDATION','Fault / requirement is required');const data={location:cleanText(r.location,1000),caller:cleanText(r.caller,500),driver:cleanText(r.driver,500),siteContact:cleanText(r.siteContact,500),updateContact:cleanText(r.updateContact,500),authoriser:cleanText(r.authoriser,500),po:cleanText(r.po,500),timing:cleanText(r.timing,500),notes:cleanText(r.notes,8000),file:cleanText(r.file,500),duplicateMode:cleanText(r.duplicateMode,50),separateReason:cleanText(r.separateReason,2000),source:'Customer Portal'};await c.query(`INSERT INTO portal_requests(legacy_ref,customer_id,site_id,vehicle_id,submitted_by,request_type,vehicle_status,description,status,emergency,data,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'Awaiting Operations Triage',$9,$10::jsonb,COALESCE($11,now()))`,[rid,m.customer.id,sid,v.id,req.user.id,cleanText(r.requestType||r.type,200)||'Other',cleanText(r.vehicleStatus,200)||null,desc,emergency,JSON.stringify(data),safeDate(r.submittedAt||r.createdAt)]);const pa=(incoming.portalActions||[]).find(x=>x.refType==='Portal Request'&&x.refId===rid);await addPortalAction(c,req,{legacyRef:pa?.id,customerId:m.customer.id,type:emergency?'Portal emergency/VOR alert':'New Request awaiting triage',refType:'Portal Request',refLegacy:rid,summary:`${ref(r.registration)||v.legacy_ref} • ${desc}`,reason:cleanText(r.separateReason,2000),priority:emergency?'Urgent':'Normal',siteRef:ref(r.site||r.s)});await B.audit(c,req,'PortalRequest',null,rid,'Customer Portal request submitted',null,{status:'Awaiting Operations Triage',emergency},null);changed=true
 }
 // Customer messages are append-only and cannot directly dictate server Work Order status.
 for(const iw of (incoming.wos||[])){
  const sw=m.workByRef.get(ref(iw.id));if(!sw)continue;for(const cm of (iw.communications||[])){if(cm.source!=='Customer Portal')continue;const mid=ref(cm.id);if(!mid)continue;const ex=await c.query('SELECT 1 FROM customer_messages WHERE legacy_ref=$1',[mid]);if(ex.rowCount)continue;requireSubmit();const msg=cleanText(cm.message,10000);if(!msg)continue;await c.query(`INSERT INTO customer_messages(legacy_ref,work_order_id,sender_user_id,source,visibility,message,created_at,data) VALUES($1,$2,$3,'Customer Portal','Customer Visible',$4,COALESCE($5,now()),$6::jsonb)`,[mid,sw.id,req.user.id,msg,safeDate(cm.at),JSON.stringify({sender:req.user.display_name})]);await c.query("UPDATE work_orders SET current_owner='Operations',next_action='Respond to customer message',version=version+1,updated_at=now() WHERE id=$1",[sw.id]);const pa=(incoming.portalActions||[]).find(x=>x.refType==='Work Order'&&x.refId===iw.id&&x.reason===cm.message);await addPortalAction(c,req,{legacyRef:pa?.id,customerId:m.customer.id,type:'Customer question',refType:'Work Order',refLegacy:iw.id,summary:msg,reason:msg,siteRef:[...m.siteByRef].find(([,id])=>String(id)===String(sw.site_id))?.[0]});await B.audit(c,req,'WorkOrder',sw.id,iw.id,'Customer message received',null,{message:msg},null);changed=true}
  const newPo=cleanText(iw.po,500),oldPo=cleanText(sw.customer_reference,500);if(newPo!==oldPo){requireSubmit();await c.query('UPDATE work_orders SET customer_reference=$2,version=version+1,updated_at=now() WHERE id=$1',[sw.id,newPo||null]);await B.audit(c,req,'WorkOrder',sw.id,iw.id,'Customer PO/reference updated',{customerReference:oldPo},{customerReference:newPo},'Customer Portal update');await addPortalAction(c,req,{customerId:m.customer.id,type:'PO issue',refType:'Work Order',refLegacy:iw.id,summary:`PO/reference updated ${oldPo||'—'} → ${newPo||'—'}`,reason:'Customer Portal update'});changed=true}
  // Exact current Estimate version/state is revalidated at commit time.
  for(const ie of (iw.ests||[])){const er=await c.query(`SELECT e.id,e.current_version_no,e.status,ev.id version_id,ev.status version_status,ev.gross FROM estimates e JOIN estimate_versions ev ON ev.estimate_id=e.id AND ev.version_no=e.current_version_no WHERE e.legacy_ref=$1 AND e.work_order_id=$2 FOR UPDATE`,[ie.id,sw.id]);if(!er.rowCount)continue;const se=er.rows[0],iv=(ie.versions||[]).find(x=>Number(x.v)===Number(se.current_version_no));if(!iv||iv.status===se.version_status)continue;if(!['Approved','Declined'].includes(iv.status))continue;if(!has(req.user,'estimates.approve'))fail(403,'ACCESS_DENIED','ACCESS DENIED / NOT AUTHORISED');if(!['Sent','Viewed'].includes(se.version_status))fail(422,'BUSINESS_RULE',`Estimate is already ${se.version_status}`);await c.query('UPDATE estimate_versions SET status=$2 WHERE id=$1',[se.version_id,iv.status]);await c.query('UPDATE estimates SET status=$2,version=version+1,updated_at=now() WHERE id=$1',[se.id,iv.status]);await c.query(`INSERT INTO estimate_approval_history(estimate_version_id,decision,approver_user_id,approver_name,method,approved_amount,scope,evidence_reference,comments) VALUES($1,$2,$3,$4,'Customer Portal',$5,$6,$7,$8)`,[se.version_id,iv.status,req.user.id,req.user.display_name,se.gross,iv.scope||null,`Portal user ${req.user.legacy_ref||req.user.id}`,cleanText(iv.approvalHistory?.at(-1)?.comments,5000)]);if(iv.status==='Approved')await c.query("UPDATE work_orders SET status='Planned',current_owner='Planning',next_action='Plan approved repair',version=version+1,updated_at=now() WHERE id=$1",[sw.id]);else await c.query("UPDATE work_orders SET status='Awaiting Approval',current_owner='Operations',next_action='Review customer-declined Estimate',version=version+1,updated_at=now() WHERE id=$1",[sw.id]);await B.audit(c,req,'Estimate',se.id,ie.id,`Estimate ${iv.status}`,{status:se.version_status,version:se.current_version_no},{status:iv.status,version:se.current_version_no},cleanText(iv.approvalHistory?.at(-1)?.comments,5000));await addPortalAction(c,req,{customerId:m.customer.id,type:'Estimate response',refType:'Work Order',refLegacy:iw.id,summary:`${iv.status} Estimate v${se.current_version_no}`,priority:iv.status==='Declined'?'High':'Normal'});changed=true}
 }
 // Customer mileage is append-only. Lower readings never reduce trusted current mileage.
 for(const iv of (incoming.vehicles||[])){const sv=m.vehicleByRef.get(ref(iv.id));if(!sv)continue;for(const mr of (iv.mileageRecords||[])){const legacy=ref(mr.id);if(!legacy||!/^MR-(PORT|CUST)/i.test(legacy))continue;const exists=await c.query("SELECT 1 FROM mileage_history WHERE data->>'legacyRef'=$1",[legacy]);if(exists.rowCount)continue;requireSubmit();const mileage=Number(mr.mileage);if(!Number.isFinite(mileage)||mileage<0)fail(422,'VALIDATION','Mileage must be a valid non-negative number');const lower=mileage<Number(sv.current_mileage||0),reason=cleanText(mr.notes||mr.reviewReason,2000);if(lower&&!reason)fail(422,'VALIDATION','Mileage is lower than the current recorded mileage. An explanation is required.');await c.query(`INSERT INTO mileage_history(vehicle_id,mileage,source,entered_by,captured_at,review_required,reason,data) VALUES($1,$2,'Customer Portal',$3,COALESCE($4,now()),$5,$6,$7::jsonb)`,[sv.id,mileage,req.user.id,safeDate(mr.at),lower,reason||null,JSON.stringify({legacyRef:legacy,customerUser:req.user.legacy_ref})]);if(!lower)await c.query('UPDATE vehicles SET current_mileage=$2,version=version+1,updated_at=now() WHERE id=$1',[sv.id,mileage]);else await addPortalAction(c,req,{customerId:m.customer.id,type:'Mileage review',refType:'Vehicle',refLegacy:iv.id,summary:`${iv.reg||iv.id} mileage ${mileage} is below trusted ${sv.current_mileage}`,reason,priority:'High'});await B.audit(c,req,'Vehicle',sv.id,iv.id,'Customer mileage submitted',{trustedMileage:Number(sv.current_mileage)},{submittedMileage:mileage,reviewRequired:lower},reason);changed=true}
 }
 // Data change requests never mutate master data themselves.
 for(const r of (incoming.portalDataChangeRequests||[])){const id=ref(r.id);if(!id)continue;const ex=await c.query('SELECT 1 FROM customer_data_change_requests WHERE legacy_ref=$1',[id]);if(ex.rowCount)continue;requireSubmit();let siteRef=null;if(r.recordType==='Vehicle'){const v=m.vehicleByRef.get(ref(r.recordId));if(!v)fail(403,'ACCESS_DENIED','ACCESS DENIED / NOT AUTHORISED');siteRef=[...m.siteByRef].find(([,sid])=>String(sid)===String(v.current_site_id))?.[0]}else if(r.recordType==='Site'){if(!m.siteByRef.has(ref(r.recordId)))fail(403,'ACCESS_DENIED','ACCESS DENIED / NOT AUTHORISED');siteRef=ref(r.recordId)}else fail(422,'VALIDATION','Unsupported customer data-change record type');const requested=cleanText(r.requestedValue,8000),reason=cleanText(r.reason,5000);if(!requested||!reason)fail(422,'VALIDATION','Requested value and reason are required');await c.query(`INSERT INTO customer_data_change_requests(legacy_ref,customer_id,submitted_by,record_type,record_ref,current_value,requested_value,reason,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'Operations Review',COALESCE($9,now()))`,[id,m.customer.id,req.user.id,r.recordType,ref(r.recordId),cleanText(r.currentValue,8000),requested,reason,safeDate(r.createdAt)]);await addPortalAction(c,req,{customerId:m.customer.id,type:'Customer Data Change Request',refType:'Data Change Request',refLegacy:id,summary:`${r.recordType} ${r.recordId}`,reason,siteRef});await B.audit(c,req,'CustomerDataChangeRequest',null,id,'Customer data-change request submitted',null,{recordType:r.recordType,recordRef:r.recordId},reason);changed=true}
 // VOR review and user-access requests are review requests only; they cannot directly change master/user authority.
 for(const a of (incoming.portalActions||[])){const id=ref(a.id);if(!id)continue;const ex=await c.query('SELECT 1 FROM portal_actions WHERE legacy_ref=$1',[id]);if(ex.rowCount)continue;if(a.type==='VOR review request'){requireSubmit();const v=m.vehicleByRef.get(ref(a.refId));if(!v)fail(403,'ACCESS_DENIED','ACCESS DENIED / NOT AUTHORISED');await addPortalAction(c,req,{legacyRef:id,customerId:m.customer.id,type:'VOR review request',refType:'Vehicle',refLegacy:a.refId,summary:cleanText(a.summary,5000)||`VOR review ${a.refId}`,reason:cleanText(a.reason,5000),priority:'High'});changed=true}}
 for(const r of (incoming.portalUserRequests||[])){const id=ref(r.id);if(!id)continue;const ex=await c.query('SELECT 1 FROM portal_user_requests WHERE legacy_ref=$1',[id]);if(ex.rowCount)continue;if(!has(req.user,'portal.users'))fail(403,'ACCESS_DENIED','ACCESS DENIED / NOT AUTHORISED');const requestedSites=(r.sites||[]).map(x=>m.siteByRef.get(ref(x))).filter(Boolean);if(requestedSites.length!==(r.sites||[]).length)fail(403,'ACCESS_DENIED','Requested user Site scope exceeds administrator authority');const role=cleanText(r.role,100);const allowedRoles=new Set(['Site Manager','Fleet Manager','Authoriser','Finance','Read Only']);if(!allowedRoles.has(role))fail(422,'VALIDATION','Requested role is not available in this test environment');await c.query(`INSERT INTO portal_user_requests(legacy_ref,customer_id,requested_by,requested_name,requested_email,requested_role,requested_site_ids,status,data) VALUES($1,$2,$3,$4,$5,$6,$7,'Operations Review',$8::jsonb)`,[id,m.customer.id,req.user.id,cleanText(r.name,500),cleanText(r.email,500).toLowerCase(),role,requestedSites,JSON.stringify({source:'Customer Portal'})]);await addPortalAction(c,req,{customerId:m.customer.id,type:'Customer user request',refType:'Customer User Request',refLegacy:id,summary:`${cleanText(r.name,500)} • ${role}`,reason:'Prototype user provisioning request'});changed=true}
 // Existing user administration may only activate/deactivate same-Customer users when portal.users is granted; role/scope changes are ignored here.
 if(has(req.user,'portal.users'))for(const pu of (incoming.portalUsers||[])){if(!pu.id||pu.id===req.user.legacy_ref)continue;const ur=await c.query('SELECT id,active FROM users WHERE legacy_ref=$1 AND customer_id=$2',[pu.id,req.user.customer_id]);if(!ur.rowCount)continue;const desired=pu.status!=='Inactive';if(desired!==ur.rows[0].active){await c.query('UPDATE users SET active=$2,updated_at=now() WHERE id=$1',[ur.rows[0].id,desired]);await B.audit(c,req,'User',ur.rows[0].id,pu.id,'Customer user status changed',{active:ur.rows[0].active},{active:desired},'Customer Administrator action');changed=true}}
 if(!changed)return{version:current,changed:false};const next=await bumpStateVersion(c);await B.audit(c,req,'SystemState',null,null,'Restricted Customer Portal compatibility commit',{version:current},{version:next},'Only authorised Portal mutations were applied');return{version:next,changed:true}
})}

function taskRequirements(t){if(t.id==='MOB-TK41')return{requires:['notes','fault','cause','measurement'],evidenceAny:['Fault / defect','Meter / diagnostic reading']};if(t.type==='Diagnosis')return{requires:['notes','fault','cause'],evidenceAny:['Fault / defect']};if(t.type==='Repair')return{requires:['notes'],evidenceAny:['Component after repair','Parts fitted','Completion']};if(t.type==='Service')return{requires:['notes','mileage'],evidenceAny:['Completion','Meter / diagnostic reading']};if(t.type==='Inspection')return{requires:['notes'],evidenceAny:['Fault / defect','Completion']};return{requires:['notes'],evidenceAny:[]}}
function validateTaskSnapshot(w,a,t){const r=taskRequirements(t),ans=t.mobileAnswers||{},missing=[];for(const k of r.requires){if(k==='notes'&&!cleanText(ans.notes))missing.push('Task notes / findings');if(k==='fault'&&!cleanText(ans.fault))missing.push('Fault found');if(k==='cause'&&!cleanText(ans.cause))missing.push('Cause');if(k==='measurement'&&!cleanText(ans.measurement))missing.push('Required measurement');if(k==='mileage'&&!(Number(ans.mileage)>0))missing.push('Mileage reading')}if(r.evidenceAny.length){const types=(w.evidence||[]).filter(e=>e.attendance===a.id&&e.task===t.id).map(e=>e.type);if(!r.evidenceAny.some(x=>types.includes(x)))missing.push('Required evidence')}if(missing.length)fail(422,'BUSINESS_RULE','Task Cannot Be Completed – Missing Requirements: '+missing.join(', '))}
function attendanceCompletionGate(a,techRole){const remote=/remote support/i.test(a.type||''),workshop=/workshop/i.test(techRole||''),j=a.journey||{},missing=[];if(!j.acceptedAt)missing.push('Attendance accepted');if(!remote&&!workshop&&!j.enRouteAt)missing.push('En Route');if(!remote&&!j.onSiteAt&&!a.arr)missing.push('Arrived / On Site');if(!remote&&(!a.vehicleConfirmation||!a.vehicleConfirmation.match))missing.push('Registration confirmed');if(!remote&&(!a.safety||!a.safety.safe))missing.push('Required safety check passed');if(!j.workStartedAt)missing.push('Work Started');if(missing.length)fail(422,'BUSINESS_RULE','Attendance Cannot Be Completed – '+missing.join(', '))}
async function technicianCommit(req){return tx(async c=>{
 const expected=Number(req.body.baseVersion),current=await getStateVersion(c);if(Number.isFinite(expected)&&expected!==current)fail(409,'CONFLICT','Server data changed. Refresh before retrying.');
 const incoming=req.body.state||{};const tr=(await c.query('SELECT * FROM technicians WHERE user_id=$1',[req.user.id])).rows[0];if(!tr)fail(403,'ACCESS_DENIED','Technician profile is not linked');let changed=false;
 const assigned=await c.query(`SELECT DISTINCT w.id,w.legacy_ref,w.vehicle_id,w.status wo_status,w.site_id FROM work_orders w JOIN attendances a ON a.work_order_id=w.id JOIN attendance_resource_assignments ar ON ar.attendance_id=a.id WHERE ar.technician_id=$1`,[tr.id]);const workByRef=new Map(assigned.rows.map(x=>[x.legacy_ref,x]));
 for(const iw of (incoming.wos||[])){const sw=workByRef.get(ref(iw.id));if(!sw)continue;const attRows=await c.query(`SELECT a.* FROM attendances a JOIN attendance_resource_assignments ar ON ar.attendance_id=a.id WHERE a.work_order_id=$1 AND ar.technician_id=$2 FOR UPDATE`,[sw.id,tr.id]);const taskRows=await c.query('SELECT * FROM tasks WHERE work_order_id=$1 FOR UPDATE',[sw.id]);const attByRef=new Map(attRows.rows.map(x=>[x.legacy_ref,x])),taskByRef=new Map(taskRows.rows.map(x=>[x.legacy_ref,x]));
  for(const ia of (iw.att||[])){const sa=attByRef.get(ref(ia.id));if(!sa)continue;
   if(ia.status&&ia.status!==sa.status){B.assertTransition('attendance',sa.status,ia.status);if(ia.status==='Completed'&&ia.completionRoute!=='Exception')attendanceCompletionGate(ia,tr.role_name);const arrived=ia.arr?safeDate(ia.arr):sa.arrived_at,departed=ia.dep?safeDate(ia.dep):sa.departed_at;const data={...(sa.data||{}),vehicleConfirmation:ia.vehicleConfirmation||sa.data?.vehicleConfirmation||null,safety:ia.safety||sa.data?.safety||null,journey:ia.journey||sa.data?.journey||null,completionRoute:ia.completionRoute||sa.data?.completionRoute||null,exception:ia.exception||sa.data?.exception||null};await c.query('UPDATE attendances SET status=$2,arrived_at=$3,departed_at=$4,outcome=$5,data=$6::jsonb,version=version+1,updated_at=now() WHERE id=$1',[sa.id,ia.status,arrived,departed,cleanText(ia.out,5000)||sa.outcome,JSON.stringify(data)]);await B.audit(c,req,'Attendance',sa.id,sa.legacy_ref,'Technician Attendance updated',{status:sa.status},{status:ia.status},ia.completionRoute==='Exception'?cleanText(ia.exception?.reason,2000):null);changed=true}
   // Technician actual time is append-only and remains separate from customer billability.
   for(const te of (ia.timeEntries||[])){if(ref(te.tech)!==tr.legacy_ref||!te.start)continue;const legacy=ref(te.id)||`${ia.id}-${tr.legacy_ref}-${te.start}`;const ex=await c.query('SELECT 1 FROM labour_time_entries WHERE legacy_ref=$1',[legacy]);if(ex.rowCount)continue;const tid=te.task?taskByRef.get(ref(te.task))?.id:null;const mins=Number(te.durationMinutes);await c.query(`INSERT INTO labour_time_entries(legacy_ref,technician_id,work_order_id,attendance_id,task_id,activity_type,started_at,ended_at,duration_minutes,chargeability_review_required,chargeability_reason,source,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'Technician Mobile',$12::jsonb)`,[legacy,tr.id,sw.id,sa.id,tid,cleanText(te.activity,100)||'Working',safeDate(te.start),safeDate(te.end),Number.isFinite(mins)?Math.max(0,Math.round(mins)):null,!!te.chargeabilityReviewRequired,cleanText(te.reviewReason||te.chargeabilityReason,2000)||null,JSON.stringify({activity:te.activity,source:'Technician Mobile'})]);const entry=(await c.query('SELECT id FROM labour_time_entries WHERE legacy_ref=$1',[legacy])).rows[0];let expectedMin=null;if(te.task){const tt=taskByRef.get(ref(te.task));if(tt?.srt_expected_hours!=null)expectedMin=Math.round(Number(tt.srt_expected_hours)*60)}const pr=await c.query(`SELECT prv.id,prv.labour_rate FROM work_orders w LEFT JOIN LATERAL(SELECT prv.*,pr.id pr_id FROM pricing_rules pr JOIN pricing_rule_versions prv ON prv.pricing_rule_id=pr.id WHERE pr.contract_id=w.contract_id AND prv.effective_from<=current_date AND (prv.effective_to IS NULL OR prv.effective_to>=current_date) ORDER BY prv.effective_from DESC LIMIT 1) prv ON true WHERE w.id=$1`,[sw.id]);const normal=['Working','Diagnosis','Repair','Service','Remote Support','Recovery Support'].includes(te.activity),proposed=normal&&Number.isFinite(mins)?Math.max(0,Math.round(mins)):0,needs=!!te.chargeabilityReviewRequired;await c.query(`INSERT INTO technician_labour_reviews(time_entry_id,work_order_id,attendance_id,task_id,technician_id,actual_minutes,expected_minutes,proposed_billable_minutes,approved_billable_minutes,pricing_rule_version_id,status,reviewer_user_id,reviewed_at,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb)`,[entry.id,sw.id,sa.id,tid,tr.id,Number.isFinite(mins)?Math.max(0,Math.round(mins)):0,expectedMin,proposed,needs?null:proposed,pr.rows[0]?.id||null,needs?'Pending Review':'Approved',needs?null:req.user.id,needs?null:new Date(),JSON.stringify({activity:te.activity,chargeabilityReviewRequired:needs,reviewReason:cleanText(te.reviewReason||te.chargeabilityReason,2000)})]);await B.audit(c,req,'LabourTimeEntry',entry.id,legacy,'Technician actual time recorded',null,{durationMinutes:mins,activity:te.activity,chargeabilityReviewRequired:needs},null);changed=true}
  }
  // Evidence metadata is persisted separately from Work Order JSON.
  for(const e of (iw.evidence||[])){const id=ref(e.id);if(!id)continue;const ex=await c.query('SELECT 1 FROM evidence_metadata WHERE legacy_ref=$1',[id]);if(ex.rowCount)continue;const aid=e.attendance?attByRef.get(ref(e.attendance))?.id:null,tid=e.task?taskByRef.get(ref(e.task))?.id:null;if(e.attendance&&!aid)fail(403,'ACCESS_DENIED','Evidence Attendance is outside technician assignment');if(e.task&&!tid)fail(403,'ACCESS_DENIED','Evidence Task is outside assigned Work Order');await c.query(`INSERT INTO evidence_metadata(legacy_ref,work_order_id,attendance_id,task_id,evidence_type,filename,visibility,storage_status,captured_by,captured_at,source,data) VALUES($1,$2,$3,$4,$5,$6,$7,'Metadata Only',$8,COALESCE($9,now()),'Technician Mobile',$10::jsonb)`,[id,sw.id,aid,tid,cleanText(e.type,200)||'Other',cleanText(e.name||e.filename,500)||null,e.visibility==='Customer Visible'?'Customer Visible':'Internal Kooner Only',req.user.id,safeDate(e.at),JSON.stringify({notes:cleanText(e.notes,5000),prototypePlaceholder:true})]);changed=true}
  // Task changes are controlled and Completion Rules are validated on the server.
  for(const it of (iw.tasks||[])){const st=taskByRef.get(ref(it.id));if(!st)continue;if(it.status===st.status){if(!same(it.mobileAnswers,st.data?.mobileAnswers)&&it.mobileAnswers){await c.query('UPDATE tasks SET data=jsonb_set(COALESCE(data,\'{}\'::jsonb),\'{mobileAnswers}\',$2::jsonb,true),updated_at=now() WHERE id=$1',[st.id,JSON.stringify(it.mobileAnswers)]);changed=true}continue}if(!['Not Started','In Progress','Completed','Awaiting Parts','Awaiting Approval','Blocked','Cancelled'].includes(it.status))fail(422,'BUSINESS_RULE','Invalid Task status');if(it.status==='Completed')validateTaskSnapshot(iw,(iw.att||[]).find(a=>(a.tech||[]).includes(tr.legacy_ref))||iw.att?.[0]||{},it);await c.query('UPDATE tasks SET status=$2,data=jsonb_set(COALESCE(data,\'{}\'::jsonb),\'{mobileAnswers}\',$3::jsonb,true),actual_hours=$4,version=version+1,updated_at=now() WHERE id=$1',[st.id,it.status,JSON.stringify(it.mobileAnswers||{}),Number.isFinite(Number(it.actual))?Number(it.actual):st.actual_hours]);await B.audit(c,req,'Task',st.id,st.legacy_ref,'Technician Task updated',{status:st.status},{status:it.status},it.status==='Completed'?'Completion Rules passed':null);changed=true}
  // Technician mileage history is append-only; lower readings are retained for review without reducing trusted mileage.
  const vr=(await c.query('SELECT * FROM vehicles WHERE id=$1 FOR UPDATE',[sw.vehicle_id])).rows[0];for(const mr of ((incoming.vehicles||[]).find(v=>ref(v.id)===ref(iw.v))?.mileageRecords||[])){const legacy=ref(mr.id);if(!legacy||!/^MR-MOB/i.test(legacy))continue;const ex=await c.query("SELECT 1 FROM mileage_history WHERE data->>'legacyRef'=$1",[legacy]);if(ex.rowCount)continue;const mileage=Number(mr.mileage),lower=mileage<Number(vr.current_mileage||0),reason=cleanText(mr.reviewReason||mr.mileageReason,2000);if(lower&&!reason)fail(422,'VALIDATION','Mileage is lower than the current recorded mileage. An explanation is required.');const ar=mr.attendance?attByRef.get(ref(mr.attendance)):null;await c.query(`INSERT INTO mileage_history(vehicle_id,mileage,source,entered_by,work_order_id,attendance_id,captured_at,review_required,reason,data) VALUES($1,$2,'Technician Mobile',$3,$4,$5,COALESCE($6,now()),$7,$8,$9::jsonb)`,[vr.id,mileage,req.user.id,sw.id,ar?.id||null,safeDate(mr.at),lower,reason||null,JSON.stringify({legacyRef:legacy,task:mr.task||null})]);if(!lower)await c.query('UPDATE vehicles SET current_mileage=$2,version=version+1,updated_at=now() WHERE id=$1',[vr.id,mileage]);else await addPortalAction(c,req,{customerId:(await c.query('SELECT customer_id FROM work_orders WHERE id=$1',[sw.id])).rows[0].customer_id,type:'Technician mileage review',refType:'Vehicle',refLegacy:iw.v,summary:`Lower technician mileage ${mileage} requires Operations review`,reason,priority:'High'});changed=true}
  // Work Order state is server-derived from resulting Tasks; Attendance completion alone never closes it.
  const open=(await c.query("SELECT count(*)::int n FROM tasks WHERE work_order_id=$1 AND required=true AND status NOT IN ('Completed','Cancelled','Resolved by Override')",[sw.id])).rows[0].n;if(open===0){const active=(await c.query("SELECT count(*)::int n FROM attendances WHERE work_order_id=$1 AND status NOT IN ('Completed','Cancelled','Rejected')",[sw.id])).rows[0].n;if(active===0&&sw.wo_status!=='Operationally Complete'){await c.query("UPDATE work_orders SET status='Operationally Complete',financial_status=CASE WHEN financial_status='Not Started' THEN 'Billing Review' ELSE financial_status END,current_owner='Billing',next_action='Commercial review',version=version+1,updated_at=now() WHERE id=$1",[sw.id]);changed=true}}else{const blocker=(iw.tasks||[]).find(t=>!['Completed','Cancelled','Resolved by Override'].includes(t.status));if(blocker){let status=blocker.status==='Awaiting Parts'?'Awaiting Parts':blocker.status==='Awaiting Approval'?'Awaiting Approval':'In Progress',owner=status==='Awaiting Parts'?'Parts':status==='Awaiting Approval'?'Customer':'Technician',next=status==='Awaiting Parts'?'Resolve parts requirement':status==='Awaiting Approval'?'Await customer approval':'Complete assigned Tasks';await c.query('UPDATE work_orders SET status=$2,current_owner=$3,next_action=$4,version=version+1,updated_at=now() WHERE id=$1',[sw.id,status,owner,next]);changed=true}}
 }
 if(!changed)return{version:current,changed:false};const next=await bumpStateVersion(c);await B.audit(c,req,'SystemState',null,null,'Restricted Technician Mobile compatibility commit',{version:current},{version:next},'Only assigned technician fields were applied');return{version:next,changed:true}
})}

app.get('/api/v1/bootstrap',requireAuth,async(req,res,next)=>{try{const p=await buildLegacyState(req.user);res.json(await enrichBootstrap(req.user,p))}catch(e){next(e)}});
app.put('/api/v1/compat/state',requireAuth,csrfRequired,async(req,res,next)=>{try{
 if(req.user.user_type==='customer'){const out=await customerCommit(req);return res.json({ok:true,stateVersion:out.version,restricted:true,changed:out.changed})}
 if(req.user.roles.includes('technician')){const out=await technicianCommit(req);return res.json({ok:true,stateVersion:out.version,restricted:true,changed:out.changed})}
 return next()
}catch(e){next(e)}});

app.use(inner);
app.use((err,req,res,next)=>{console.error(JSON.stringify({level:'error',event:'stage6_gateway_error',requestId:req.id,code:err.code||null,message:err.message}));const status=err.status||500;res.status(status).json({error:err.code||'SERVER_ERROR',message:status>=500?'Unexpected server error':err.message,requestId:req.id,...(err.serverVersion?{serverVersion:err.serverVersion}:{})})});
module.exports=app;
