'use strict';
const {query,tx,getStateVersion,bumpStateVersion}=require('./db');
const crypto=require('crypto');

const WO_STATUSES=new Set(['Draft','Pending Triage','Planned','Dispatched','Accepted','En Route','On Site','In Progress','Awaiting Approval','Awaiting Parts','On Hold','Operationally Complete','Cancelled']);
const ATT_STATUSES=new Set(['Planned','Dispatched','Accepted','En Route','On Site','In Progress','Paused','Completed','Rejected','Cancelled','Stopped for Safety']);
const EST_STATUSES=new Set(['Draft','Sent','Viewed','Approved','Declined','Superseded','Cancelled']);
const BILL_STATUSES=new Set(['Not Started','Billing Review','Validated','Ready to Invoice','Invoiced','Financially Closed / No Charge']);

function safeObj(v){return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}
function ref(v){return String(v||'').trim()}
function numeric(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function isoOrNull(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.valueOf())?null:d.toISOString()}
function dateOrNull(v){if(!v)return null;const s=String(v).slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:null}
function json(v){return JSON.stringify(v??{})}
function correlation(){return crypto.randomUUID()}

async function maps(client){
 const out={};
 for(const [k,t] of Object.entries({customers:'customers',contracts:'contracts',sites:'sites',vehicles:'vehicles',technicians:'technicians',workOrders:'work_orders',attendances:'attendances',tasks:'tasks',invoices:'invoices'})){
  const r=await client.query(`SELECT id,legacy_ref FROM ${t}`);out[k]=new Map(r.rows.map(x=>[x.legacy_ref,String(x.id)]));
 }
 return out;
}
async function audit(client,{entityType,entityId=null,entityRef=null,action,user,source='System',prev=null,next=null,reason=null,requestId=null,ip=null}){
 await client.query(`INSERT INTO audit_events(entity_type,entity_id,entity_ref,action,user_id,user_role,source,previous_value,new_value,reason,correlation_id,ip_address)
 VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10,$11,$12)`,[entityType,entityId,entityRef,action,user?.id||null,user?.roles?.[0]||null,source,prev?json(prev):null,next?json(next):null,reason,requestId||correlation(),ip]);
}
async function scopeRefs(client,user){
 if(!user||user.user_type==='internal')return{internal:true,customerRefs:null,siteRefs:null};
 const c=await client.query('SELECT legacy_ref FROM customers WHERE id=$1',[user.customer_id]);
 const s=await client.query(`SELECT si.legacy_ref FROM user_scopes us JOIN sites si ON si.id=us.site_id WHERE us.user_id=$1 AND us.site_id IS NOT NULL`,[user.id]);
 return{internal:false,customerRefs:new Set(c.rows.map(x=>x.legacy_ref)),siteRefs:new Set(s.rows.map(x=>x.legacy_ref))};
}
function assertAllowed(scope,customerRef,siteRef){
 if(scope.internal)return;
 if(customerRef&&!scope.customerRefs.has(customerRef))throw Object.assign(new Error('Customer scope violation'),{status:403,code:'ACCESS_DENIED'});
 if(siteRef&&!scope.siteRefs.has(siteRef))throw Object.assign(new Error('Site scope violation'),{status:403,code:'ACCESS_DENIED'});
}

async function upsertLegacyState(state,user,opts={}){
 return tx(async client=>{
  const expected=opts.baseVersion==null?null:Number(opts.baseVersion),current=await getStateVersion(client);
  if(expected!=null&&expected!==current)throw Object.assign(new Error('Server data changed. Refresh before retrying.'),{status:409,code:'CONFLICT',serverVersion:current});
  const scope=await scopeRefs(client,user),source=opts.source||'Operations/Desktop',requestId=opts.requestId||correlation();
  const customers=Array.isArray(state.customers)?state.customers:[];
  for(const x of customers){assertAllowed(scope,ref(x.id),null);if(!scope.internal)continue;await client.query(`INSERT INTO customers(legacy_ref,name,account_code,data) VALUES($1,$2,$3,$4::jsonb)
   ON CONFLICT(legacy_ref) DO UPDATE SET name=EXCLUDED.name,account_code=EXCLUDED.account_code,data=EXCLUDED.data,version=customers.version+1,updated_at=now()`,[ref(x.id),x.name||ref(x.id),x.account||null,json(x)])}
  let m=await maps(client);
  for(const x of (state.contracts||[])){
   assertAllowed(scope,ref(x.c),null);if(!scope.internal)continue;const cid=m.customers.get(ref(x.c));if(!cid)continue;
   await client.query(`INSERT INTO contracts(legacy_ref,customer_id,name,contract_type,effective_from,effective_to,data) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)
   ON CONFLICT(legacy_ref) DO UPDATE SET customer_id=EXCLUDED.customer_id,name=EXCLUDED.name,contract_type=EXCLUDED.contract_type,effective_from=EXCLUDED.effective_from,effective_to=EXCLUDED.effective_to,data=EXCLUDED.data,version=contracts.version+1,updated_at=now()`,[ref(x.id),cid,x.name||ref(x.id),x.type||null,dateOrNull(x.from),dateOrNull(x.to),json(x)])}
  for(const x of (state.sites||[])){
   assertAllowed(scope,ref(x.c),ref(x.id));if(!scope.internal)continue;const cid=m.customers.get(ref(x.c));if(!cid)continue;
   await client.query(`INSERT INTO sites(legacy_ref,customer_id,name,address,postcode,data) VALUES($1,$2,$3,$4,$5,$6::jsonb)
   ON CONFLICT(legacy_ref) DO UPDATE SET customer_id=EXCLUDED.customer_id,name=EXCLUDED.name,address=EXCLUDED.address,postcode=EXCLUDED.postcode,data=EXCLUDED.data,version=sites.version+1,updated_at=now()`,[ref(x.id),cid,x.name||ref(x.id),x.addr||null,x.pc||null,json(x)])}
  m=await maps(client);
  for(const x of (state.vehicles||[])){
   assertAllowed(scope,ref(x.c),ref(x.s));const cid=m.customers.get(ref(x.c)),sid=m.sites.get(ref(x.s));if(!cid||!sid)continue;
   const exists=await client.query('SELECT id,current_mileage,data FROM vehicles WHERE legacy_ref=$1',[ref(x.id)]);
   if(!scope.internal&&exists.rowCount){const old=exists.rows[0];const allowed={...safeObj(old.data),miles:numeric(x.miles,old.current_mileage),status:x.status,maint:x.maint,nextD:x.nextD,nextM:x.nextM};x.miles=allowed.miles;x.status=allowed.status;x.maint=allowed.maint;x.nextD=allowed.nextD;x.nextM=allowed.nextM}
   await client.query(`INSERT INTO vehicles(legacy_ref,customer_id,current_site_id,registration,vin,unit_number,make,model,vehicle_type,current_mileage,status,vor,data)
   VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb)
   ON CONFLICT(legacy_ref) DO UPDATE SET current_site_id=EXCLUDED.current_site_id,current_mileage=GREATEST(vehicles.current_mileage,EXCLUDED.current_mileage),status=EXCLUDED.status,vor=EXCLUDED.vor,data=EXCLUDED.data,version=vehicles.version+1,updated_at=now()`,[ref(x.id),cid,sid,String(x.reg||'').toUpperCase(),x.vin||null,x.unit||null,x.make||null,x.model||null,x.type||null,numeric(x.miles,0),x.status||'In Service',!!x.vor,json(x)]);
   const vid=(await client.query('SELECT id FROM vehicles WHERE legacy_ref=$1',[ref(x.id)])).rows[0].id;
   const cur=await client.query('SELECT id,site_id FROM vehicle_site_assignments WHERE vehicle_id=$1 AND current=true',[vid]);
   if(!cur.rowCount)await client.query('INSERT INTO vehicle_site_assignments(vehicle_id,site_id,effective_from,current,reason) VALUES($1,$2,COALESCE($3,current_date),true,$4)',[vid,sid,dateOrNull(x.onboardedAt||x.effectiveFrom),'Prototype/Stage 6 seed']);
   else if(String(cur.rows[0].site_id)!==String(sid)&&scope.internal){await client.query('UPDATE vehicle_site_assignments SET current=false,effective_to=current_date WHERE id=$1',[cur.rows[0].id]);await client.query('INSERT INTO vehicle_site_assignments(vehicle_id,site_id,effective_from,current,reason,changed_by) VALUES($1,$2,current_date,true,$3,$4)',[vid,sid,'Stage 6 compatibility site move',user?.id||null])}
  }
  if(scope.internal){
   for(const x of (state.techs||[])){
    await client.query(`INSERT INTO technicians(legacy_ref,display_name,role_name,base_region,status,assigned_van,benchmark_group,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)
    ON CONFLICT(legacy_ref) DO UPDATE SET display_name=EXCLUDED.display_name,role_name=EXCLUDED.role_name,base_region=EXCLUDED.base_region,status=EXCLUDED.status,assigned_van=EXCLUDED.assigned_van,benchmark_group=EXCLUDED.benchmark_group,data=EXCLUDED.data,version=technicians.version+1,updated_at=now()`,[ref(x.id),x.name||ref(x.id),x.role||null,x.base||null,x.status||null,x.van||null,x.group||null,json(x)])}
  }
  m=await maps(client);
  const pricing=state.pricingRules||{};
  if(scope.internal){for(const [contractRef,p] of Object.entries(pricing)){const ctid=m.contracts.get(contractRef);if(!ctid)continue;const cr=await client.query('SELECT customer_id FROM contracts WHERE id=$1',[ctid]);const legacy=ref(p.id||`PR-${contractRef}`);await client.query(`INSERT INTO pricing_rules(legacy_ref,customer_id,contract_id,name,data) VALUES($1,$2,$3,$4,$5::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET data=EXCLUDED.data`,[legacy,cr.rows[0].customer_id,ctid,p.name||legacy,json(p)]);const rid=(await client.query('SELECT id FROM pricing_rules WHERE legacy_ref=$1',[legacy])).rows[0].id;await client.query(`INSERT INTO pricing_rule_versions(pricing_rule_id,version_no,effective_from,labour_rate,parts_markup_percent,third_party_markup_percent,mileage_rate,vat_percent,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) ON CONFLICT(pricing_rule_id,version_no) DO UPDATE SET labour_rate=EXCLUDED.labour_rate,parts_markup_percent=EXCLUDED.parts_markup_percent,third_party_markup_percent=EXCLUDED.third_party_markup_percent,mileage_rate=EXCLUDED.mileage_rate,vat_percent=EXCLUDED.vat_percent,data=EXCLUDED.data`,[rid,numeric(p.version,1),dateOrNull(p.effective)||'2026-01-01',numeric(p.labour),numeric(p.partsMarkup),numeric(p.thirdMarkup),numeric(p.mileage),numeric(p.vat,20),json(p)])}}
  }
  for(const w of (state.wos||[])){
   assertAllowed(scope,ref(w.c),ref(w.s));const cid=m.customers.get(ref(w.c)),sid=m.sites.get(ref(w.s)),vid=m.vehicles.get(ref(w.v)),ctid=m.contracts.get(ref(w.ct));if(!cid||!sid||!vid)continue;
   if(!WO_STATUSES.has(w.status))throw Object.assign(new Error(`Invalid Work Order status: ${w.status}`),{status:422,code:'BUSINESS_RULE'});
   if(w.fin&&!BILL_STATUSES.has(w.fin))throw Object.assign(new Error(`Invalid Billing status: ${w.fin}`),{status:422,code:'BUSINESS_RULE'});
   await client.query(`INSERT INTO work_orders(legacy_ref,customer_id,contract_id,site_id,vehicle_id,work_type,priority,fault_description,status,financial_status,current_owner,next_action,due_at,customer_reference,vor,data,created_at)
   VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16::jsonb,COALESCE($17,now()))
   ON CONFLICT(legacy_ref) DO UPDATE SET status=EXCLUDED.status,financial_status=EXCLUDED.financial_status,current_owner=EXCLUDED.current_owner,next_action=EXCLUDED.next_action,due_at=EXCLUDED.due_at,customer_reference=EXCLUDED.customer_reference,vor=EXCLUDED.vor,data=EXCLUDED.data,version=work_orders.version+1,updated_at=now()`,[ref(w.id),cid,ctid||null,sid,vid,w.cat||'Other',w.pri||null,w.fault||'No description',w.status,w.fin||'Not Started',w.owner||null,w.next||null,isoOrNull(w.due),w.po||null,!!w.vor,json({...w,att:undefined,tasks:undefined,ests:undefined,parts:undefined,audit:undefined}),isoOrNull(w.created)]);
   const wid=(await client.query('SELECT id FROM work_orders WHERE legacy_ref=$1',[ref(w.id)])).rows[0].id;
   for(const a of (w.att||[])){
    if(!ATT_STATUSES.has(a.status))throw Object.assign(new Error(`Invalid Attendance status: ${a.status}`),{status:422,code:'BUSINESS_RULE'});
    await client.query(`INSERT INTO attendances(legacy_ref,work_order_id,attendance_type,status,planned_at,arrived_at,departed_at,outcome,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)
    ON CONFLICT(legacy_ref) DO UPDATE SET status=EXCLUDED.status,planned_at=EXCLUDED.planned_at,arrived_at=EXCLUDED.arrived_at,departed_at=EXCLUDED.departed_at,outcome=EXCLUDED.outcome,data=EXCLUDED.data,version=attendances.version+1,updated_at=now()`,[ref(a.id),wid,a.type||'Other',a.status,isoOrNull(a.plan),isoOrNull(a.arr),isoOrNull(a.dep),a.out||null,json({...a,tech:undefined,timeEntries:undefined,lab:undefined})]);
    const aid=(await client.query('SELECT id FROM attendances WHERE legacy_ref=$1',[ref(a.id)])).rows[0].id;
    if(scope.internal){await client.query('DELETE FROM attendance_resource_assignments WHERE attendance_id=$1',[aid]);for(const tr of (a.tech||[])){const tid=m.technicians.get(ref(tr));if(tid)await client.query('INSERT INTO attendance_resource_assignments(attendance_id,technician_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[aid,tid])}}
    for(const te of (a.timeEntries||[])){
     const tr=m.technicians.get(ref(te.tech));if(!tr||!te.start)continue;const taskId=te.task?m.tasks.get(ref(te.task)):null;const legacy=ref(te.id||`${a.id}-${te.tech}-${te.start}`);await client.query(`INSERT INTO labour_time_entries(legacy_ref,technician_id,work_order_id,attendance_id,task_id,activity_type,started_at,ended_at,duration_minutes,chargeability_review_required,chargeability_reason,source,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET ended_at=EXCLUDED.ended_at,duration_minutes=EXCLUDED.duration_minutes,chargeability_review_required=EXCLUDED.chargeability_review_required,chargeability_reason=EXCLUDED.chargeability_reason,data=EXCLUDED.data`,[legacy,tr,wid,aid,taskId,te.activity||'Working',isoOrNull(te.start),isoOrNull(te.end),numeric(te.durationMinutes,null),!!te.chargeabilityReview,te.chargeabilityReason||null,'Technician Mobile',json(te)])
    }
   }
   for(const t of (w.tasks||[])){
    const st=t.status||'Not Started';await client.query(`INSERT INTO tasks(legacy_ref,work_order_id,description,task_type,status,required,srt_expected_hours,actual_hours,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET status=EXCLUDED.status,required=EXCLUDED.required,srt_expected_hours=EXCLUDED.srt_expected_hours,actual_hours=EXCLUDED.actual_hours,data=EXCLUDED.data,version=tasks.version+1,updated_at=now()`,[ref(t.id),wid,t.desc||ref(t.id),t.type||'Other',st,t.required!==false,numeric(t.srt,null),numeric(t.actual,null),json(t)])
   }
   m=await maps(client);
   for(const e of (w.ests||[])){
    const versions=e.versions||[];const current=[...versions].sort((a,b)=>numeric(b.v)-numeric(a.v))[0];const overall=current?.status||'Draft';await client.query(`INSERT INTO estimates(legacy_ref,work_order_id,status,current_version_no) VALUES($1,$2,$3,$4) ON CONFLICT(legacy_ref) DO UPDATE SET status=EXCLUDED.status,current_version_no=EXCLUDED.current_version_no,version=estimates.version+1,updated_at=now()`,[ref(e.id),wid,overall,numeric(current?.v,1)]);const eid=(await client.query('SELECT id FROM estimates WHERE legacy_ref=$1',[ref(e.id)])).rows[0].id;
    for(const ev of versions){if(!EST_STATUSES.has(ev.status))continue;const net=numeric(ev.net,numeric(ev.hrs)*numeric(ev.rate)+numeric(ev.parts)*(1+numeric(ev.markup)/100)+numeric(ev.other));const vat=net*numeric(ev.vat,20)/100;await client.query(`INSERT INTO estimate_versions(estimate_id,version_no,status,net,vat,gross,scope,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb) ON CONFLICT(estimate_id,version_no) DO UPDATE SET status=EXCLUDED.status,net=EXCLUDED.net,vat=EXCLUDED.vat,gross=EXCLUDED.gross,scope=EXCLUDED.scope,data=EXCLUDED.data`,[eid,numeric(ev.v,1),ev.status,net,vat,net+vat,ev.scope||null,json(ev)])}
   }
  }
  m=await maps(client);
  if(scope.internal){
   for(const inv of (state.invoices||[])){const cid=m.customers.get(ref(inv.customer));if(!cid)continue;const sid=inv.site?m.sites.get(ref(inv.site)):null;await client.query(`INSERT INTO invoices(legacy_ref,customer_id,explicit_site_id,invoice_type,status,issue_date,period_start,period_end,customer_reference,net,vat,gross,data,locked_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14) ON CONFLICT(legacy_ref) DO UPDATE SET status=EXCLUDED.status,data=EXCLUDED.data`,[ref(inv.id),cid,sid,inv.type||'One Work Order',inv.status||'Issued',dateOrNull(inv.date),inv.period?`${inv.period}-01`:null,inv.period?new Date(Number(inv.period.slice(0,4)),Number(inv.period.slice(5,7)),0).toISOString().slice(0,10):null,inv.po||null,numeric(inv.net),numeric(inv.vat),numeric(inv.gross),json(inv),inv.status==='Issued'?isoOrNull(inv.date)||new Date().toISOString():null]);const iid=(await client.query('SELECT id FROM invoices WHERE legacy_ref=$1',[ref(inv.id)])).rows[0].id;await client.query('DELETE FROM invoice_lines WHERE invoice_id=$1',[iid]);for(const l of (inv.lines||[])){const wid=m.workOrders.get(ref(l.workOrder||l.reference));const lsid=l.site?m.sites.get(ref(l.site)):null;const lvid=l.vehicle?m.vehicles.get(ref(l.vehicle)):null;await client.query('INSERT INTO invoice_lines(invoice_id,line_type,description,amount,work_order_id,site_id,vehicle_id,source_ref,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)',[iid,l.type||'Other',l.description||l.type||'Charge',numeric(l.amount),wid||null,lsid||null,lvid||null,l.reference||null,json(l)])}}
  }
  for(const d of (state.documents||[])){
   const cid=m.customers.get(ref(d.customer));if(!cid)continue;assertAllowed(scope,ref(d.customer),ref(d.site));const sid=d.site?m.sites.get(ref(d.site)):null,vid=d.vehicle?m.vehicles.get(ref(d.vehicle)):null,wid=d.workOrder?m.workOrders.get(ref(d.workOrder)):null,iid=d.invoice?m.invoices.get(ref(d.invoice)):null;
   await client.query(`INSERT INTO documents(legacy_ref,customer_id,site_id,vehicle_id,work_order_id,invoice_id,filename,visibility,storage_status,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'Metadata Only',$9::jsonb) ON CONFLICT(legacy_ref) DO UPDATE SET visibility=EXCLUDED.visibility,data=EXCLUDED.data`,[ref(d.id),cid,sid||null,vid||null,wid||null,iid||null,d.name||d.filename||ref(d.id),d.visibility||'Internal Kooner Only',json(d)])
  }
  if(scope.internal){for(const d of (state.defects||[])){const dr=ref(d.id);if(!/^DCR-\d+$/i.test(dr))continue;await client.query(`INSERT INTO dcr_items(dcr_ref,area,description,item_type,priority,status,resolution,retest_result,deferred) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(dcr_ref) DO UPDATE SET area=EXCLUDED.area,description=EXCLUDED.description,item_type=EXCLUDED.item_type,priority=EXCLUDED.priority,status=EXCLUDED.status,resolution=EXCLUDED.resolution,retest_result=EXCLUDED.retest_result,deferred=EXCLUDED.deferred,updated_at=now()`,[dr,d.area||'Legacy',d.desc||'Migrated legacy DCR',d.type||'Change',d.priority||'P2',d.status||'Agreed',d.resolution||null,d.retest||null,!!d.deferred]);const did=(await client.query('SELECT id FROM dcr_items WHERE dcr_ref=$1',[dr])).rows[0].id;for(const h of (d.history||[])){const at=isoOrNull(h.at)||new Date().toISOString();await client.query(`INSERT INTO dcr_history(dcr_id,from_status,to_status,note,changed_by,changed_at) SELECT $1,$2,$3,$4,$5,$6 WHERE NOT EXISTS(SELECT 1 FROM dcr_history WHERE dcr_id=$1 AND changed_at=$6 AND COALESCE(note,'')=COALESCE($4,''))`,[did,h.from||null,h.to||null,h.note||null,h.by||'Migrated',at])}}}
  for(const r of (state.portalRequests||[])){const cid=m.customers.get(ref(r.customer||r.c)),sid=m.sites.get(ref(r.site||r.s)),vid=m.vehicles.get(ref(r.vehicle||r.v));if(!cid)continue;assertAllowed(scope,ref(r.customer||r.c),ref(r.site||r.s));await client.query(`INSERT INTO portal_requests(legacy_ref,customer_id,site_id,vehicle_id,submitted_by,request_type,vehicle_status,description,status,emergency,data,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,COALESCE($12,now())) ON CONFLICT(legacy_ref) DO UPDATE SET status=EXCLUDED.status,data=EXCLUDED.data,version=portal_requests.version+1,updated_at=now()`,[ref(r.id),cid,sid||null,vid||null,user?.id||null,r.requestType||r.type||'Other',r.vehicleStatus||null,r.fault||r.description||'Customer Portal request',r.status||'Awaiting Operations Triage',!!r.emergency,json(r),isoOrNull(r.createdAt)])}
  if(scope.internal){for(const x of (state.portalActions||[])){const cid=m.customers.get(ref(x.customer));if(!cid)continue;await client.query(`INSERT INTO portal_actions(legacy_ref,customer_id,action_type,ref_type,ref_legacy,summary,reason,priority,status,data,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,COALESCE($11,now())) ON CONFLICT(legacy_ref) DO UPDATE SET status=EXCLUDED.status,data=EXCLUDED.data,resolved_at=CASE WHEN EXCLUDED.status='Resolved' THEN now() ELSE NULL END`,[ref(x.id),cid,x.type||'Portal Action',x.refType||null,x.refId||null,x.summary||x.type||'Portal Action',x.reason||null,x.priority||'Normal',x.status||'New',json(x),isoOrNull(x.createdAt)])}}
  const config={settings:state.settings||{},mobileSettings:state.mobileSettings||{},mobileDevice:state.mobileDevice||{},billingRunSettings:state.billingRunSettings||{},portalSettings:scope.internal?(state.portalSettings||{}):{}};
  if(scope.internal)await client.query(`INSERT INTO system_meta(key,value,updated_at) VALUES('compatibility_config',$1::jsonb,now()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()`,[json(config)]);
  const next=await bumpStateVersion(client);await audit(client,{entityType:'SystemState',action:'Compatibility state committed to relational backend',user,source,requestId,reason:`State version ${current} → ${next}`,ip:opts.ip});return{version:next};
 })
}

async function fullLegacyState(client){
 const s={customers:[],sites:[],contracts:[],vehicles:[],techs:[],wos:[],defects:[],invoices:[],documents:[],portalRequests:[],portalActions:[],pricingRules:{},srtOps:[],shifts:[]};
 const plain=async(table,key)=>{const r=await client.query(`SELECT * FROM ${table}`);return r.rows.map(x=>Object.keys(safeObj(x.data)).length?x.data:{})};
 s.customers=await plain('customers');s.sites=await plain('sites');s.contracts=await plain('contracts');s.vehicles=await plain('vehicles');s.techs=await plain('technicians');
 const techRows=await client.query('SELECT legacy_ref,data,display_name,role_name,base_region,status,assigned_van,benchmark_group FROM technicians');s.techs=techRows.rows.map(x=>({...safeObj(x.data),id:x.legacy_ref,name:x.data?.name||x.display_name,role:x.data?.role||x.role_name,base:x.data?.base||x.base_region,status:x.status,van:x.data?.van||x.assigned_van,group:x.data?.group||x.benchmark_group}));
 const shiftRows=await client.query(`SELECT sh.*,t.legacy_ref tech_ref FROM shifts sh JOIN technicians t ON t.id=sh.technician_id`);s.shifts=shiftRows.rows.map(x=>({...safeObj(x.data),id:x.legacy_ref||String(x.id),tech:x.tech_ref,date:String(x.shift_date).slice(0,10),start:x.start_time?String(x.start_time).slice(0,5):'',end:x.end_time?String(x.end_time).slice(0,5):'',status:x.status}));
 const woRows=await client.query(`SELECT w.*,c.legacy_ref c_ref,ct.legacy_ref ct_ref,si.legacy_ref s_ref,v.legacy_ref v_ref FROM work_orders w JOIN customers c ON c.id=w.customer_id LEFT JOIN contracts ct ON ct.id=w.contract_id JOIN sites si ON si.id=w.site_id JOIN vehicles v ON v.id=w.vehicle_id ORDER BY w.created_at`);
 for(const row of woRows.rows){let w={...safeObj(row.data),id:row.legacy_ref,c:row.c_ref,ct:row.ct_ref,s:row.s_ref,v:row.v_ref,cat:row.work_type,pri:row.priority,fault:row.fault_description,status:row.status,fin:row.financial_status,owner:row.current_owner,next:row.next_action,due:row.due_at,po:row.customer_reference,vor:row.vor,created:row.created_at,att:[],tasks:[],ests:[],parts:[],audit:[]};
  const ar=await client.query(`SELECT a.*,COALESCE(json_agg(t.legacy_ref) FILTER(WHERE t.legacy_ref IS NOT NULL),'[]') tech_refs FROM attendances a LEFT JOIN attendance_resource_assignments ara ON ara.attendance_id=a.id LEFT JOIN technicians t ON t.id=ara.technician_id WHERE a.work_order_id=$1 GROUP BY a.id ORDER BY a.planned_at`,[row.id]);
  for(const a of ar.rows){const tr=await client.query(`SELECT l.*,t.legacy_ref tech_ref,ta.legacy_ref task_ref FROM labour_time_entries l JOIN technicians t ON t.id=l.technician_id LEFT JOIN tasks ta ON ta.id=l.task_id WHERE l.attendance_id=$1 ORDER BY l.started_at`,[a.id]);w.att.push({...safeObj(a.data),id:a.legacy_ref,type:a.attendance_type,status:a.status,plan:a.planned_at,arr:a.arrived_at||'',dep:a.departed_at||'',out:a.outcome||'',tech:a.tech_refs,timeEntries:tr.rows.map(x=>({...safeObj(x.data),id:x.legacy_ref,tech:x.tech_ref,task:x.task_ref,activity:x.activity_type,start:x.started_at,end:x.ended_at,durationMinutes:x.duration_minutes,chargeabilityReview:x.chargeability_review_required,chargeabilityReason:x.chargeability_reason}))})}
  const ts=await client.query('SELECT * FROM tasks WHERE work_order_id=$1 ORDER BY created_at',[row.id]);w.tasks=ts.rows.map(t=>({...safeObj(t.data),id:t.legacy_ref,desc:t.description,type:t.task_type,status:t.status,required:t.required,srt:t.srt_expected_hours==null?null:Number(t.srt_expected_hours),actual:t.actual_hours==null?null:Number(t.actual_hours)}));
  const es=await client.query('SELECT * FROM estimates WHERE work_order_id=$1',[row.id]);for(const e of es.rows){const vs=await client.query('SELECT * FROM estimate_versions WHERE estimate_id=$1 ORDER BY version_no',[e.id]);w.ests.push({id:e.legacy_ref,versions:vs.rows.map(v=>({...safeObj(v.data),v:v.version_no,status:v.status,scope:v.scope,net:Number(v.net),vatAmount:Number(v.vat),gross:Number(v.gross)}))})}
  const au=await client.query('SELECT created_at,user_role,action,reason,new_value FROM audit_events WHERE entity_type=$1 AND entity_ref=$2 ORDER BY created_at',['WorkOrder',row.legacy_ref]);w.audit=au.rows.map(a=>[a.created_at,a.user_role||'System',a.action,a.reason||'']);s.wos.push(w)
 }
 const d=await client.query('SELECT * FROM dcr_items ORDER BY dcr_ref');for(const x of d.rows){const h=await client.query('SELECT * FROM dcr_history WHERE dcr_id=$1 ORDER BY changed_at',[x.id]);s.defects.push({id:x.dcr_ref,area:x.area,desc:x.description,type:x.item_type,priority:x.priority,status:x.status,resolution:x.resolution,retest:x.retest_result,deferred:x.deferred,history:h.rows.map(y=>({at:y.changed_at,by:y.changed_by,from:y.from_status,to:y.to_status,note:y.note}))})}
 const inv=await client.query(`SELECT i.*,c.legacy_ref c_ref,sit.legacy_ref site_ref FROM invoices i JOIN customers c ON c.id=i.customer_id LEFT JOIN sites sit ON sit.id=i.explicit_site_id ORDER BY issue_date`);for(const i of inv.rows){const lines=await client.query(`SELECT il.*,w.legacy_ref wo_ref,s.legacy_ref site_ref,v.legacy_ref v_ref FROM invoice_lines il LEFT JOIN work_orders w ON w.id=il.work_order_id LEFT JOIN sites s ON s.id=il.site_id LEFT JOIN vehicles v ON v.id=il.vehicle_id WHERE il.invoice_id=$1`,[i.id]);s.invoices.push({...safeObj(i.data),id:i.legacy_ref,customer:i.c_ref,site:i.site_ref,date:i.issue_date,period:i.period_start?String(i.period_start).slice(0,7):null,status:i.status,type:i.invoice_type,po:i.customer_reference,net:Number(i.net),vat:Number(i.vat),gross:Number(i.gross),lines:lines.rows.map(l=>({...safeObj(l.data),type:l.line_type,description:l.description,amount:Number(l.amount),workOrder:l.wo_ref,site:l.site_ref,vehicle:l.v_ref,reference:l.source_ref}))})}
 const docs=await client.query(`SELECT d.*,c.legacy_ref c_ref,s.legacy_ref s_ref,v.legacy_ref v_ref,w.legacy_ref w_ref,i.legacy_ref i_ref FROM documents d LEFT JOIN customers c ON c.id=d.customer_id LEFT JOIN sites s ON s.id=d.site_id LEFT JOIN vehicles v ON v.id=d.vehicle_id LEFT JOIN work_orders w ON w.id=d.work_order_id LEFT JOIN invoices i ON i.id=d.invoice_id`);s.documents=docs.rows.map(d=>({...safeObj(d.data),id:d.legacy_ref,customer:d.c_ref,site:d.s_ref,vehicle:d.v_ref,workOrder:d.w_ref,invoice:d.i_ref,name:d.filename,visibility:d.visibility}));
 const prs=await client.query(`SELECT p.*,c.legacy_ref c_ref,s.legacy_ref s_ref,v.legacy_ref v_ref FROM portal_requests p JOIN customers c ON c.id=p.customer_id LEFT JOIN sites s ON s.id=p.site_id LEFT JOIN vehicles v ON v.id=p.vehicle_id`);s.portalRequests=prs.rows.map(p=>({...safeObj(p.data),id:p.legacy_ref,customer:p.c_ref,site:p.s_ref,vehicle:p.v_ref,status:p.status,emergency:p.emergency,requestType:p.request_type,vehicleStatus:p.vehicle_status,fault:p.description,createdAt:p.created_at}));
 const pa=await client.query(`SELECT p.*,c.legacy_ref c_ref FROM portal_actions p JOIN customers c ON c.id=p.customer_id`);s.portalActions=pa.rows.map(p=>({...safeObj(p.data),id:p.legacy_ref,customer:p.c_ref,type:p.action_type,refType:p.ref_type,refId:p.ref_legacy,summary:p.summary,reason:p.reason,priority:p.priority,status:p.status,createdAt:p.created_at}));
 const pr=await client.query(`SELECT r.legacy_ref,r.data,v.* FROM pricing_rules r JOIN pricing_rule_versions v ON v.pricing_rule_id=r.id ORDER BY v.version_no`);for(const p of pr.rows){const d=safeObj(p.data);const key=d.contract||d.contractRef||p.legacy_ref.replace(/^PR-/,'');s.pricingRules[key]={...d,id:p.legacy_ref,version:p.version_no,effective:p.effective_from,labour:Number(p.labour_rate),partsMarkup:Number(p.parts_markup_percent),thirdMarkup:Number(p.third_party_markup_percent),mileage:Number(p.mileage_rate),vat:Number(p.vat_percent)}}
 const conf=await client.query("SELECT value FROM system_meta WHERE key='compatibility_config'");Object.assign(s,conf.rows[0]?.value||{});return s;
}

function invoiceSites(state,inv){const set=new Set();if(inv.site)set.add(inv.site);for(const l of (inv.lines||[])){if(l.site)set.add(l.site);if(l.workOrder){const w=state.wos.find(x=>x.id===l.workOrder);if(w)set.add(w.s)}if(l.reference){const w=state.wos.find(x=>x.id===l.reference);if(w)set.add(w.s)}}return[...set]}
function documentVisible(d,user,state,allowedSites){if(d.visibility==='Internal Kooner Only')return false;if(d.site&&!allowedSites.has(d.site))return false;if(d.workOrder){const w=state.wos.find(x=>x.id===d.workOrder);if(!w||!allowedSites.has(w.s))return false}if(d.vehicle){const v=state.vehicles.find(x=>x.id===d.vehicle);if(!v||!allowedSites.has(v.s))return false}if(d.visibility==='Customer Finance Only'&&!user.permissions.includes('portal.finance'))return false;if(d.visibility==='Specific Site/User Role'){const aS=d.allowedSites||[],aR=d.allowedRoles||[],aU=d.allowedUsers||[];if(!aS.length&&!aR.length&&!aU.length)return false;if(aS.length&&!aS.some(x=>allowedSites.has(x)))return false;if(aR.length&&!aR.some(x=>user.roles.includes(x)||user.roles.includes(String(x).toLowerCase().replace(/ /g,'_'))))return false;if(aU.length&&!aU.includes(user.legacy_ref)&&!aU.includes(user.id))return false}return true}
async function buildLegacyState(user){
 return tx(async client=>{let s=await fullLegacyState(client),version=await getStateVersion(client);
  if(user.user_type==='customer'){
   const c=(await client.query('SELECT legacy_ref FROM customers WHERE id=$1',[user.customer_id])).rows[0]?.legacy_ref;const sr=await client.query(`SELECT si.legacy_ref FROM user_scopes us JOIN sites si ON si.id=us.site_id WHERE us.user_id=$1 AND us.site_id IS NOT NULL`,[user.id]);const sites=new Set(sr.rows.map(x=>x.legacy_ref));s.customers=s.customers.filter(x=>x.id===c);s.sites=s.sites.filter(x=>sites.has(x.id));s.contracts=s.contracts.filter(x=>x.c===c);s.vehicles=s.vehicles.filter(x=>x.c===c&&sites.has(x.s));s.wos=s.wos.filter(x=>x.c===c&&sites.has(x.s));s.techs=s.techs.map(x=>({id:x.id,name:x.name,role:x.role,group:x.group,base:x.base,status:x.status,van:x.van}));s.defects=[];s.portalActions=[];s.pricingRules={};s.invoices=s.invoices.filter(i=>i.customer===c&&user.permissions.includes('portal.finance')&&(()=>{const is=invoiceSites(s,i);const customerWide=user.permissions.includes('portal.finance.all_sites');return customerWide||(is.length&&is.every(x=>sites.has(x)))})());s.documents=s.documents.filter(d=>d.customer===c&&documentVisible(d,user,s,sites));s.portalRequests=s.portalRequests.filter(r=>r.customer===c&&(!r.site||sites.has(r.site)));s.settings={};s.mobileSettings={};s.mobileDevice={};
  }else if(user.roles.includes('technician')){
   const tr=await client.query('SELECT legacy_ref FROM technicians WHERE user_id=$1',[user.id]);const tid=tr.rows[0]?.legacy_ref;const allowedWos=new Set(s.wos.filter(w=>(w.att||[]).some(a=>(a.tech||[]).includes(tid))).map(w=>w.id));s.wos=s.wos.filter(w=>allowedWos.has(w.id));const vids=new Set(s.wos.map(w=>w.v)),sids=new Set(s.wos.map(w=>w.s)),cids=new Set(s.wos.map(w=>w.c));s.vehicles=s.vehicles.filter(v=>vids.has(v.id)).map(v=>({...v,internalCost:undefined}));s.sites=s.sites.filter(x=>sids.has(x.id));s.customers=s.customers.filter(x=>cids.has(x.id));s.contracts=[];s.pricingRules={};s.invoices=[];s.documents=s.documents.filter(d=>d.visibility!=='Internal Kooner Only'&&(!d.workOrder||allowedWos.has(d.workOrder)));s.defects=[];s.portalActions=[];s.portalRequests=[];s.techs=s.techs.filter(t=>t.id===tid).map(t=>({...t,cost:undefined,internalCost:undefined}));s.mobileSettings={selectedTech:tid};
  }
  return{legacyState:s,stateVersion:version,serverTime:new Date().toISOString(),mode:'Database/API Backed'}
 })
}
module.exports={upsertLegacyState,buildLegacyState,audit,WO_STATUSES,ATT_STATUSES,EST_STATUSES,BILL_STATUSES};
